### ISSUE TITLE
agent container_logs worker: Actor crashed with  Docker::Error::NotFoundError

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1127]
Looks like the `start` function is supposed to handle the `NotFoundError` by stopping, but the debug logging happens outside of the `begin..rescue` block.

```
kontena-agent | E, [2016-10-13T09:00:52.910487 #1] ERROR -- : Actor crashed!
kontena-agent | Docker::Error::NotFoundError: No such container: 1c73976e6812de66f1165e74c8c677342341e95b09b0623aed29a3eb28c61762
kontena-agent | 
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:46:in `rescue in request'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:151:in `block (2 levels) in <class:Container>'
kontena-agent |     /app/lib/docker/container.rb:87:in `cached_json'
kontena-agent |     /app/lib/docker/container.rb:7:in `name'
kontena-agent |     /app/lib/kontena/workers/container_log_worker.rb:21:in `start'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent |     /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'

```

**Comment by SpComb** [comment]
Seems like the `NotFoundError` rescue case is also broken:

```
Oct 25 08:56:39 terom-xenial-node1 docker[22805]: E, [2016-10-25T08:56:39.949849 #1] ERROR -- : Actor crashed!
Oct 25 08:56:39 terom-xenial-node1 docker[22805]: NoMethodError: undefined method `stop' for #<Kontena::Workers::ContainerLogWorker:0x00562962ca6c50>
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /app/lib/kontena/workers/container_log_worker.rb:49:in `rescue in start'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /app/lib/kontena/workers/container_log_worker.rb:23:in `start'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
Oct 25 08:56:39 terom-xenial-node1 docker[22805]:         /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```
