### ISSUE TITLE
grid env and grid current show different tokens..

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1135]
I noticed this because I was unable to join an agent using the token given by `kontena grid env`. I had previously added and removed a grid. Here is a session log:

~~~
12:12:41 AM root@test1
~ # kontena grid env
KONTENA_URI=wss://***.***.***.***/
KONTENA_TOKEN=kontena-zZuuJJgwVfZNY/gjnBMzL***REDACTED***
12:12:43 AM root@test1
~ # kontena grid current
mytest:
  uri: wss://***.***.***.***/
  token: 1qNX4G8+M710mS2rdk2R8alJmbSjsLqeVHD0vdTOy+x3aZDsHW+02EudYbWbnH1GSt8z6tWh7f18oEa/hMDBQw==
  stats:
    nodes: 0 of 0
    cpus: 0
    load: 0.0 0.0 0.0
    memory: 0.0 of 0.0 GB
    filesystem: 0.0 of 0.0 GB
    users: 1
    services: 0
    containers: 0
12:12:53 AM root@test1
~ # kontena grid rm mytest
Destructive command. To proceed, type "mytest" or re-run this command with --force option.
> mytest
removed mytest
12:13:27 AM root@test1
~ # kontena grid env
No grid selected. Use: kontena grid env <name>, or select a grid with: kontena grid use <name>
12:13:30 AM root@test1
~ # kontena grid create mytest2
Using grid: mytest2
12:13:49 AM root@test1
~ # kontena grid env
KONTENA_URI=wss://***.***.***.***/
KONTENA_TOKEN=kontena-zZuuJJgwVfZNY/gjnBMzL***REDACTED***
12:13:56 AM root@test1
~ # kontena grid current
mytest2:
  uri: wss://***.***.***.***/
  token: 7gQBY2oCI5nveC4j3igdgi4s1IpMUEKt2rA7w1l85AobnSvvWouRokLObNVImsFjNet7HuNnyqF9IMRWIoqs0w==
  stats:
    nodes: 0 of 0
    cpus: 0
    load: 0.0 0.0 0.0
    memory: 0.0 of 0.0 GB
    filesystem: 0.0 of 0.0 GB
    users: 1
    services: 0
    containers: 0
~~~

So it seems the `grid env` command is stuck on some previous grid token and doesn't get updated by `grid use`.

**Comment by SpComb** [comment]
Looks like the token that `kontena grid env` shows is actually the access token used by the CLI to talk to the server.

Definitely a bug in `kontena grid env`, it makes no sense to have a combination of the websocket URL used by the agent and the access token used by the CLI.

**Comment by SpComb** [comment]
This was changed for the upcoming 0.16 auth changes, and it looks like `kontena grid env` is current broken in master: `DEBUG=1 bundle exec bin/kontena grid env`

```
Running #<Kontena::MainCommand:0x00000000bfdd30> -- callback matcher = 'nil'
Running #<Kontena::Cli::GridCommand:0x00000000be0898> -- callback matcher = 'nil'
Running #<Kontena::Cli::Grids::EnvCommand:0x00000000bd33c8> -- callback matcher = 'grids env'
D, [2016-10-14T10:08:59.450726 #6289] DEBUG -- CONFIG: Loading configuration from /home/kontena/.kontena_client.json
D, [2016-10-14T10:08:59.452657 #6289] DEBUG -- CONFIG: Configuration loaded with 4 servers.
D, [2016-10-14T10:08:59.452700 #6289] DEBUG -- CONFIG: Current master: foo
D, [2016-10-14T10:08:59.452745 #6289] DEBUG -- CONFIG: Current grid: development
/home/kontena/kontena/kontena/cli/lib/kontena/cli/grids/env_command.rb:24:in `execute': undefined method `find' for nil:NilClass (NoMethodError)
	from /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:181:in `run'
	from /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.0.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:181:in `run'
	from /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.0.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:181:in `run'
	from /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from bin/kontena:16:in `<main>'
```
