### ISSUE TITLE
Improve container exec error handling

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#1140]
When trying to exec in a container that is restarting:

```
➜  kontena container exec restarting-container-1 echo "hello"
{"code":500,"message":"Docker::Error::ConflictError: Container 703d5a5735457b4c905347f919978a580833530d92939d03e355a7c29cccfb21 is restarting, wait until the container is running\n","backtrace":["/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:48:in `rescue in request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in \u003cclass:Connection\u003e'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/exec.rb:22:in `create'","/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:64:in `exec'","/app/lib/kontena/rpc/docker_container_api.rb:111:in `exec'","/app/lib/kontena/rpc_server.rb:40:in `handle_request'","/app/lib/kontena/websocket_client.rb:108:in `block in on_message'","/usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'"]}
```

**Comment by SpComb** [comment]
With current 1.3.0.dev CLI/server/agent this loks even worse:

```
$ bundle exec bin/kontena container exec core-01/redis-1 echo test
 [error] 500 : Internal Server Error (/v1/containers/development/core-01/redis-1/exec)
```

Some `DEBUG` shows that for a stopped container, the server is returning something like `{"code":500,"message":"Docker::Error::ServerError: Container a70cb0e0e47a270f665de7ceac6f1557c3e03e562cd41064053d178cd496da62 is not running\n","backtrace":[...]}`

**Comment by SpComb** [comment]
Looks like this changed for the final 1.3 release... now the CLI just sees an `exit 0` without any output in this case :confused:   #2598
