### ISSUE TITLE
Cannot delete service that is linked to another service

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1166]
I deployed an app while testing straight from the kontena/examples repo: [redis-sentinel](https://github.com/kontena/examples/blob/master/redis-sentinel/3.0/kontena.yml)
I did add an additional very simple service just to play with the etcdctl tool:

```
  etcdtest:
    build: .
    image: registry.kontena.local/etcdctl:latest
```

I then tried to stop and remove the app:

```
~/kontena-test # kontena app stop
stopping redis-sentinel-node
stopping redis-sentinel-monitor
stopping redis-sentinel-lb
stopping redis-sentinel-etcdtest
~/kontena-test # kontena app rm
Destructive command. Are you sure? (y/n) or re-run this command with --force option.
> y
deleting node ... fail
/usr/local/rvm/gems/ruby-2.1.1/gems/kontena-cli-0.15.5/lib/kontena/client.rb:209:in `handle_error_response': {"service":"Cannot delete service that is linked to another service (redis-sentinel-monitor)"} (Exception)
        from /usr/local/rvm/gems/ruby-2.1.1/gems/kontena-cli-0.15.5/lib/kontena/client.rb:130:in `delete'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/kontena-cli-0.15.5/lib/kontena/cli/services/services_helper.rb:251:in `delete_service'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/kontena-cli-0.15.5/lib/kontena/cli/apps/remove_command.rb:48:in `block in delete'
        from /usr/local/rvm/gems/ruby-2.1.1/gems/shell-spinner-1.0.4/lib/shell-spinner.rb:48:in `block in with_spinner'
```

**Comment by colinmollenhour** [comment]
Looks like it might be because one of the containers (the one I added) did not deploy and the stop command didn't stop it:

~~~
~/kontena-test # kontena service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS               
⊝ redis-sentinel-etcdtest                                    0 / 1      no       deploying                              
⊝ redis-sentinel-monitor                                     0 / 5      yes      stopped                                
⊝ redis-sentinel-node                                        0 / 5      yes      stopped                                
⊝ redis-sentinel-lb                                          0 / 2      no       stopped                                
⊝ registry                                                   1 / 1      yes      running                                
~~~

The Dockerfile for the "etcdtest" image is this:

~~~
FROM alpine:3.2

# Install etcdctl
RUN apk add --update-cache curl tar \
    && curl -sSL https://github.com/coreos/etcd/releases/download/v2.2.1/etcd-v2.2.1-linux-amd64.tar.gz \
    | tar -vxz -C /usr/local/bin --strip=1 etcd-v2.2.1-linux-amd64/etcdctl \
    && chown root:root /usr/local/bin/etcdctl \
    && apk del --purge curl tar \
    && rm -rf /var/cache/apk/*

CMD ["/usr/local/bin/boot"]
~~~

I honestly don't even know what /usr/local/bin/boot does, I just wanted to run a container with etcdctl installed so I could run etcdctl and inspect keys in Kontena's etcd server.

**Comment by jakolehm** [comment]
Most likely this is a bug in the kontena cli (it does not resolve service dependencies correctly). Fix is coming: https://github.com/kontena/kontena/pull/1160

**Comment by jnummelin** [comment]
Sorting should be fixed now via stacks functionality.
