### ISSUE TITLE
Cli can't register first master, because no current master can be found

### ISSUE THREAD

**Issue by james-nesbitt** [kontena/kontena#1240]
With empty configuration, trying to register my first master, I get a complaint that no current master can be found, followed by instructions to try to register to a master.

```
> % kontena master login http://X.X.X.X 
Running #<Kontena::MainCommand:0x0056302f3ed720> -- callback matcher = 'nil'
Running #<Kontena::Cli::MasterCommand:0x0056302f3d2a38> -- callback matcher = 'nil'
Running #<Kontena::Cli::Master::LoginCommand:0x0056302f41bf30> -- callback matcher = 'master login'
D, [2016-10-27T10:28:47.938554 #1] DEBUG -- CONFIG: Configuration file not found, using default settings.
D, [2016-10-27T10:28:47.938729 #1] DEBUG -- CONFIG: Configuration loaded with 0 servers.
D, [2016-10-27T10:28:47.938753 #1] DEBUG -- CONFIG: Current master: default
D, [2016-10-27T10:28:47.938788 #1] DEBUG -- CONFIG: Current grid: (not selected)
/usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/config.rb:313:in `require_current_master': You are not logged into a Kontena Master. Use: kontena master login (ArgumentError)
```

```
-> % kontena version
cli: 0.16.0
```

Full error stack:
```
/usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/config.rb:313:in `require_current_master': You are not logged into a Kontena Master. Use: kontena master login (ArgumentError)
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/common.rb:139:in `require_current_master'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/common.rb:179:in `client'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/master/login_command.rb:170:in `block in get_authorization_url'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/common.rb:80:in `vspinner'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/master/login_command.rb:169:in `get_authorization_url'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/master/login_command.rb:212:in `response_from_web_flow'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/cli/master/login_command.rb:55:in `execute'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/command.rb:181:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/command.rb:181:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/lib/kontena/command.rb:181:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.0/bin/kontena:16:in `<top (required)>'
	from /usr/bin/kontena:23:in `load'
	from /usr/bin/kontena:23:in `<main>'
```

**Comment by james-nesbitt** [comment]
this occurs even when starting with no .kontena_client.json in use, but it is using the **kontena cli docker image**.

**Comment by james-nesbitt** [comment]
will test again if made avialable in the kontena cli image.

**Comment by jakolehm** [comment]
@james-nesbitt can you try like this: `kontena master login --name master http://X.X.X.X`

**Comment by james-nesbitt** [comment]
will do.

**Comment by james-nesbitt** [comment]
```
james@redrum [05:22:30 PM] [~/.local/share] 
-> % kontena master login --name kontena-testing http://94.237.28.154 
Running #<Kontena::MainCommand:0x0055bfa9cddf20> -- callback matcher = 'nil'
Running #<Kontena::Cli::MasterCommand:0x0055bfa9cc7158> -- callback matcher = 'nil'
Running #<Kontena::Cli::Master::LoginCommand:0x0055bfa9cc40e8> -- callback matcher = 'master login'
D, [2016-10-27T14:24:16.723411 #1] DEBUG -- CONFIG: Configuration file not found, using default settings.
D, [2016-10-27T14:24:16.723567 #1] DEBUG -- CONFIG: Configuration loaded with 0 servers.
D, [2016-10-27T14:24:16.723591 #1] DEBUG -- CONFIG: Current master: default
D, [2016-10-27T14:24:16.723624 #1] DEBUG -- CONFIG: Current grid: (not selected)
Opening browser to https://cloud.kontena.io

If you are running this command over an ssh connection or it's
otherwise not possible to open a browser from this terminal
then you must use the --remote flag or use a pregenerated
access token using the --token option.

Once the authentication is complete you can close the browser
window or tab and return to this window to continue.

If the browser does not open, try visiting this URL manually:                            
                                                             https://cloud.kontena.io/login/oauth/authorize?response_type=code&client_id=8da2d19131b340e188d5b8f64adfb3d3&scope=user&state=ba136cb94c771270cf6f9d4be0483300d77cbf20e4e8c6f67cdd50fc09819d21&redirect_uri=http%3A%2F%2F94.237.28.154%2Fcb

      Waiting for connection on port 42219..
```

**Comment by james-nesbitt** [comment]
OK I think that I managed to get the login to work.

First I had to also add the --remote,
then the code that was given to me from the kontena web UI was incorrect:

```
 kontena master login --code {code{&server_name={name}
```

Should have been:
```
 kontena master login --code={code} name={name http://X.X.X.X 
```

**Comment by james-nesbitt** [comment]
feel free to mark the issue as closed, if you think that having a --name as required is expected behaviour.

**Comment by kke** [comment]
No, the issue  is real and fixed now in the referenced PR.
