### ISSUE TITLE
Agent WeaveWorker Timeout::Error

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1360]
```
I, [2016-11-21T13:02:55.861014 #1]  INFO -- Kontena::Agent: initializing agent (version 0.17.0.pre1)
...
I, [2016-11-21T13:03:23.842491 #1]  INFO -- Kontena::NetworkAdapters::Weave: image weaveworks/weave:1.7.2 pulled 
...
I, [2016-11-21T13:03:23.894770 #1]  INFO -- Kontena::Workers::WeaveWorker: initialized
...
E, [2016-11-21T13:03:27.755543 #1] ERROR -- : Actor crashed!
Timeout::Error: Timeout while: waiting for weave running
	/app/lib/kontena/helpers/wait_helper.rb:39:in `wait!'
	/app/lib/kontena/helpers/weave_helper.rb:16:in `wait_weave_running?'
	/app/lib/kontena/workers/weave_worker.rb:40:in `on_container_event'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2016-11-21T13:03:27.781119 #1]  INFO -- Kontena::Workers::WeaveWorker: initialized
```

**Comment by SpComb** [comment]
Looks like the logic in the agent `WaitHelper` is wrong:

```ruby
      def __still_waiting?(wait_until)
        wait_until > Time.now.to_f
      end
```

And the tests are broken:

```ruby
  describe '#__still_waiting?' do
    it 'return true if more waiting needed' do
      wait_until = Time.now.to_f - 1.0
      expect(subject.__still_waiting?(wait_until)).to be_truthy
    end

    it 'return true if more waiting needed' do
      wait_until = Time.now.to_f + 1.0
      expect(subject.__still_waiting?(wait_until)).to be_falsey
    end
  end
```

**Comment by SpComb** [comment]
This seems to happen when the agent `EventWorker` gets a Docker event before weave is running, and the `WeaveWorker` immediately hits the `Timeout::Error`.
