### ISSUE TITLE
kontena app does not recognize compose labels

### ISSUE THREAD

**Issue by mklatsky** [kontena/kontena#1387]
I have a docker-compose file for testing an app which uses labels. 
The compose file is here: http://pastebin.com/cgdkPm7T

I perform a 'kontena app init' which completes successfully.

When I run 'kontena app config' or 'kontena app deploy' with DEBUG=true, I receive the following error:

$ DEBUG=true kontena app config
Running #<Kontena::MainCommand:0x007fbc2da1bb98> -- callback matcher = 'nil'
Running #<Kontena::Cli::AppCommand:0x007fbc2da087a0> -- callback matcher = 'nil'
Running #<Kontena::Cli::Apps::ConfigCommand:0x007fbc2da00aa0> -- callback matcher = 'apps config'
D, [2016-11-23T10:15:14.315746 #39525] DEBUG -- CONFIG: Loading configuration from /Users/mk/.kontena_client.json
D, [2016-11-23T10:15:14.316359 #39525] DEBUG -- CONFIG: Configuration loaded with 3 servers.
D, [2016-11-23T10:15:14.316404 #39525] DEBUG -- CONFIG: Current master: nameless-snow-9-admin
D, [2016-11-23T10:15:14.316450 #39525] DEBUG -- CONFIG: Current grid: test
/usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/service_extender.rb:19:in `extend': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:148:in `extend_config'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:107:in `process_config'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:92:in `block in parse_services'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:91:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:91:in `parse_services'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:32:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:27:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/yaml/reader.rb:27:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/common.rb:23:in `services_from_yaml'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/cli/apps/config_command.rb:16:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:181:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:181:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:181:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/kontena-cli-0.16.3/bin/kontena:16:in `<top (required)>'
	from /usr/local/bin/kontena:23:in `load'
	from /usr/local/bin/kontena:23:in `<main>'

When I remove the labels from the docker-compose file, rerun 'kontena app init', and run 'kontena app deploy', the app is deployed successfully but not with the labels applied of course.

**Comment by jnummelin** [comment]
So the idea of the labels here is to get them as labels for the containers? There's couple of problems here. 

First, looking at the docker-compose reference guide, I think labels should be on the top level under the service and not within environment. https://docs.docker.com/compose/compose-file/#/labels

Second issue is that Kontena yml does not support labels ATM.

**Comment by colinmollenhour** [comment]
+1 for supporting "labels" in Kontena yml compatible with docker-compose.yml ([ref](https://docs.docker.com/compose/compose-file/#labels-1))

Use case: datadog monitoring service discovery can match containers based on the value of a label named `com.datadoghq.sd.check.id`. Probably plenty of other uses.
