### ISSUE TITLE
Agent Weave actor does not crash gracefully

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1395]
Consider the following error case, where the kontena-ipam returns a HTTP 400 error on a conflict retry timeout:

```
I, [2016-11-23T15:09:08.847558 #1]  INFO -- Kontena::ServicePods::Creator: creating service: null-redis5-70
E, [2016-11-23T15:09:10.693540 #1] ERROR -- : Actor crashed!
Kontena::NetworkAdapters::IpamError: Bad Request
	/app/lib/kontena/network_adapters/ipam_client.rb:121:in `handle_error_response'
	/app/lib/kontena/network_adapters/ipam_client.rb:62:in `rescue in reserve_address'
	/app/lib/kontena/network_adapters/ipam_client.rb:51:in `reserve_address'
	/app/lib/kontena/network_adapters/weave.rb:151:in `modify_create_opts'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2016-11-23T15:09:10.698736 #1] ERROR -- Kontena::ServicePods::Creator: Kontena::NetworkAdapters::IpamError: Bad Request
E, [2016-11-23T15:09:10.703886 #1] ERROR -- Kontena::ServicePods::Creator: /app/lib/kontena/network_adapters/ipam_client.rb:121:in `handle_error_response'
```

The exception raised by the `Actor[:network_adapter].modify_create_opts(...)` call crashes the `Weave` actor. This leads to a cascade of further failures:

```
E, [2016-11-23T15:09:10.705245 #1] ERROR -- Kontena::Workers::EventWorker: Celluloid::DeadActorError: attempted to call a dead actor: adapter_image?
E, [2016-11-23T15:09:10.705478 #1] ERROR -- Kontena::Workers::EventWorker: Celluloid::DeadActorError: attempted to call a dead actor: adapter_image?
E, [2016-11-23T15:09:10.705693 #1] ERROR -- Kontena::Workers::EventWorker: Celluloid::DeadActorError: attempted to call a dead actor: adapter_image?
E, [2016-11-23T15:09:10.705990 #1] ERROR -- Kontena::Workers::EventWorker: Celluloid::DeadActorError: attempted to call a dead actor: adapter_image?
E, [2016-11-23T15:09:10.706187 #1] ERROR -- Kontena::Workers::EventWorker: Celluloid::DeadActorError: attempted to call a dead actor: adapter_image?
E, [2016-11-23T15:09:10.706409 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
E, [2016-11-23T15:09:10.709897 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
E, [2016-11-23T15:09:10.712376 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
E, [2016-11-23T15:09:10.718086 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
E, [2016-11-23T15:09:10.718725 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
E, [2016-11-23T15:09:10.719217 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
I, [2016-11-23T15:09:10.724690 #1]  INFO -- Kontena::NetworkAdapters::Weave: initialized
E, [2016-11-23T15:09:10.724932 #1] ERROR -- Kontena::ServicePods::Creator: Celluloid::DeadActorError: attempted to call a dead actor: network_ready?
```

Until the Celluloid supervisor manages to restart the actor and it re-initializes. However, the re-initialization after the actor crash causes it to lose any state in the form of instance variables, which complicates recovery for any state formed by any one-time startup Celluloid signals. The re-initializing actor after a crash will never receive any of the one-time Celluloid signals sent during the normal startup process.

See #1392 for one example of this issue, concerning the `Weave@ipam_running` state. The Weave actor's `ipam_ready?` relies on the @ipam_running = true state set on the Celluloid `ipam:start` event. However, this is only sent once during the agent startup, which means that a crashing Weave actor will re-initialize the `@ipam_running` = false state and remain stuck there. This then leads to complete agent failure in the form of `WeaveHelper#wait_network_ready?` timing out, because the `ipam_ready?` never recovers.

**Comment by SpComb** [comment]
Similar happens for the Kontena::NetworkAdapters::IpamCleaner` actor:

```
kontena-agent | D, [2016-11-24T12:24:11.111676 #1] DEBUG -- NetworkAdapters::IpamClient: Request GET /KontenaIPAM.Cleanup: 500 Internal Server Error: {"Error":"Failed to open TCP connection to localhost:2379 (Connection refused - connect(2) for \"localhost\" port 2379)"}
kontena-agent | E, [2016-11-24T12:24:11.112490 #1] ERROR -- : Actor crashed!
kontena-agent | Kontena::NetworkAdapters::IpamError: Failed to open TCP connection to localhost:2379 (Connection refused - connect(2) for "localhost" port 2379)
kontena-agent | 	/app/lib/kontena/network_adapters/ipam_client.rb:117:in `handle_error_response'
kontena-agent | 	/app/lib/kontena/network_adapters/ipam_client.rb:94:in `rescue in cleanup_index'
kontena-agent | 	/app/lib/kontena/network_adapters/ipam_client.rb:91:in `cleanup_index'
kontena-agent | 	/app/lib/kontena/network_adapters/ipam_cleaner.rb:28:in `block in cleanup_ipam'
kontena-agent | 	/app/lib/kontena/network_adapters/ipam_cleaner.rb:25:in `loop'
kontena-agent | 	/app/lib/kontena/network_adapters/ipam_cleaner.rb:25:in `cleanup_ipam'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
kontena-agent | I, [2016-11-24T12:24:11.136312 #1]  INFO -- Kontena::NetworkAdapters::IpamCleaner: initialized
```

It will no longer perform any IPAM cleanups.

**Comment by jrasanen** [comment]
I wonder if this is related:

```
kontena-agent | E, [2016-12-27T13:17:00.242480 #1] ERROR -- Kontena::ServicePods::Creator: Timeout::Error: Timeout while: waiting for all network components running
kontena-agent | E, [2016-12-27T13:17:00.242659 #1] ERROR -- Kontena::ServicePods::Creator: /app/lib/kontena/helpers/wait_helper.rb:39:in `wait!'
kontena-agent | /app/lib/kontena/helpers/weave_helper.rb:22:in `wait_network_ready?'
kontena-agent | /app/lib/kontena/service_pods/creator.rb:32:in `perform'
kontena-agent | /app/lib/kontena/service_pods/creator.rb:70:in `block in perform_async'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
kontena-agent | E, [2016-12-27T13:18:48.801832 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
kontena-agent | E, [2016-12-27T13:18:50.041818 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
```

**Comment by SpComb** [comment]
> I wonder if this is related:

Not, this presumably means that the grid's etcd cluster is broken, and the kontena-ipam is unable to operate. This may be caused by offline initial nodes, or weave issues. Ensure that all of your grid's initial nodes are up and healthy.
