### ISSUE TITLE
Kontena CLI errors on Windows 10 (1511 - 10586.679)

### ISSUE THREAD

**Issue by WoLfulus** [kontena/kontena#1401]
I'm running into troubles running Kontena CLI inside a Windows machine. Looking at the error I thought it could be something related to Ruby, but I tried installing different versions of Ruby but doesn't help at all.

```
C:\Users\WoLfulus>kontena aws master create
Running #<Kontena::MainCommand:0x37f1100> -- callback matcher = 'nil'
Running #<Kontena::Plugin::AwsCommand:0x37fa340> -- callback matcher = 'nil'
Running #<Kontena::Plugin::Aws::MasterCommand:0x37f8048> -- callback matcher = 'nil'
Running #<Kontena::Plugin::Aws::Master::CreateCommand:0x38028d8> -- callback matcher = 'master create'
 _               _
| | _____  _ __ | |_ ___ _ __   __ _
| |/ / _ \| '_ \| __/ _ \ '_ \ / _` |
|   < (_) | | | | ||  __/ | | | (_| |
|_|\_\___/|_| |_|\__\___|_| |_|\__,_|
-------------------------------------
Copyright (c)2016 Kontena, Inc.

O sistema não pode encontrar o caminho especificado.
D, [2016-11-24T20:03:15.072101 #8580] DEBUG -- CONFIG: Configuration file not found, using default settings.
D, [2016-11-24T20:03:15.083855 #8580] DEBUG -- CONFIG: Configuration loaded with 0 servers.
D, [2016-11-24T20:03:15.085357 #8580] DEBUG -- CONFIG: Current master: default
D, [2016-11-24T20:03:15.093400 #8580] DEBUG -- CONFIG: Current grid: (not selected)
> Enter a name for this Kontena Master:  kontena-masterr)
> Select OAuth2 authentication provider:  (Use arrow keys, press Enter to select)
‣ Kontena Cloud (recommended)
  Custom
  None (single user mode)C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:93:in `sysread': sysread for buffered IO (IOError)
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:93:in `read_char'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:78:in `block (3 levels) in read_keypress'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader/mode.rb:36:in `raw'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader/mode.rb:36:in `raw'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:77:in `block (2 levels) in read_keypress'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader/mode.rb:24:in `echo'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:76:in `block in read_keypress'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:60:in `call'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:60:in `buffer'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/reader.rb:75:in `read_keypress'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/list.rb:167:in `render'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt/list.rb:96:in `call'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt.rb:231:in `invoke_select'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/tty-prompt-0.7.1/lib/tty/prompt.rb:167:in `select'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callbacks/master/deploy/05_before_deploy_configuration_wizard.rb:74:in `block in before'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callbacks/master/deploy/05_before_deploy_configuration_wizard.rb:21:in `unless_param'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callbacks/master/deploy/05_before_deploy_configuration_wizard.rb:72:in `before'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:46:in `block (3 levels) in run_callbacks'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:43:in `each'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:43:in `block (2 levels) in run_callbacks'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:42:in `each'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:42:in `block in run_callbacks'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:41:in `each'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/callback.rb:41:in `run_callbacks'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:80:in `run_callbacks'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:177:in `run'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:181:in `run'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:181:in `run'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/lib/kontena/command.rb:181:in `run'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
        from C:/Ruby/lib/ruby/gems/2.0.0/gems/kontena-cli-0.16.3/bin/kontena:16:in `<top (required)>'
        from C:/Ruby/bin/kontena:23:in `load'
        from C:/Ruby/bin/kontena:23:in `<main>'
```

I can't use commandline since it asks for OAuth and breaks again.

**Comment by kke** [comment]
I think this is a problem of the tty-prompt gem. As a workaround you can answer all of the questions on the command line by using the params listed in`kontena aws master create --help`

**Comment by WoLfulus** [comment]
It doesn't help. OAuth breaks it again. Is this authentication really necessary, or is there any way to manually configure the token?

**Comment by kke** [comment]
`kontena cloud login` does not work either?

**Comment by WoLfulus** [comment]
I'm not sure when it didn't work. I literally spent the whole day yesterday trying to make these commands work that I don't remember. I'll test again in a few minutes.

**Comment by kke** [comment]
I made a PR for possibly fixing this on tty-prompt: https://github.com/piotrmurach/tty-prompt/pull/26

**Comment by WoLfulus** [comment]
I had to install Linux Mint to make it work. :(
I'll be waiting for a fix on Windows.

**Comment by kke** [comment]
You can use `--skip-auth-provider` during master create.

25.11.2016 13.19 "WoLfulus" <notifications@github.com> kirjoitti:

**Comment by kke** [comment]
Did you get any visual feedback on the interactive menus on windows? Or did you ever see one?

I'm now trying to replicate on a windows box, but I can't get the IOError. However, I can't get any visual feedback from pressing the arrow keys either. Also the "blips" look completely wrong.

![image](https://cloud.githubusercontent.com/assets/224971/20686023/91a86b98-b5bf-11e6-9566-60bda2ad2180.png)

**Comment by kke** [comment]
ping @kontena/core-platform 

I think we may to do some workarounds for windows.

Perhaps use a "dumb" prompt, such as enum_select 

```ruby
prompt.enum_select("Select an editor?", choices)
# =>
#
# Select an editor?
#   1) /bin/nano
#   2) /usr/bin/vim.basic
#   3) /usr/bin/vim.tiny
#   Choose 1-3 [2]:
```

**Comment by kke** [comment]
Also:

```ruby
prompt.yes?("Sure?")
prompt.ask("Talk to me:")
```

Pressing Y + enter on the first Y/n prompt leaks the enter to the second one every time.

**Comment by kke** [comment]
https://github.com/adoxa/ansicon

That may help for some problems, but not all. Essentially I think this just won't work on windows without implementing some "dumb" mode that uses no console trickery.

**Comment by kke** [comment]
Everything works great using [Windows Subsystem For For Linux](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) which seems excellent in many ways any ways.

There's still a problem when trying to launch a browser, it's a big hassle (you need to install x-server such as Ming on your windows host and `export DISPLAY` and so on). 

This can be quite easily fixed by adding an option to cloud login so that it doesn't try to open a browser, but just outputs the url to visit manually. I added it in my local installation and it works great, just copy-paste the url to your regular browser and it completes fine.

Another option is to use Cygwin.

Ruby on regular Windows just does not work very well.

**Comment by yuruki** [comment]
If Kontena is aiming for wide-spread adoption, it is essential that CLI works also on Windows. Right now this gets in the way of a lot of people.

**Comment by WoLfulus** [comment]
Yeah, we're using Rancher because we couldn't get started with Kontena.
