### ISSUE TITLE
Azure Master Provisioning - undefined local variable or method `virtual_machine' 

### ISSUE THREAD

**Issue by leowmjw** [kontena/kontena#1456]
Versions (OSX):

```
leow$ kontena version
cli: 1.0.0

leow$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
```

Machines are deployed but it fails the last step as below:
```
> Enter a name for this Kontena Master:  kontena-master
> Select OAuth2 authentication provider:  None (single user mode)

You have selected to use Kontena Master in single user mode. You can configure an authentication provider later. For more information, see here: www.kontena.io/docs/using-kontena/authentication

    *   Creating an Azure Virtual Machine kontena-master-proud-bird-53 .. /Enter PEM pass phrase:

    *   Creating an Azure Virtual Machine kontena-master-proud-bird-53 .. -Enter PEM pass phrase:

 [done] Creating an Azure Virtual Machine kontena-master-proud-bird-53     
 [done] Waiting for kontena-master-proud-bird-53 to start     
 [done] Retrieving Kontena Master version     
 [done] Kontena Master  is now running at http://13.93.2.99
/Library/Ruby/Gems/2.0.0/gems/kontena-plugin-azure-0.2.1/lib/kontena/machine/azure/master_provisioner.rb:96:in `run!': undefined local variable or method `virtual_machine' for #<Kontena::Machine::Azure::MasterProvisioner:0x007f96745e29c0> (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/kontena-plugin-azure-0.2.1/lib/kontena/plugin/azure/master/create_command.rb:23:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/kontena-cli-1.0.0/bin/kontena:16:in `<top (required)>'
	from /usr/bin/kontena:23:in `load'
	from /usr/bin/kontena:23:in `<main>'
```

**Comment by matti** [comment]
You might want to try https://github.com/AppGyver/konterraform as the azure plugin creates virtual machines using the "classic" or legacy mode and not resource manager.

**Comment by leowmjw** [comment]
Thanks @matti; looks good; a nice resource for one like me learning Terraform.  Hit some problems standing that up :(  but reported under that repo :)

**Comment by kke** [comment]
You can upgrade the azure plugin now, it should work.

`kontena plugin uninstall azure && kontena plugin install azure`
