### ISSUE TITLE
possible to create stacks that break stack command

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1478]
While experimenting with stack variables I managed to inject something that breaks everything:
```
➜  stacks DEBUG=true dontena stack ls

D, [2016-12-02T12:45:48.420606 #31737] DEBUG -- CONFIG: Loading configuration from /Users/mpa/.kontena_client.json
D, [2016-12-02T12:45:48.423373 #31737] DEBUG -- CONFIG: Configuration loaded with 29 servers.
D, [2016-12-02T12:45:48.423418 #31737] DEBUG -- CONFIG: Current master: devmaster
D, [2016-12-02T12:45:48.423473 #31737] DEBUG -- CONFIG: Current grid: dev
Running #<Kontena::MainCommand:0x007fd3da289460> -- callback matcher = 'nil'
Running #<Kontena::Cli::StackCommand:0x007fd3da219b60> -- callback matcher = 'nil'
Running #<Kontena::Cli::Stacks::ListCommand:0x007fd3d99f0380> -- callback matcher = 'stacks list'
/Users/mpa/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:20:in `split': undefined method `ascii_only?' for nil:NilClass (NoMethodError)
	from /Users/mpa/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /Users/mpa/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /Users/mpa/dev/kontena/cli/lib/kontena/client.rb:46:in `initialize'
	from /Users/mpa/dev/kontena/cli/lib/kontena/command.rb:153:in `new'
	from /Users/mpa/dev/kontena/cli/lib/kontena/command.rb:153:in `rescue in verify_current_master_token'
	from /Users/mpa/dev/kontena/cli/lib/kontena/command.rb:149:in `verify_current_master_token'
	from /Users/mpa/dev/kontena/cli/lib/kontena/command.rb:181:in `run'
	from /Users/mpa/.rvm/gems/ruby-2.3.1/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/mpa/dev/kontena/cli/lib/kontena/command.rb:187:in `run'
	from /Users/mpa/.rvm/gems/ruby-2.3.1/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/mpa/dev/kontena/cli/lib/kontena/command.rb:187:in `run'
	from /Users/mpa/.rvm/gems/ruby-2.3.1/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /usr/local/bin/dontena:16:in `<main>'
```

**Comment by jnummelin** [comment]
Any idea what was that "something"?

**Comment by kke** [comment]
It's actually a bug elsewhere, not stacks.

(Your token has expired)

**Comment by matti** [comment]
???

**Comment by matti** [comment]
![slack](https://cloud.githubusercontent.com/assets/3893/20833140/b2dbcac4-b896-11e6-8540-3a99a43c0f4c.png)

**Comment by matti** [comment]
^- this token?

**Comment by kke** [comment]
Yes.

Before command execution, the CLI checked if you have a working token, and noticed that indeed you do, but it has expired. 

It tried to refresh it, but there was a bug that made it use the whole current_master object as the URL for refresh request, instead of using just the actual URL field of the current_master.
