### ISSUE TITLE
Stack variable errors should be more friendly

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1506]
With a missing `type:`

```yaml
variables:
  web_path:
    from:
      env: WEB_PATH
      prompt: Publish at given HTTP /path
    default: /${STACK}
```

The error does not say which variable is bad: ` [error] No handler for type`

The error should be something like "Missing type for variable web_path". Any other errors should also include the name of the variable, or the line number in the YAML file.

```
D, [2016-12-08T14:24:34.523552 #18755] DEBUG -- CONFIG: Loading configuration from /home/kontena/.kontena_client.json
D, [2016-12-08T14:24:34.524152 #18755] DEBUG -- CONFIG: Configuration loaded with 5 servers.
D, [2016-12-08T14:24:34.524186 #18755] DEBUG -- CONFIG: Current master: development
D, [2016-12-08T14:24:34.524217 #18755] DEBUG -- CONFIG: Current grid: development
Running #<Kontena::MainCommand:0x00000002261540> -- callback matcher = 'nil'
Running #<Kontena::Cli::StackCommand:0x0000000226f438> -- callback matcher = 'nil'
Running #<Kontena::Cli::Stacks::UpgradeCommand:0x0000000226ccd8> -- callback matcher = 'stacks upgrade'
Running Kontena.run("vault read --return wordpress-red_wordpress-mysql-root", returning: result
Running #<Kontena::MainCommand:0x00000000e8b520> -- callback matcher = 'nil'
Running #<Kontena::Cli::VaultCommand:0x0000000257eea8> -- callback matcher = 'nil'
Running #<Kontena::Cli::Vault::ReadCommand:0x0000000257c8b0> -- callback matcher = 'vault read'
D, [2016-12-08T14:24:34.611964 #18755] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true}
Command completed, result: "yCIUkdDqJgtK7mURTzWxn6e7NIjtBWAs" status: 0
Running Kontena.run("vault read --return wordpress-red_wordpress-mysql-password", returning: result
Running #<Kontena::MainCommand:0x00000000e695d8> -- callback matcher = 'nil'
Running #<Kontena::Cli::VaultCommand:0x00000002596850> -- callback matcher = 'nil'
Running #<Kontena::Cli::Vault::ReadCommand:0x00000002595180> -- callback matcher = 'vault read'
D, [2016-12-08T14:24:34.691414 #18755] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true}
Command completed, result: "d6jfh0qjYwvv3fCawpaNmnxQ8IckO6lZ" status: 0
bundler: failed to load command: bin/kontena (bin/kontena)
NameError: No handler for type 
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/type.rb:39:in `for'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/option.rb:174:in `handler'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/option.rb:238:in `valid?'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/group.rb:51:in `block in valid?'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/group.rb:51:in `each'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/group.rb:51:in `all?'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.5.0/lib/opto/group.rb:51:in `valid?'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/reader.rb:56:in `parse_variables'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/reader.rb:65:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:33:in `stack_from_yaml'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/upgrade_command.rb:20:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
  bin/kontena:16:in `<top (required)>'
```

**Comment by kke** [comment]
Fixed in opto 1.5.2 (`gem uninstall opto && gem install opto`)
