### ISSUE TITLE
Unable to deploy kontena nodes in 1.0.1 (docker-compose)

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#1539]
Flow:

1. deploy kontena-master with docker-compose
2. create grid with initial-size=3
3. deploy 1st node with docker-compose
4. "kontena node ls" shows node online
5. check logs:

kontena-ipam:
```
127.0.0.1 - - [10/Dec/2016:12:18:17 +0000] "POST /Plugin.Activate HTTP/1.1" 500 41 7.0052
2016-12-10 12:18:25 - Net::HTTPFatalError - 500 "Internal Server Error":
        /usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
        /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:145:in `process_http_request'
        /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:114:in `api_execute'
        /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/keys.rb:39:in `set'
        /app/app/etcd_client.rb:88:in `set'
        /app/lib/etcd_model.rb:236:in `mkdir'
        /app/plugin.rb:26:in `ensure_models'
        /app/plugin.rb:63:in `block in <class:IpamPlugin>'
[...]
127.0.0.1 - - [10/Dec/2016:12:18:33 +0000] "POST /Plugin.Activate HTTP/1.1" 500 41 7.0043
2016-12-10 12:18:40 - Net::HTTPFatalError - 500 "Internal Server Error":
        /usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
        /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:145:in `process_http_request'
        /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:114:in `api_execute'
        /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/keys.rb:39:in `set'
        /app/app/etcd_client.rb:88:in `set'
        /app/lib/etcd_model.rb:459:in `create!'
        /app/lib/etcd_model.rb:250:in `create'
        /app/app/models/subnet.rb:79:in `create'
        /app/app/models/subnet.rb:59:in `reserve'
        /app/app/models/address_pool.rb:37:in `create!'
        /app/lib/etcd_model.rb:250:in `create'
        /app/app/models/address_pool.rb:28:in `create'
        /app/lib/etcd_model.rb:278:in `create_or_get'
        /app/app/mutations/address_pools/request.rb:81:in `request_static'
        /app/app/mutations/address_pools/request.rb:32:in `execute'
[...]
127.0.0.1 - - [10/Dec/2016:12:18:40 +0000] "POST /IpamDriver.RequestPool HTTP/1.1" 500 41 7.0085
127.0.0.1 - - [10/Dec/2016:12:21:33 +0000] "GET /KontenaIPAM.Cleanup HTTP/1.1" 200 15 0.0036
2016-12-10 12:22:03 - Mutations::ValidationException - AddressPool not found: kontena:
        /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:88:in `run!'
        /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:36:in `run!'
        /app/plugin.rb:136:in `block in <class:IpamPlugin>'
        /usr/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
``` 

```
docker exec kontena-etcd /usr/bin/etcdctl cluster-health
member 2bb868f677c2405 is unreachable: no available published client urls
member b29731e29fee6555 is unreachable: no available published client urls
member eb7aed324a8314b5 is unreachable: no available published client urls
cluster is unhealthy
```

kontena-etcd
```
2016-12-10 12:39:11.240008 I | raft: 2bb868f677c2405 became candidate at term 1118
2016-12-10 12:39:11.240026 I | raft: 2bb868f677c2405 received vote from 2bb868f677c2405 at term 1118
2016-12-10 12:39:11.240057 I | raft: 2bb868f677c2405 [logterm: 1, index: 3] sent vote request to b29731e29fee6555 at term 1118
2016-12-10 12:39:11.240082 I | raft: 2bb868f677c2405 [logterm: 1, index: 3] sent vote request to eb7aed324a8314b5 at term 1118
2016-12-10 12:39:12.600187 E | etcdserver: publish error: etcdserver: request timed out
2016-12-10 12:39:12.639979 I | raft: 2bb868f677c2405 is starting a new election at term 1118
2016-12-10 12:39:12.640036 I | raft: 2bb868f677c2405 became candidate at term 1119
2016-12-10 12:39:12.640054 I | raft: 2bb868f677c2405 received vote from 2bb868f677c2405 at term 1119
2016-12-10 12:39:12.640082 I | raft: 2bb868f677c2405 [logterm: 1, index: 3] sent vote request to eb7aed324a8314b5 at term 1119
2016-12-10 12:39:12.640105 I | raft: 2bb868f677c2405 [logterm: 1, index: 3] sent vote request to b29731e29fee6555 at term 1119
2016-12-10 12:39:13.939957 I | raft: 2bb868f677c2405 is starting a new election at term 1119
2016-12-10 12:39:13.940008 I | raft: 2bb868f677c2405 became candidate at term 1120
```

wave logs:
```
INFO: 2016/12/10 12:13:26.945047 Command line options: map[name:ca:dd:16:be:df:42 nickname:backend datapath:datapath dns-domain:kontena.local dns-effective-listen-address:172.17.0.1 http-addr:127.0.0.1:6784 trusted-subnets: dns-listen-address:172.17.0.1:53 ipalloc-range: port:6783 resolv-conf:/var/run/weave/etc/resolv.conf]
INFO: 2016/12/10 12:13:26.947069 Communication between peers via untrusted networks is encrypted.
INFO: 2016/12/10 12:13:26.956120 Our name is ca:dd:16:be:df:42(backend)
INFO: 2016/12/10 12:13:26.956190 Launch detected - using supplied peer list: []
INFO: 2016/12/10 12:13:26.958628 Docker API on unix:///var/run/docker.sock: &[GitCommit=23cf638 GoVersion=go1.6.2 Os=linux Arch=amd64 KernelVersion=4.5.7-std-3 BuildTime=Tue, 27 Sep 2016 12:25:38 +1300 Version=1.12.1 ApiVersion=1.24]
INFO: 2016/12/10 12:13:26.959561 Listening for DNS queries on 172.17.0.1
INFO: 2016/12/10 12:13:26.959633 Sniffing traffic on datapath (via ODP)
INFO: 2016/12/10 12:13:26.974455 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2016/12/10 12:13:27.667713 Weave version 1.8.2 is available; please update at https://github.com/weaveworks/weave/releases/download/v1.8.2/weave
INFO: 2016/12/10 12:13:28.888407 Discovered local MAC 1e:42:d3:61:f6:46
INFO: 2016/12/10 12:13:29.098297 Discovered local MAC c2:78:99:91:ef:50
INFO: 2016/12/10 12:13:29.426767 Discovered local MAC ca:dd:16:be:df:42
INFO: 2016/12/10 12:13:37.517950 [nameserver ca:dd:16:be:df:42] adding entry for 550c8e0712160411856382aa2e936577be92f33e6f27d6257e460b2398667207: etcd.kontena.local. -> 10.81.0.1
INFO: 2016/12/10 12:28:26.958863 Expired MAC 1e:42:d3:61:f6:46 at ca:dd:16:be:df:42(backend)
INFO: 2016/12/10 12:28:26.958952 Expired MAC c2:78:99:91:ef:50 at ca:dd:16:be:df:42(backend)
```

kontena-agent
```
I, [2016-12-10T12:38:41.972831 #1]  INFO -- Kontena::Workers::StatsWorker: starting collection
I, [2016-12-10T12:39:21.220923 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
E, [2016-12-10T12:39:33.430958 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Kontena::NetworkAdapters::IpamError: AddressPool not found: kontena
```

**Comment by SpComb** [comment]
You cannot operate an `--initial-size=3` grid with only one node, you need a minimum of two online initial nodes to achieve etcd quorum, and allow the IPAM to operate.

 #1468 will improve the `kontena node ls` output to clarify this.

**Comment by jalberto** [comment]
@SpComb same errors after deploying 2nd node

I tried:

1. deploy 3 nodes at once: didn't works
2. deploy node01 then node02 (as for you indication): same errors

**Comment by jalberto** [comment]
@SpComb this can be the upstream issue:

https://github.com/weaveworks/weave/issues/2427

**Comment by SpComb** [comment]
> In other hand wave seems to be using the public IP for node communication instead of the private IP.

If you want kontena to use the private IPs for weave, then you need to label the nodes with the same `region=...`

> a workaround will be to pass --name to weave using gridname+nodename to generate the name (forget this, it will not solve the issue as weave use productid for other stuff too)

Worth looking into if Kontena can use the node_id to provide weave with a unique name.

> Also this issue will affect mostly baremetal nodes (not only scaleway)

What baremetal hosts are these, if they have identical product UUIDs in DMI? online.net?

**Comment by jakolehm** [comment]
Just tested with two Scaleway nodes and got this:
```
INFO: 2016/12/10 15:26:58.600471 ->[10.1.167.45:6783|ca:dd:16:be:df:42(scw-9246dd)]: connection shutting down due to error: local "ca:dd:16:be:df:42(scw-9246dd)" and remote "ca:dd:16:be:df:42(scw-d16d95)" peer names collision
```

**Comment by jalberto** [comment]
> If you want kontena to use the private IPs for weave, then you need to label the nodes with the same region=...

they are in same region

> Worth looking into if Kontena can use the node_id to provide weave with a unique name.

no really, productid is used for the virtual MAC too, so even if the name is unique, the MAC will conflict

> What baremetal hosts are these, if they have identical product UUIDs in DMI? online.net?

I find same problem in online.net & scaleway, also checked friend datacenter, same issue.
In the weave issue you can check there is more people hitting this using localnetowkrs with dell hardware.

**Comment by jakolehm** [comment]
@jalberto could you try to install Kontena Agent with `WEAVEEXEC_IMAGE=jakolehm/weaveexec` environment variable? This image generates random mac on each boot so it "should work".. I tested it with Scaleway and it seemed to work.

**Comment by jalberto** [comment]
@jakolehm thanks! I will.
but in the weave issue a weave dev mention that whatever used to generate the iface must be permanent and resistant to reboots.

**Comment by jakolehm** [comment]
Opened separate issue about this: #1541
