### ISSUE TITLE
[CLI 1.0.1] VPN key creation errors with undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by BenHall** [kontena/kontena#1546]
After upgrading, I'm getting this error with my cluster: 
```
$ DEBUG=true kontena vpn create --node kontena-node --ip 172.17.0.16                                  
D, [2016-12-12T17:39:49.559739 #6413] DEBUG -- CONFIG: Loading configuration from /home/ubuntu/.konten
a_client.json                                                                                         
D, [2016-12-12T17:39:49.560126 #6413] DEBUG -- CONFIG: Configuration loaded with 1 servers.           
D, [2016-12-12T17:39:49.560185 #6413] DEBUG -- CONFIG: Current master: CompanyMasterCluster           
D, [2016-12-12T17:39:49.560230 #6413] DEBUG -- CONFIG: Current grid: prod                             
Running #<Kontena::MainCommand:0x00000001ac7410> -- callback matcher = 'nil'                          
Running #<Kontena::Cli::VpnCommand:0x00000001afa400> -- callback matcher = 'nil'                      
Running #<Kontena::Cli::Vpn::CreateCommand:0x00000001b1c1e0> -- callback matcher = 'vpn create'       
D, [2016-12-12T17:39:49.629254 #6413] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect
_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true}                            
D, [2016-12-12T17:39:49.741916 #6413] DEBUG -- CLIENT: Request GET /v1/stacks/prod/vpn: 404 Not Found:
 {}                                                                                                   
 [done] Deploying vpn service                                                                         
 [fail] Generating vpn keys (this will take a while)                                                  
undefined method `[]' for nil:NilClass undefined method `[]' for nil:NilClass                         
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/cli/vpn/create_command.rb:66:in `wait_for_confi
guration_to_finish'                                                                                   
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/cli/vpn/create_command.rb:54:in `block in execu
te'                                                                                                   
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/cli/spinner.rb:124:in `spin'                   
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/cli/common.rb:278:in `spinner'                 
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/cli/vpn/create_command.rb:53:in `execute'      
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/command.rb:187:in `run'                        
/var/lib/gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'                
/var/lib/gems/2.0.0/gems/kontena-cli-1.0.1/lib/kontena/command.rb:187:in `run'                        
/var/lib/gems/2.0.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'    
```

**Comment by jakolehm** [comment]
Fixed in #1537
