### ISSUE TITLE
kontena container ls --all -> undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1574]
It seems like I have multiple data volume containers that are missing a `node` field:

```json
{
   "containers":[
      {
         "id":"development/core-01/registry-api-1-volumes",
         "name":"registry-api-1-volumes",
         "container_id":"c1e1902e0f88ba5ceff22f6f17f3b368f40b8c4c6658203b775d37c488af8403",
         "grid_id":"development",
         "node":{
            "id":"XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5",
            "connected":false,
            "last_seen_at":"2016-12-19T14:40:33.461Z",
            "name":"core-01",
            "labels":null,
            "public_ip":"87.93.49.130",
            "private_ip":"192.168.66.101",
            "node_number":1,
            "grid":{
               "id":"development",
               "name":"development",
               "initial_size":1
            }
         },
         "service_id":"development/registry/api",
         "created_at":"2016-11-21T14:53:36.699Z",
         "updated_at":"2016-12-19T14:22:34.911Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-11-21 14:53:15 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"kontena/registry:2.2",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"c1e1902e0f88",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      },
      {
         "id":"development/core-01/wordpress-mysql-1-volumes",
         "name":"wordpress-mysql-1-volumes",
         "container_id":"09e74abf458c15033086b5cf7f47df5a419b4c7fbc0e7468d0637537bcd7f103",
         "grid_id":"development",
         "node":{
            "id":"XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5",
            "connected":false,
            "last_seen_at":"2016-12-19T14:40:33.461Z",
            "name":"core-01",
            "labels":null,
            "public_ip":"87.93.49.130",
            "private_ip":"192.168.66.101",
            "node_number":1,
            "grid":{
               "id":"development",
               "name":"development",
               "initial_size":1
            }
         },
         "service_id":"development/wordpress/mysql",
         "created_at":"2016-11-28T10:46:14.970Z",
         "updated_at":"2016-12-19T14:22:34.721Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-11-28 10:45:20 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"mariadb:5.5",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GOSU_VERSION=1.7",
            "MARIADB_MAJOR=5.5",
            "MARIADB_VERSION=5.5.53+maria-1~wheezy"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"09e74abf458c",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      },
      {
         "id":"development/core-01/wordpress-wordpress-1-volumes",
         "name":"wordpress-wordpress-1-volumes",
         "container_id":"7a7c033fd526f94c6d8902c177564a380352b6bef25acc62db4a75ac69dae05e",
         "grid_id":"development",
         "node":{
            "id":"XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5",
            "connected":false,
            "last_seen_at":"2016-12-19T14:40:33.461Z",
            "name":"core-01",
            "labels":null,
            "public_ip":"87.93.49.130",
            "private_ip":"192.168.66.101",
            "node_number":1,
            "grid":{
               "id":"development",
               "name":"development",
               "initial_size":1
            }
         },
         "service_id":"development/wordpress/wordpress",
         "created_at":"2016-11-28T10:46:14.982Z",
         "updated_at":"2016-12-19T14:22:34.662Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-11-28 10:45:19 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"wordpress:4.6",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PHPIZE_DEPS=autoconf \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
            "PHP_INI_DIR=/usr/local/etc/php",
            "APACHE_CONFDIR=/etc/apache2",
            "APACHE_ENVVARS=/etc/apache2/envvars",
            "PHP_EXTRA_BUILD_DEPS=apache2-dev",
            "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
            "GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3",
            "PHP_VERSION=5.6.28",
            "PHP_URL=https://secure.php.net/get/php-5.6.28.tar.xz/from/this/mirror",
            "PHP_ASC_URL=https://secure.php.net/get/php-5.6.28.tar.xz.asc/from/this/mirror",
            "PHP_SHA256=07187ba2870f89cef334cd2ad6cb801aeec5eaf283da0293a9a6be75d6786d11",
            "PHP_MD5=1e01c66b2e67ab3b56a6180ee560fe4c",
            "WORDPRESS_VERSION=4.6.1",
            "WORDPRESS_SHA1=027e065d30a64720624a7404a1820e6c6fff1202"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"7a7c033fd526",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      },
      {
         "id":"null-cli-wordpress-1-volumes",
         "name":"null-cli-wordpress-1-volumes",
         "container_id":"13b6adc3814bd87ffc91f4734201de177e4b94267dafa93022ca39777841003f",
         "grid_id":"development",
         "service_id":null,
         "created_at":"2016-12-05T16:01:35.107Z",
         "updated_at":"2016-12-09T13:29:31.877Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-11-30 14:02:11 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"wordpress:4.1",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PHP_INI_DIR=/usr/local/etc/php",
            "PHP_EXTRA_BUILD_DEPS=apache2-dev",
            "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
            "PHP_VERSION=5.6.8",
            "WORDPRESS_VERSION=4.1.2",
            "WORDPRESS_UPSTREAM_VERSION=4.1.2",
            "WORDPRESS_SHA1=9e9745bb8a1166622de866076eac73a49cb3eba0"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"13b6adc3814b",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      },
      {
         "id":"null-cli-mysql-1-volumes",
         "name":"null-cli-mysql-1-volumes",
         "container_id":"93b474e0b7b6be38e4ae08f9287e8a4c4bdf2e97276c0d2875523180b580a915",
         "grid_id":"development",
         "service_id":null,
         "created_at":"2016-12-05T16:01:35.146Z",
         "updated_at":"2016-12-09T13:29:31.988Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-11-30 14:01:21 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"mariadb:5.5",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GOSU_VERSION=1.7",
            "MARIADB_MAJOR=5.5",
            "MARIADB_VERSION=5.5.53+maria-1~wheezy"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"93b474e0b7b6",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      },
      {
         "id":"wordpress-green-wordpress-1-volumes",
         "name":"wordpress-green-wordpress-1-volumes",
         "container_id":"1258b729ac9e94106d1bcfc08d318e3eefce18a2cae07e0e5b98c17a28adb550",
         "grid_id":"development",
         "service_id":null,
         "created_at":"2016-12-05T16:01:35.205Z",
         "updated_at":"2016-12-09T13:29:32.388Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-11-29 11:21:24 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"wordpress:4.6.1",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "PHPIZE_DEPS=autoconf \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
            "PHP_INI_DIR=/usr/local/etc/php",
            "APACHE_CONFDIR=/etc/apache2",
            "APACHE_ENVVARS=/etc/apache2/envvars",
            "PHP_EXTRA_BUILD_DEPS=apache2-dev",
            "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
            "GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3",
            "PHP_VERSION=5.6.28",
            "PHP_URL=https://secure.php.net/get/php-5.6.28.tar.xz/from/this/mirror",
            "PHP_ASC_URL=https://secure.php.net/get/php-5.6.28.tar.xz.asc/from/this/mirror",
            "PHP_SHA256=07187ba2870f89cef334cd2ad6cb801aeec5eaf283da0293a9a6be75d6786d11",
            "PHP_MD5=1e01c66b2e67ab3b56a6180ee560fe4c",
            "WORDPRESS_VERSION=4.6.1",
            "WORDPRESS_SHA1=027e065d30a64720624a7404a1820e6c6fff1202"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"1258b729ac9e",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      },
      {
         "id":"development/core-03/wordpress-green-mysql-1-volumes",
         "name":"wordpress-green-mysql-1-volumes",
         "container_id":"2f70d4027e06893938c3ec10795940673bf1ec4e4d73c960dea56b2a8997a628",
         "grid_id":"development",
         "node":{
            "id":"UXTT:TPWP:6OQM:3UKS:EPB4:MOQD:DYYT:N42X:VSR5:IIM3:VDCP:22IC",
            "connected":false,
            "last_seen_at":"2016-12-09T13:49:30.545Z",
            "name":"core-03",
            "labels":null,
            "public_ip":"82.181.116.101",
            "private_ip":"192.168.66.103",
            "node_number":3,
            "grid":{
               "id":"development",
               "name":"development",
               "initial_size":1
            }
         },
         "service_id":"development/wordpress-green/mysql",
         "created_at":"2016-12-09T13:31:02.058Z",
         "updated_at":"2016-12-09T13:31:02.048Z",
         "started_at":"0001-01-01T00:00:00.000Z",
         "finished_at":"0001-01-01T00:00:00.000Z",
         "deleted_at":null,
         "status":"stopped",
         "state":{
            "error":"",
            "exit_code":0,
            "pid":0,
            "oom_killed":false,
            "paused":false,
            "restarting":false,
            "dead":false,
            "running":false
         },
         "deploy_rev":"2016-12-09 13:30:22 UTC",
         "service_rev":null,
         "instance_number":1,
         "image":"mariadb:5.5",
         "cmd":[
            "echo",
            "Data only container"
         ],
         "env":[
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GOSU_VERSION=1.7",
            "MARIADB_MAJOR=5.5",
            "MARIADB_VERSION=5.5.53+maria-1~wheezy"
         ],
         "volumes":[

         ],
         "ip_address":null,
         "hostname":"2f70d4027e06",
         "domainname":"",
         "network_settings":{
            "bridge":"",
            "gateway":"",
            "ip_address":"",
            "ip_prefix_len":0,
            "mac_address":"",
            "port_mapping":null,
            "ports":null
         }
      }
   ]
}
```

#### `DEBUG=true bundle exec bin/kontena container ls -a`
```
D, [2016-12-20T10:45:18.975939 #8657] DEBUG -- CONFIG: Loading configuration from /home/kontena/.kontena_client.json
D, [2016-12-20T10:45:18.976576 #8657] DEBUG -- CONFIG: Configuration loaded with 3 servers.
D, [2016-12-20T10:45:18.976611 #8657] DEBUG -- CONFIG: Current master: development
D, [2016-12-20T10:45:18.976639 #8657] DEBUG -- CONFIG: Current grid: development
Running #<Kontena::MainCommand:0x00000002b7f690> -- callback matcher = 'nil'
Running #<Kontena::Cli::ContainerCommand:0x00000002b7cb98> -- callback matcher = 'nil'
Running #<Kontena::Cli::Containers::ListCommand:0x00000002b8bbc0> -- callback matcher = 'containers list'
D, [2016-12-20T10:45:19.030553 #8657] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true}
bundler: failed to load command: bin/kontena (bin/kontena)
NoMethodError: undefined method `[]' for nil:NilClass
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:19:in `block in execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:19:in `map'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:19:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
  bin/kontena:16:in `<top (required)>'
```

**Comment by jakolehm** [comment]
Do you have any idea how did you manage to get those ghost containers?

**Comment by SpComb** [comment]
There is no `dependent: :destroy` on the [`HostNode` `has_many :containers`](https://github.com/kontena/kontena/blob/d4dc9bd01fc8931e7b2fbf1478b98a0590260a76/server/app/models/host_node.rb#L51) relation, so those containers are presumably left over from a `kontena node rm`?

The `NodeCleanupJob` => `ContainerCleanupJob` is not going to kick in for orphaned containers.

**Comment by SpComb** [comment]
Up-to-date CLI traceback for this in 1.6.0.dev:

```
NoMethodError: undefined method `[]' for nil:NilClass
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:34:in `container_id'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:26:in `block in execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:81:in `format_row'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:90:in `block in rows'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:90:in `map'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:90:in `rows'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:67:in `table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:74:in `render'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:35:in `generate_table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:39:in `print_table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:25:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:216:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:216:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:216:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
  bin/kontena:22:in `<top (required)>'
```

**Comment by SpComb** [comment]
> There is no dependent: :destroy on the HostNode has_many :containers relation, so those containers are presumably left over from a kontena node rm?

OTOH there's an `after_destroy` hook...? https://github.com/kontena/kontena/blob/master/server/app/models/host_node.rb#L71-L73

**Comment by SpComb** [comment]
Unable to repro the orphaned containers, I don't see how the `HostNode` would get removed while leaving the containers behind... unless the server/mongo encounters some error during the `after_destroy` hook, but that doesn't seem likely enough.

Not filing a separate issue for the orphaned containers until there's some indication of that continuing to happen somehow.
