### ISSUE TITLE
Agent WebsocketClient gets stuck on connection close

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1601]
The Agent `Kontena::WebsocketClient` uses `Faye::WebSocket::Client` with `EventMachine` for the control channel to the master server. The client implements a keepalive timer, where every 30s it will send a websocket ping to the server, and wait up to 2000ms for a response.

If the `WebsocketClient` does not receive a pong response within 2000ms, it will call `@ws.close`, and mark itself as disconnected once it gets `@ws.on :close`. This triggers a reconnect using a new websocket. 

However, the [`Faye::WebSocket::Client#close`](https://github.com/faye/faye-websocket-ruby/blob/0.10.1/lib/faye/websocket/api.rb#L74) method calls the [`Websocket::Driver#close`](https://github.com/faye/websocket-driver-ruby/blob/0.6.3/lib/websocket/driver/hybi.rb#L147) method, which actually sends a websocket close frame... the `:close` event is only triggered once the server replies (or on some other protocol error). In the case of a dead TCP connection, this means that the `@ws.close` called after the keepalvie timeout does *NOT* provide any gurarantees as to when the `:close` event will be omitted.

This is easy to repro by blackholing the master from a node: `sudo ip ro add blackhole 192.168.66.1/32`

The agent notices that the websocket is dead, but it does not actually reconnect... not until the blackhole route is removed (`ip ro del blackhole 192.168.66.1/32`), and the TCP socket resumes sending (`ss -t` -> `Send-Q == 0`):

```
kontena-agent | I, [2016-12-30T12:06:56.173340 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
.... wait until dropping the blackhole route ....
kontena-agent | I, [2016-12-30T12:07:42.437398 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
kontena-agent | I, [2016-12-30T12:07:42.593559 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
kontena-agent | I, [2016-12-30T12:07:42.638189 #1]  INFO -- Kontena::WebsocketClient: connection established
```

**Comment by SpComb** [comment]
Newest `faye-websocket` git master just added a `CLOSE_TIMEOUT`, which might solve this exact issue: https://github.com/faye/faye-websocket-ruby/commit/07be5a24ef446db5d7e461ca1eaa9fa6aa7b7f21

However, this is not yet released, and I have some doubts as to how the `close` -> `CLOSE_TIMEOUT` timer -> `begin_close` -> `@stream.close_connection_after_writing` -> ... -> `finalize_close` -> `on :close` actually works... updating `faye-websocket` might works, but needs testing.

**Comment by SpComb** [comment]
It also looks like the agent `WebsocketClient` keepalive logic is broken after a reconnect; the ping timeout timer does not reset `@ping_timer = nil`, which means that the agent will not send keepalive pings after a reconnect.

**Comment by SpComb** [comment]
The agent should probably also fire the `websocket:disconnect` immediately when closing the connection, to queue up events? I think ATM it keeps sending event frames even after the `close`, which presumably get lost?

**Comment by SpComb** [comment]
It turns out that the `Thread.new { EventMachine.run }` would also silently swallow any exceptions in the EventMachine thread, leaving the websocket client completely dead.

Turning on `$DEBUG = true` reveals the following example of a legit `NameError` inside an `EM::Timer.new do ... end`, with some interesting side effects inside EventMachine..

```
kontena-agent | I, [2016-12-30T13:30:57.531295 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
kontena-agent | Exception `NameError' at /app/lib/kontena/websocket_client.rb:198 - undefined local variable or method `event' for #<Kontena::WebsocketClient:0x0055b9ef7b5968>
kontena-agent | I, [2016-12-30T13:30:57.537040 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66b5a8>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66b4b8>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66b3a0>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66b288>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66b170>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66b058>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66af68>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66ae78>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66ad88>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66ac98>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66aba8>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66aab8>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a950>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a838>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a720>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a608>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a4c8>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a3b0>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NoMethodError' at /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:211 - undefined method `kill!' for #<Thread:0x0055b9ef66a298>
kontena-agent | Did you mean?  kill
kontena-agent | Exception `NameError' at /app/lib/kontena/agent.rb:39 - undefined local variable or method `event' for #<Kontena::WebsocketClient:0x0055b9ef7b5968>
kontena-agent | Exception `IO::EAGAINWaitReadable' at <internal:prelude>:76 - Resource temporarily unavailable - read would block
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::TaskTerminated' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75 - task was terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | Exception `Celluloid::DeadActorError' at /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb:34 - actor already terminated
kontena-agent | /app/lib/kontena/websocket_client.rb:198:in `close': undefined local variable or method `event' for #<Kontena::WebsocketClient:0x0055b9ef7b5968> (NameError)
kontena-agent | 	from /app/lib/kontena/websocket_client.rb:182:in `block in verify_connection'
kontena-agent | 	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
kontena-agent | 	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
kontena-agent | 	from /app/lib/kontena/agent.rb:158:in `block in start_em'
kontena-agent exited with code 1
```
