### ISSUE TITLE
kontena aws create returning `require': cannot load such file

### ISSUE THREAD

**Issue by sallespro** [kontena/kontena#1643]
with kontena-cli-1.0.4, i got this `'require': cannot load such file`

`kontena aws master create --access-key X --secret-key Y --region us-east-1 --key-pair mine --vpc-id vpc-85121221 --type t2.micro --storage 100`

returns

```
> Select OAuth2 authentication provider:  Kontena Cloud (recommended)
D, [2017-01-10T15:41:09.127734 #14527] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true}
D, [2017-01-10T15:41:09.128166 #14527] DEBUG -- CLIENT: Requesting user info from https://cloud-api.kontena.io/user
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- kontena/machine/aws (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/kontena-plugin-aws-0.2.4/lib/kontena/plugin/aws/master/create_command.rb:28:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.0.4/lib/kontena/command.rb:187:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.0.4/lib/kontena/command.rb:187:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.0.4/lib/kontena/command.rb:187:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.0.4/lib/kontena/command.rb:187:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.0.4/bin/kontena:16:in `<top (required)>'
	from /usr/local/bin/kontena:23:in `load'
	from /usr/local/bin/kontena:23:in `<main>'
```

**Comment by jakolehm** [comment]
Do you have the latest version of AWS plugin installed?

**Comment by kke** [comment]
I got a different error, but indeed there seems to be some problem:

```
$ kontena aws master create
 _               _
| | _____  _ __ | |_ ___ _ __   __ _
| |/ / _ \| '_ \| __/ _ \ '_ \ / _` |
|   < (_) | | | | ||  __/ | | | (_| |
|_|\_\___/|_| |_|\__\___|_| |_|\__,_|
-------------------------------------
Copyright (c)2016 Kontena, Inc.

> Enter a name for this Kontena Master:  qwewqe
> Select OAuth2 authentication provider:  Kontena Cloud (recommended)
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate kontena-cli-1.0.4, because tty-prompt-0.10.0 conflicts with tty-prompt (~> 0.7.1) (Gem::ConflictError)
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `each'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /usr/local/Cellar/rbenv/1.0.0/versions/2.3.3/lib/ruby/gems/2.3.0/gems/kontena-plugin-aws-0.2.4/lib/kontena/plugin/aws/master/create_command.rb:28:in `execute'
        from /Users/kimmo/Projects/kontena/cli/lib/kontena/command.rb:187:in `run'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/kimmo/Projects/kontena/cli/lib/kontena/command.rb:187:in `run'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/kimmo/Projects/kontena/cli/lib/kontena/command.rb:187:in `run'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/kimmo/Projects/kontena/cli/lib/kontena/command.rb:187:in `run'
        from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
        from bin/kontena:16:in `<main>'
```

**Comment by kke** [comment]
I just had to `gem uninstall tty-prompt -v 0.10.0`

```
Successfully uninstalled tty-prompt-0.10.0
$ kontena aws master create
> Enter a name for this Kontena Master:  fgweefwwef
> Select OAuth2 authentication provider:  Kontena Cloud (recommended)
> AWS access key:
```

Probably a different problem.

**Comment by kke** [comment]
Looks like this has been solved in some other plugins earlier by changing the requires to use require_relative.

Releasing a new version any moment now.

**Comment by kke** [comment]
@sallespro New plugin version released. See if installing that helps.

**Comment by sallespro** [comment]
the updated plugin is ok.  thank you.
