### ISSUE TITLE
CLI etcd URLs fail when using the DEBUG instrumentor

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1714]
#### `DEBUG=true bundle exec bin/kontena etcd ls /kontena`

```
D, [2017-01-24T14:51:55.740648 #5590] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor}
[API Client Error]: 
bundler: failed to load command: bin/kontena (bin/kontena)
URI::InvalidComponentError: bad component(expected absolute path component): /v1/etcd/development//kontena?
  /usr/lib/ruby/2.3.0/uri/generic.rb:769:in `check_path'
  /usr/lib/ruby/2.3.0/uri/generic.rb:817:in `path='
  /home/kontena/kontena/kontena/cli/lib/kontena/debug_instrumentor.rb:12:in `instrument'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/excon-0.49.0/lib/excon/middlewares/instrumentor.rb:21:in `request_call'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/excon-0.49.0/lib/excon/middlewares/base.rb:15:in `request_call'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/excon-0.49.0/lib/excon/connection.rb:250:in `request'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:328:in `request'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:200:in `get'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/etcd/list_command.rb:20:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:187:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
  bin/kontena:16:in `<top (required)>'
```

**Comment by jakolehm** [comment]
wfm

```
$ DEBUG=true kontena etcd ls /
D, [2017-01-24T14:53:27.061697 #21424] DEBUG -- CONFIG: Loading configuration from /Users/jari/.kontena_client.json
D, [2017-01-24T14:53:27.063014 #21424] DEBUG -- CONFIG: Configuration loaded with 18 servers.
D, [2017-01-24T14:53:27.063053 #21424] DEBUG -- CONFIG: Current master: bitter-hill-2
D, [2017-01-24T14:53:27.063169 #21424] DEBUG -- CONFIG: Current grid: test
Running #<Kontena::MainCommand:0x007fe963694f70> -- callback matcher = 'nil'
Running #<Kontena::Cli::EtcdCommand:0x007fe96369eef8> -- callback matcher = 'nil'
Running #<Kontena::Cli::Etcd::ListCommand:0x007fe96369c900> -- callback matcher = 'etcd list'
D, [2017-01-24T14:53:27.289535 #21424] DEBUG -- CLIENT: Key looks like a self-signed cert made by Kontena CLI, setting verify_peer_host to 'Test'
D, [2017-01-24T14:53:27.289614 #21424] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true, :ssl_ca_file=>"/Users/jari/.kontena/certs/95.85.35.53.pem", :ssl_verify_peer_host=>"Test"}
/kontena
/coreos.com
```

**Comment by SpComb** [comment]
> wfm

With git master, using the `DEBUG -- CLIENT: Excon opts: {..., :instrumentor=>Kontena::DebugInstrumentor}`

**Comment by kke** [comment]
@jakolehm you used `ls /` tero was using `ls /kontena`

**Comment by SpComb** [comment]
It also happens with `/`

```
URI::InvalidComponentError: bad component(expected absolute path component): /v1/etcd/development//?
```
