### ISSUE TITLE
Agent crashed, won't restart even if unless-stopped

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1762]
kontena: 1.0.6

started with docker-compose as `unless-stopped` --> agent exited(1) and won't restart -- is this due docker (aka "a docker bug/feature") or has this something to do with Kontena?

```
$ docker inspect kontena-agent
<snip>
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
</snip>

<snip>
        "Path": "/app/bin/kontena-agent",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2017-02-01T03:06:07.287075405Z",
            "FinishedAt": "2017-02-01T09:56:33.14714848Z"
        },
        "Image": "sha256:4e0a2fcf6a665289304971466e4d1b3988db0d002327ff09df51efdacabe18e2",
        "ResolvConfPath": "/var/lib/docker/containers/210a4aa4472fdb10202227021519301ebb3d72d7fc1aeb57449e3bf34cbea11d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/210a4aa4472fdb10202227021519301ebb3d72d7fc1aeb57449e3bf34cbea11d/hostname",
        "HostsPath": "/var/lib/docker/containers/210a4aa4472fdb10202227021519301ebb3d72d7fc1aeb57449e3bf34cbea11d/hosts",
        "LogPath": "/var/lib/docker/containers/210a4aa4472fdb10202227021519301ebb3d72d7fc1aeb57449e3bf34cbea11d/210a4aa4472fdb10202227021519301ebb3d72d7fc1aeb57449e3bf34cbea11d-json.log",
        "Name": "/kontena-agent",
        "RestartCount": 2,
</snip>
```

```
$ docker logs kontena-agent
I, [2017-02-01T09:30:03.330948 #1]  INFO -- Kontena::Workers::StatsWorker: starting collection
I, [2017-02-01T09:34:49.323011 #1]  INFO -- Kontena::Workers::ContainerHealthCheckWorker: About to restart container lb-ingress-lb-3 as it's reported to be unhealthy
I, [2017-02-01T09:35:52.925377 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
I, [2017-02-01T09:37:07.115225 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
E, [2017-02-01T09:37:06.619859 #1] ERROR -- Kontena::Workers::StatsWorker: get /api/v1.2/subcontainers: Excon::Error::Timeout: read timeout reached
I, [2017-02-01T09:38:08.740838 #1]  INFO -- Kontena::Workers::StatsWorker: starting collection
I, [2017-02-01T09:38:10.345574 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
I, [2017-02-01T09:39:46.681432 #1]  INFO -- Kontena::Workers::NodeInfoWorker: publishing node information
E, [2017-02-01T09:47:25.146644 #1] ERROR -- Kontena::Workers::EventWorker: connection timeout... retrying
E, [2017-02-01T09:47:23.600026 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: read timeout reached
I, [2017-02-01T09:47:26.318872 #1]  INFO -- Kontena::Workers::ImageCleanupWorker: initialized
E, [2017-02-01T09:47:39.116248 #1] ERROR -- Kontena::Workers::EventWorker: Celluloid::DeadActorError: attempted to call a dead actor: adapter_image?
E, [2017-02-01T09:47:25.306264 #1] ERROR -- : Actor crashed!
Docker::Error::TimeoutError: read timeout reached
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:52:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:200:in `all'
	/app/lib/kontena/workers/image_cleanup_worker.rb:30:in `cleanup_images'
	/app/lib/kontena/workers/image_cleanup_worker.rb:25:in `block in start'
	/app/lib/kontena/workers/image_cleanup_worker.rb:23:in `loop'
	/app/lib/kontena/workers/image_cleanup_worker.rb:23:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-02-01T09:47:38.466478 #1] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:52:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)
	from /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	from /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	from /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker.rb:112:in `info'
	from /app/lib/kontena/websocket_client.rb:176:in `labels'
	from /app/lib/kontena/websocket_client.rb:70:in `connect'
	from /app/lib/kontena/websocket_client.rb:42:in `block in ensure_connect'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/em/timers.rb:56:in `fire'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `call'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /app/lib/kontena/agent.rb:160:in `block in start_em'
```

**Comment by SpComb** [comment]
Given all of the Docker-related API errors in the agent logs, it sounds like Docker has hung itself pretty badly. What OS and Docker version is this?

Do commands like `docker info` work when run in the CLI? The agent logs indicate that even that Docker API is timing out.

```
E, [2017-02-01T09:37:06.619859 #1] ERROR -- Kontena::Workers::StatsWorker: get /api/v1.2/subcontainers: Excon::Error::Timeout: read timeout reached
E, [2017-02-01T09:47:25.146644 #1] ERROR -- Kontena::Workers::EventWorker: connection timeout... retrying
E, [2017-02-01T09:47:23.600026 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: read timeout reached
Docker::Error::TimeoutError: read timeout reached
E, [2017-02-01T09:47:38.466478 #1] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!

# after restart?
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:52:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)
	from /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	from /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	from /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker.rb:112:in `info'
	from /app/lib/kontena/websocket_client.rb:176:in `labels'
	from /app/lib/kontena/websocket_client.rb:70:in `connect'
	from /app/lib/kontena/websocket_client.rb:42:in `block in ensure_connect'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/em/timers.rb:56:in `fire'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `call'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /app/lib/kontena/agent.rb:160:in `block in start_em'
```

**Comment by matti** [comment]
Maybe docker timed out (prob. because I was using the cheapest possible vm just to test things out), so at the end docker just gave up and then recovered so I was able to get that output.

I think this is safe to close?
