### ISSUE TITLE
Unable to install digitalocean plugin

### ISSUE THREAD

**Issue by mklatsky** [kontena/kontena#1763]
I am using kontena-cli 1.0.6.

OS is MacOS Sierra 10.12.2.

**kontena plugin install aws**  and **kontena plugin install vagrant** succeed. These plugins are installed at /usr/local/lib/ruby/gems/2.4.0/gems/.

However, attempts to install the digitalocean plugin fail with the debug message below. While I can easily fix perms to allow the install to succeed, that is not a proper solution.

Expected behavior: **kontena plugin install digitalocean** succeeds as standard, non-root user in same fashion as aws and vagrant plugin.

```
MapuAir:~ mklatsky$ kontena plugin install digitalocean
D, [2017-02-01T10:47:31.831555 #24386] DEBUG -- CONFIG: Loading configuration from /Users/mklatsky/.kontena_client.json
D, [2017-02-01T10:47:31.832086 #24386] DEBUG -- CONFIG: Configuration loaded with 3 servers.
D, [2017-02-01T10:47:31.832122 #24386] DEBUG -- CONFIG: Current master: (not selected)
D, [2017-02-01T10:47:31.832141 #24386] DEBUG -- CONFIG: Current grid: (not selected)
Running #<Kontena::MainCommand:0x007fc99b33d710> -- callback matcher = 'nil'
Running #<Kontena::Cli::PluginCommand:0x007fc99b334700> -- callback matcher = 'nil'
Running #<Kontena::Cli::Plugins::InstallCommand:0x007fc99b32e490> -- callback matcher = 'plugins install'
Running /usr/local/bin/gem install --no-ri --no-doc kontena-plugin-digitalocean
 [fail] Installing plugin digitalocean
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16
 ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16

/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/plugins/install_command.rb:29:in `block in install_plugin'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/spinner.rb:124:in `spin'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/common.rb:278:in `spinner'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/plugins/install_command.rb:27:in `install_plugin'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/plugins/install_command.rb:15:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/command.rb:187:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/command.rb:187:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/command.rb:187:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/bin/kontena:16:in `<top (required)>'
/usr/local/bin/kontena:22:in `load'
/usr/local/bin/kontena:22:in `<main>'
/usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/plugins/install_command.rb:29:in `block in install_plugin': ERROR:  While executing gem ... (Errno::EACCES) (RuntimeError)
    Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/spinner.rb:124:in `spin'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/common.rb:278:in `spinner'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/plugins/install_command.rb:27:in `install_plugin'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/cli/plugins/install_command.rb:15:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/command.rb:187:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/command.rb:187:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/lib/kontena/command.rb:187:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/kontena-cli-1.0.6/bin/kontena:16:in `<top (required)>'
	from /usr/local/bin/kontena:22:in `load'
	from /usr/local/bin/kontena:22:in `<main>'
```

**Comment by jakolehm** [comment]
1.1.0 should fix this (#1628)

**Comment by kke** [comment]
1.1.0 is out, does it work for you now?

**Comment by mklatsky** [comment]
I was able to successfully install the plugin without sudo using kontena-cli version 1.1.0. Thank you!
