### ISSUE TITLE
stack file service_link resolver fails if there are no matching services

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1765]
With

```yaml
variables:
  lb_link:
    type: string
    from:
      service_link:
        prompt: Link pls
        image: kontena/lb2
```

referencing an image that does not exist,

`DEBUG=true bundle exec bin/kontena stack install ~/kontena/kontena/docs/examples/wordpress/kontena.yml`
```
bundler: failed to load command: bin/kontena (bin/kontena)
TTY::Prompt::ConfigurationError: Resolver 'service_link' for 'lb_link' : default index `1` out of range (1 - 0)
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/option.rb:206:in `rescue in block in resolve'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/option.rb:201:in `block in resolve'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/option.rb:200:in `each'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/option.rb:200:in `resolve'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/option.rb:177:in `value'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/option.rb:233:in `valid?'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/group.rb:80:in `select'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/opto-1.8.0/lib/opto/group.rb:80:in `run'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/reader.rb:138:in `process_variables'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/reader.rb:114:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:73:in `stack_from_yaml'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/install_command.rb:31:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:191:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:191:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:191:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
  bin/kontena:16:in `<top (required)>'
```

**Comment by jnummelin** [comment]
fixed in #1800
