### ISSUE TITLE
Cannot remove grid XYZ

### ISSUE THREAD

**Issue by vinhmmkh** [kontena/kontena#1766]
Hello -
I want to delete my kontena grid using **"kontena grid remove --force testing"**. In order to do it properly I removed each node in this grid and stopped the kontena-agent service on them.  **"kontena node ls"** shows zero nodes, so I can start to delete my grid.

```sh
foo@bar:~$ kontena node ls
Name                                                                   Status     Initial    Labels                                  
foo@bar:~$ kontena service ls
 [error] Internal Server Error
foo@bar:~$ kontena grid remove --force testing
 [fail] removing testing grid      
 [error] {"grid"=>"Grid has services"}
foo@bar:~$ 
``` 

Is there any config file/ folder of kontena which define the services? Or is there another way to solve it.

Best regards,

vinhmmkh

**Comment by SpComb** [comment]
The `kontena service ls` -> `Internal Server Error` indicates that you still have services, but they are are in some broken state. Can you take a look at the `docker logs kontena-server-api` on the master, and post any errors and associated backtraces here?

**Comment by vinhmmkh** [comment]
Thank you for the reply. 
Here is the error logged in the docker logs of kontena-server-api

```sh
NoMethodError (undefined method `to_path' for nil:NilClass
Did you mean?  to_a):
  /app/app/views/v1/grid_services/_grid_service.json.jbuilder:37:in `block (3 levels) in evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `map'
  /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `method_missing'
  /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/embedded/many.rb:404:in `method_missing'
  /app/app/views/v1/grid_services/_grid_service.json.jbuilder:36:in `block (2 levels) in evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /app/app/views/v1/grid_services/index.json.jbuilder:19:in `block (3 levels) in evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block (2 levels) in _map_collection'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block in _map_collection'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `map'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `_map_collection'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:180:in `array!'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `block in set!'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `set!'
  /app/app/views/v1/grid_services/index.json.jbuilder:14:in `block (2 levels) in evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /usr/lib/ruby/gems/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /usr/lib/ruby/gems/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda/plugins/render.rb:216:in `render'
  /app/app/routes/v1/grids/grid_services.rb:33:in `block (3 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:448:in `is'
  /app/app/routes/v1/grids/grid_services.rb:24:in `block (2 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:376:in `get'
  /app/app/routes/v1/grids/grid_services.rb:23:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `route'
  /app/app/routes/v1/grids_api.rb:37:in `block (2 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1/grids_api.rb:35:in `block in <class:GridsApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /app/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /app/server.rb:52:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/server.rb:51:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /app/app/middlewares/token_authentication.rb:73:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:46:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

80.147.58.111 - - [02/Feb/2017:09:30:36 +0000] "GET /v1/grids/testing/services?stack= HTTP/1.1" 500 35 0.0817
80.147.58.111 - - [02/Feb/2017:09:30:43 +0000] "GET /v1/grids HTTP/1.1" 200 582 0.0638
80.147.58.111 - - [02/Feb/2017:09:30:44 +0000] "DELETE /v1/grids/testing HTTP/1.1" 422 38 0.0619
```

**Comment by SpComb** [comment]
It seems like you've managed to delete a linked service, which shouldn't normally be possible using `kontena service rm`. Did `kontena service ls` still work before you removed all of the nodes?

I assume this is with Kontena version 1.0.6?

**Comment by vinhmmkh** [comment]
Im using kontena version 1.0.5. I remember *kontena service ls* worked until I created another grid. Shutting services down and started them multiple times could ve caused that error. 
... that sucks.

**Comment by SpComb** [comment]
The `kontena service ls` is exploding on the [`grid_service.grid_service_links[...].linked_grid_service`](https://github.com/kontena/kontena/blob/v1.0.5/server/app/views/v1/grid_services/_grid_service.json.jbuilder#L36-L38) being nil. AFAIK that can only happen if the linked grid service is removed, but the `kontena service rm` -> server `DELETE /v1/services/:grid_name/:stack_name/:service_name` -> `GridServices::Delete` should prevent that from happening...

Okay, I managed to repro this. Are you linking to services in other stacks? It looks like removing a linked-to service from a stack and then running `kontena stack upgrade` will remove the linked-to service without this check, and that results in `kontena service ls` HTTP 500 errors.

## Repro
```
$ kontena stack install --deploy links-test.yaml
$ kontena stack install --deploy links-test2.yaml
# edit the links-test.yaml to remove the test1 service
$ kontena stack upgrade --deploy links links-test.yaml
$ kontena service ls
 [error] Internal Server Error
```

### Stack files
#### `links-test.yaml`
```yaml
stack: test/links
services:
    test1:
        image: redis
    test2:
        image: redis
```

#### `links-test2.yaml`
```yaml
stack: test/links2
services:
    test2:
        image: redis
        links:
          - links/test1
```

### Server error
```

NoMethodError (undefined method `to_path' for nil:NilClass
Did you mean?  to_a):
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/_grid_service.json.jbuilder:37:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `method_missing'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/embedded/many.rb:404:in `method_missing'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/_grid_service.json.jbuilder:36:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/index.json.jbuilder:19:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block (2 levels) in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `_map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:180:in `array!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `block in set!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `set!'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/index.json.jbuilder:14:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/render.rb:216:in `render'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:33:in `block (3 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:448:in `is'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:24:in `block (2 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:376:in `get'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:23:in `block in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `route'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids_api.rb:37:in `block (2 levels) in <class:GridsApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids_api.rb:35:in `block in <class:GridsApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/server.rb:54:in `block (2 levels) in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/server.rb:53:in `block in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/app/middlewares/version_injector.rb:12:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/token_authentication.rb:73:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:140:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:46:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

127.0.0.1 - - [02/Feb/2017:12:08:16 +0200] "GET /v1/grids/development/services?stack= HTTP/1.1" 500 35 0.0759
```

**Comment by SpComb** [comment]
So you probably still have some services in that grid, which is preventing you from removing them. You can technically still remove those with `kontena service rm`, but that's hard if you can't use `kontena service ls` to list them...

Workaround would be to use `kontena container ls` to find those broken services that are linking to the removed service, and then remove them using `kontena service rm`. If you manage to remove the affected services that way, then `kontena service ls` should start working again.

**Comment by vinhmmkh** [comment]
Thank you very much! I will spend some time to investigate.

**Comment by vinhmmkh** [comment]
My situation is, that I removed already the nodes. Hence i dont have any container which can be listed. How is that possible, that the grid tells me having running services since the services are provided by the nodes? I dont get it.

**Comment by SpComb** [comment]
Tracking a fix to the underlying #1741 issue in #1769

I'll keep this open in case you still need help cleaning up the aftermath.

**Comment by SpComb** [comment]
Right... I suppose you'd need to dig into the even lower-level server-side mongo stuff to get this fixed :/

**Comment by SpComb** [comment]
You can try this hack on the the master node to list any grid services with broken links:

```sh
docker exec kontena-server-api ruby -r ./app/boot.rb -e 'GridService.all.select{|s| s.grid_service_links.any? { |l| l.linked_grid_service.nil? } }.map{|s| s.to_path}'
```

It should output a list like

```
["development/links2/test2"]
```

**Comment by vinhmmkh** [comment]
I resetted the grid completely and it seems to work now. :) Thank you very much for your support.
