### ISSUE TITLE
Stack upgrade can remove linked-to services, breaking linking services

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1769]
Having a service that links to a service in a different stack, and then using `kontena stack upgrade` to remove that linked-to service, results in a nil [`grid_service.grid_service_links[...].linked_grid_service`. This is normally impossible, as the `kontena service rm` -> server `DELETE /v1/services/:grid_name/:stack_name/:service_name` -> `GridServices::Delete` validation refuses to remove a service that is linked to.

This results in `kontena service ls` HTTP 500 errors:  #1741

The server's `StackDeployWorker#remove_services`  should not remove services that are still linked. The `Stacks::Update` mutation should also validate these.

## Example
```
$ kontena stack install --deploy links-test.yaml
$ kontena stack install --deploy links-test2.yaml
# edit the links-test.yaml to remove the test1 service
$ kontena stack upgrade --deploy links links-test.yaml
$ kontena service ls
 [error] Internal Server Error
```

The server error is on the `links2/test2` service, and running `kontena service rm links2/test2` fixes this situation.

#### `links-test.yaml`
```yaml
stack: test/links
services:
    test1:
        image: redis
    test2:
        image: redis
```

#### `links-test2.yaml`
```yaml
stack: test/links2
services:
    test2:
        image: redis
        links:
          - links/test1
```

### Server error
```

NoMethodError (undefined method `to_path' for nil:NilClass
Did you mean?  to_a):
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/_grid_service.json.jbuilder:37:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/proxy.rb:150:in `method_missing'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/relations/embedded/many.rb:404:in `method_missing'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/_grid_service.json.jbuilder:36:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/index.json.jbuilder:19:in `block (3 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block (2 levels) in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:294:in `block in _map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `map'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:293:in `_map_collection'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:180:in `array!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `block in set!'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:31:in `set!'
  /home/kontena/kontena/kontena/server/app/views/v1/grid_services/index.json.jbuilder:14:in `block (2 levels) in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/render.rb:216:in `render'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:33:in `block (3 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:448:in `is'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:24:in `block (2 levels) in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:376:in `get'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids/grid_services.rb:23:in `block in <top (required)>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/multi_route.rb:208:in `route'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids_api.rb:37:in `block (2 levels) in <class:GridsApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1/grids_api.rb:35:in `block in <class:GridsApi>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /home/kontena/kontena/kontena/server/server.rb:54:in `block (2 levels) in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /home/kontena/kontena/kontena/server/server.rb:53:in `block in <class:Server>'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /home/kontena/kontena/kontena/server/app/middlewares/version_injector.rb:12:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/token_authentication.rb:73:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:140:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:46:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

127.0.0.1 - - [02/Feb/2017:12:08:16 +0200] "GET /v1/grids/development/services?stack= HTTP/1.1" 500 35 0.0759
```

**Comment by SpComb** [comment]
Per #1873 the server will now omit any such broken links from the service JSON `links` array.

**Comment by SpComb** [comment]
The stack/service delete now fails for the linking service:

```
127.0.0.1 - - [21/Mar/2017:17:35:47 +0200] "DELETE /v1/stacks/development/links-victim HTTP/1.1" 200 2 0.1008
E, [2017-03-21T17:35:47.529086 #26675] ERROR -- : Actor crashed!
NoMethodError: undefined method `load_balancer?' for nil:NilClass
	/home/kontena/kontena/kontena/server/app/models/grid_service.rb:155:in `block in linked_to_load_balancer?'
	/home/kontena/kontena/kontena/server/app/models/grid_service.rb:155:in `any?'
	/home/kontena/kontena/kontena/server/app/models/grid_service.rb:155:in `linked_to_load_balancer?'
	/home/kontena/kontena/kontena/server/app/mutations/grid_services/delete.rb:18:in `execute'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
	/home/kontena/kontena/kontena/server/app/jobs/stack_remove_worker.rb:25:in `block in remove_stack'
	/home/kontena/kontena/kontena/server/app/jobs/stack_remove_worker.rb:24:in `each'
	/home/kontena/kontena/kontena/server/app/jobs/stack_remove_worker.rb:24:in `remove_stack'
	/home/kontena/kontena/kontena/server/app/jobs/stack_remove_worker.rb:12:in `perform'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```
