### ISSUE TITLE
Existing Vault variables fail Stack builds

### ISSUE THREAD

**Issue by mattdavenport** [kontena/kontena#1807]
After upgrading to 1.1, I've encountered an error with building/validating some stacks. Here is a simplified version of a stack file which triggers the bug:
```yaml
#
# Web services
#
---
stack: web
version: 0.5.0
description: Web services (nginx+php-fpm)

variables:
  parent_domain:
    type: string
    from:
      vault: PARENT_DOMAIN
      prompt: Parent Domain
    to:
      vault: PARENT_DOMAIN
      env: parent_domain

services:
  nginx:
    image: registry/nginx:latest
    build:
      context: ./nginx
      args:
        PARENT_DOMAIN: ${parent_domain}
    ports:
      - "80:80"
      - "443:443"
```

After running `DEBUG=true kontena stack build -f stack.yml`:
```
D, [2017-02-07T11:52:31.375326 #70639] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>false, :instrumentor=>Kontena::DebugInstrumentor}
[API Client Request]: POST https://<redacted>/v1/grids/primary/secrets (ssl_verify: false)  | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: "{\"name\":\"PARENT_DOMAIN\",\"value\":\"existingvalue.com\"}"
[API Client Error]:
D, [2017-02-07T11:52:31.665812 #70639] DEBUG -- CLIENT: Request POST /v1/grids/primary/secrets: 422 Unprocessable Entity: {"error":{"name":"is already taken"}}
Command raised {"name"=>"is already taken"} with message: {"name"=>"is already taken"}
  /Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:535:in `handle_error_response'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:347:in `rescue in request'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:288:in `request'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:212:in `post'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/vault/write_command.rb:26:in `block in execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/common.rb:80:in `vspinner'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/vault/write_command.rb:25:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena_cli.rb:18:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/yaml/opto/vault_setter.rb:7:in `set'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/opto-1.8.2/lib/opto/option.rb:221:in `block in output'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/opto-1.8.2/lib/opto/option.rb:218:in `each'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/opto-1.8.2/lib/opto/option.rb:218:in `output'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/opto-1.8.2/lib/opto/group.rb:80:in `each'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/opto-1.8.2/lib/opto/group.rb:80:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/yaml/reader.rb:141:in `process_variables'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/yaml/reader.rb:117:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/common.rb:63:in `stack_from_yaml'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/build_command.rb:28:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
/Users/matt/.rvm/gems/ruby-2.3.0/gems/kontena-cli-1.1.0/bin/kontena:16:in `<top (required)>'
/Users/matt/.rvm/gems/ruby-2.3.0/bin/kontena:22:in `load'
/Users/matt/.rvm/gems/ruby-2.3.0/bin/kontena:22:in `<main>'
Value for app_parent_domain is not set. Substituting with an empty string.
Value for app_parent_domain is not set. Substituting with an empty string.
Building image registry/nginx:latest
Sending build context to Docker daemon 14.96 MB
Error response from daemon: Syntax error - can't find = in "ENV". Must be of the form: name=value
```

It appears Kontena is trying to rewrite the secrets to the vault, even though the `from:` clause in the variable declaration should have caught the vault key before executing the rest of the path.

**Comment by mattdavenport** [comment]
Update: Removing the secrets and running the build (all prompts are re-triggered) does the same thing. The secrets get stored properly, but the same error from above happens at actual build time.

**Comment by jnummelin** [comment]
I'm failing to reproduce this. :/ @kke Any ideas why this could happen?

**Comment by kke** [comment]
Well the setter should use upsert and not create, but it shouldn't give  any error.

`Error response from daemon: Syntax error - can't find = in "ENV". Must be of the form: name=value` this hints towards something else in my opinion.

**Comment by mattdavenport** [comment]
Upgrading the 1.1.1 seems to have fixed this issue. Again, not sure why it was occurring... but looks good now. Thanks!
