### ISSUE TITLE
Stateful service deploy failure with API 403 Forbidden

### ISSUE THREAD

**Issue by counterbeing** [kontena/kontena#1824]
Just ran into this, I'm not positive it's a bug just yet. I recently upgraded Kontena to 1.1.0. 

```bash
➜  infrastructure git:(master) kontena version
cli: 1.1.0
master: 1.1.0 (https://107.180.213.142)
```
 I just attempted to deploy a pre-existing stack that used to work. The major difference between this staging stack and my production stack is that it's stateful and has a DB:

```yaml
  db:
    stateful: true
    image: postgres:9.3
    environment:
      POSTGRES_USER: xxxxxxx
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-staging-db:/var/lib/postgresql/data
```

Now, if I try a deploy, or upgrade I'm getting : 

```bash
[API Client Response]: Headers: {Content-Type: application/json}  | Status: 200 | Body: "{\"id\":\"589bd2de6320370006000056\",\"stack_id\":\"prod/staging\",\"created_at..."
    *   Deploying service db .. \[API Client Request]: GET https://107.180.213.142/v1/services/prod/staging/db/deploys/589bd2de6320370006000058 (ssl_verify: true)  | Headers: {Accept: application/json, Authorization: Bearer}
    *   Deploying service db .. /[API Client Error]:
D, [2017-02-08T18:24:32.683744 #43090] DEBUG -- CLIENT: Request GET /v1/services/prod/staging/db/deploys/589bd2de6320370006000058: 403 Forbidden: {"error":"Access denied"}
 [fail] Deploying service db
Access denied Access denied
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:535:in `handle_error_response'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:347:in `rescue in request'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:288:in `request'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:201:in `get'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/stacks_helper.rb:72:in `block in wait_for_service_deploy'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/spinner.rb:140:in `spin'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/common.rb:278:in `spinner'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/stacks_helper.rb:70:in `wait_for_service_deploy'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/stacks_helper.rb:41:in `block in wait_for_deploy_to_finish'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/stacks_helper.rb:35:in `wait_for_deploy_to_finish'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/deploy_command.rb:24:in `execute'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena_cli.rb:18:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/stacks/upgrade_command.rb:32:in `execute'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/bin/kontena:16:in `<top (required)>'
/Users/cory/.rbenv/versions/2.3.1/bin/kontena:23:in `load'
/Users/cory/.rbenv/versions/2.3.1/bin/kontena:23:in `<main>'
Command raised Access denied with message: Access denied
```

The  API is responding with a 403 when I ask about the deploy. And the deploy does indeed seem to fail. The DB clearly never really starts up.  But then, I can't access its logs either:

```
➜  infrastructure git:(master) kontena service logs --debug staging/db
D, [2017-02-08T18:32:27.296857 #51359] DEBUG -- CLIENT: Key looks like a self-signed cert made by Kontena CLI, setting verify_peer_host to 'Test'
D, [2017-02-08T18:32:27.297006 #51359] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>"/Users/cory/.kontena/certs/107.180.213.142.pem", :ssl_verify_peer_host=>"Test"}
[API Client Request]: GET https://107.180.213.142/v1/services/prod/staging/db/container_logs?limit=100 (ssl_verify: true)  | Headers: {Accept: application/json, Authorization: Bearer}
[API Client Error]:
D, [2017-02-08T18:32:27.513790 #51359] DEBUG -- CLIENT: Request GET /v1/services/prod/staging/db/container_logs: 403 Forbidden: {"error":"Access denied"}
/Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:535:in `handle_error_response': Access denied (Kontena::Errors::StandardError)
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:347:in `rescue in request'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:288:in `request'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/client.rb:201:in `get'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/helpers/log_helper.rb:31:in `get_logs'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/helpers/log_helper.rb:23:in `show_logs'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/cli/services/logs_command.rb:20:in `execute'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/lib/kontena/command.rb:191:in `run'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
        from /Users/cory/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.0/bin/kontena:16:in `<top (required)>'
        from /Users/cory/.rbenv/versions/2.3.1/bin/kontena:23:in `load'
        from /Users/cory/.rbenv/versions/2.3.1/bin/kontena:23:in `<main>'
```

**Comment by counterbeing** [comment]
Status update: just removed and re-deployed the stack. 

The environment is now up and running, but the deployment still reported a failure on the db:

```
➜  infrastructure git:(master) ✗ kontena stack install kontena-staging.yml
 [done] Creating stack staging
 [done] Triggering deployment of stack staging
 [done] Waiting for deployment to start
 [fail] Deploying service db
```

**Comment by counterbeing** [comment]
Another update, realizing a number of endpoints on the master are now inaccessible to me. I cannot use the following result in access denied:

```
kontena service show staging/db
kontena container ls
```

**Comment by jnummelin** [comment]
Sounds a bit like these issues: #1686 and #1442

So verify that you have added your account also to the grid:
`kontena grid user add <email>`

**Comment by counterbeing** [comment]
That's not something I've ever done for either of my grids. So far I've just used the default setup. i don't currently share access with anyone.

**Comment by counterbeing** [comment]
That did indeed fix the issue I was seeing @jnummelin . I was't aware of the role issue as it previously worked for me out of the box. I'm comfortable closing this issue in favor of #1686 if you think that's the way to go.
