### ISSUE TITLE
e2e tests do not wait for service operations to complete

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1904]
The `kontena service start` spec may fail:

```
  1) service start starts initialized service
     Failure/Error: expect(k.out.scan('state: running').size).to eq(1)
     
       expected: 1
            got: 0
     
       (compared using ==)
     # ./spec/features/service/start_spec.rb:30:in `block (2 levels) in <top (required)>'
```

This is currently  `kontena service start`, `sleep 1`, `kontena service show`, which may not be enough. I think these need slightly better logic to poll the service status, not just `sleep 1`

The `kontena service start` -> `POST /v1/services/:grid_name/:stack_name/:service_name/start` API -> `GridServices::Start` mutation uses a `Celluloid::Future` to run the `/service_pods/start` RPC asynchronously, and the service state only changes once the agent picks up the Docker event, and notifies the master.

The recently merged #1607 could be used to make this slightly more reliable, as the RPCs are now synchronous on the Docker API requests. We could change the server API to block on the RPC, and thus return better errors etc?

**Comment by matti** [comment]
yep, sleeps are horrible as they make the whole test suite to run slower than what it could run.

something like (pseudocode):

```
# CURRENT:
  it 'starts initialized service' do
    k = kommando("kontena service start test-2")
    expect(k.run).to be_truthy
    sleep 1
    k = run("kontena service show test-2")
    expect(k.out.scan('state: running').size).to eq(1)
  end
  
# NEW:
  it 'BETTER starts initialized service' do
    k = kommando("kontena service start test-2")
    expect(k.run).to be_truthy
  
    got_running = false
    10.times do |t|
      k = run("kontena service show test-2")
      got_running = k.out.scan('state: running').size == 1
      sleep 0.25
    end
    
    expect(got_runnign).to be_truthy
  end
```

**Comment by SpComb** [comment]
Something like the agent's `WaitHelper` would look like

```ruby
it "starts initialized service" do
   expect(run("kontena service start test-2")).to be_truthy

   wait("Service is running", timeout: 5) {
      run("kontena service show test-2").out.matches? 'state: running'
   }
end
```

Which would then fail with a `TimeoutError: Timeout while waiting for: Service is running` if Kontena is b0rken.

**Comment by SpComb** [comment]
Also

```
  1) app remove removes a deployed app
     Failure/Error: expect(k.out).not_to match(/simple-#{service}/)
     
       expected "NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED ...              0 / 1      no       deleting   0.0.0.0:80->80/tcp                                \r\n" not to match /simple-lb/
       Diff:
       @@ -1,2 +1,3 @@
       -/simple-lb/
       +NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
       +⊝ simple-lb                                                  0 / 1      no       deleting   0.0.0.0:80->80/tcp                                
       
     # ./spec/features/app/remove_spec.rb:13:in `block (4 levels) in <top (required)>'
     # ./spec/features/app/remove_spec.rb:12:in `each'
     # ./spec/features/app/remove_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/support/shell.rb:29:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:28:in `chdir'
     # ./spec/support/shell.rb:28:in `with_fixture_dir'
     # ./spec/features/app/remove_spec.rb:5:in `block (2 levels) in <top (required)>'
```
