### ISSUE TITLE
CLI: kontena app commands fail with an obscure error when given a stack file

### ISSUE THREAD

**Issue by industral** [kontena/kontena#1916]
```
$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

```
$ gem -v
2.5.1
```

```
$ DEBUG=true kontena app list
D, [2017-03-01T18:36:51.251250 #18757] DEBUG -- CONFIG: Loading configuration from /home/alex/.kontena_client.json
D, [2017-03-01T18:36:51.252275 #18757] DEBUG -- CONFIG: Configuration loaded with 1 servers.
D, [2017-03-01T18:36:51.252393 #18757] DEBUG -- CONFIG: Current master: some-name
D, [2017-03-01T18:36:51.252558 #18757] DEBUG -- CONFIG: Current grid: my-grid
Running #<Kontena::MainCommand:0x005611610e6550> -- callback matcher = 'nil'
Running #<Kontena::Cli::AppCommand:0x005611610dab60> -- callback matcher = 'nil'
Running #<Kontena::Cli::Apps::ListCommand:0x005611610d7898> -- callback matcher = 'apps list'
/var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:196:in `expand_build_context': undefined method `dig' for "test-ns/is":String (NoMethodError)
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:105:in `process_config'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:92:in `block in parse_services'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:91:in `each'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:91:in `parse_services'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:32:in `block in execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:27:in `chdir'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/yaml/reader.rb:27:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/common.rb:23:in `services_from_yaml'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/cli/apps/list_command.rb:19:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.1.2/bin/kontena:16:in `<top (required)>'
	from /usr/local/bin/kontena:23:in `load'
	from /usr/local/bin/kontena:23:in `<main>'
```

```
$ kontena -v
kontena-cli 1.1.2 [ruby2.3.1+x86_64-linux-gnu]
```

`kontena-server 1.1.2-1`

**Comment by SpComb** [comment]
Can you also show the `kontena.yml` that you are using?

**Comment by SpComb** [comment]
In particular, do you have `version: '2'`? It looks like the YAML reader is missing some validations for the default legacy v1 format that are likely to lead to this kind of error later on in the parsing.

**Comment by industral** [comment]
```
$ cat kontena.yml
stack: test/is
services:
  website:
    image: path/to/image
    ports:
      - "8811:8811"
    network_mode: "host"
```

**Comment by SpComb** [comment]
Yes, that is a `kontena stack ...` file. You can't use it with the legacy `kontena app ...` commands.

We should clearly document that difference better.

**Comment by SpComb** [comment]
BTW, `ports` will not work with `network_mode: host`

> ports: - "8811:8811"
> network_mode: "host"

**Comment by industral** [comment]
@SpComb I just need to **scale**, so find that it could be done with `kontenta app`.
Can I do it somehow with `kontenta stack` then?

About ports, yes you right. It's extra now. With `network_mode: "host"` I've fixed issue with custom hosts.

**Comment by SpComb** [comment]
No, you can't mix and match `kontena app` with `kontena stack`.

You can add an `instances: X` to the stack YAML file service, and then `kontena stack upgrade`.

**Comment by industral** [comment]
OK, got it. I guess will be better to use something like `kontenta stack scale ...`
Anyway, @SpComb thanks for help!

**Comment by SpComb** [comment]
Let's keep this open, we need a better error message if you try and use the `kontena app ...` commands with a stack file.

Edited the title.
