### ISSUE TITLE
Can't fetch docker private repository Docker::Error::NotFoundError: repository not found: does not exist or no pull access

### ISSUE THREAD

**Issue by industral** [kontena/kontena#1918]
While scaling nodes `kontena stack upgrade NAME`, I found that node can't fetch docker image from private repository.

failing with

```
ERROR -- : Actor crashed!
Docker::Error::NotFoundError: repository YOUR_NAME/IMAGE not found: does not exist or no pull access
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:114:in `create'
/app/lib/kontena/workers/image_pull_worker.rb:34:in `pull_image'
/app/lib/kontena/workers/image_pull_worker.rb:18:in `ensure_image'
```

`level=error msg="Handler for GET /v1.22/images/YOUR_NAME/IMAGE:latest/json returned error: No such image: YOUR_NAME/IMAGE:latest"
`

But `docker login` is fine

```
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (YOUR_NAME):
Password:
Login Succeeded
```

```
$ docker pull YOUR_NAME/IMAGE:latest
latest: Pulling from YOUR_NAME/IMAGE
8aec416115fd: Downloading [=>                                                 ] 1.523 MB/50.31 MB
695f074e24e3: Download complete
946d6c48c2a7: Download complete
bc7277e579f0: Download complete
2508cbcde94b: Download complete
a994dc1e0598: Waiting
9b572aa8eaab: Waiting
```

Should docker credentials be stored somewhere else for Kontenta?

**Comment by industral** [comment]
More logs...

```
INFO -- Kontena::ServicePods::Creator: creating service: is.website-2
INFO -- Kontena::Workers::ImagePullWorker: pulling image: NAME/IMAGE:latest
level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
level=info msg="Translating \"denied: requested access to the resource is denied\" to \"repository NAME/IMAGE not found: does not exist or no pull access\""
level=error msg="Handler for POST /v1.22/images/create returned error: repository NAME/IMAGE not found: does not exist or no pull access"
WARN -- Kontena::Workers::ImagePullWorker: image pull failed: repository NAME/IMAGE not found: does not exist or no pull access
```

**Comment by jakolehm** [comment]
See http://www.kontena.io/docs/using-kontena/private-registries.html

**Comment by industral** [comment]
Ahh... Guess that should be also added to https://www.kontena.io/docs/references/kontena-yml.html

@jakolehm  Thank you!
