### ISSUE TITLE
Cannot start service in virtual environment

### ISSUE THREAD

**Issue by giovannicandido** [kontena/kontena#1969]
Steps to reproduce:

Environment: Vmware Workstation
Setup: 1 master 2 nodes
Installation method:
Created a Ubuntu Server 16.04.2 LTS minimal installation
Clone the server to create master
Clone the server to create the nodes
Follow installation instructions via apt-get
create a default grid

`kontena node list: ok`

`kontena service create -p 8080:80 nginx nginx`
`kontena service start nginx`

Service do not deploy

Logs:

```
> 2017-03-14T00:42:31.000Z kontena-agent: E, [2017-03-14T00:42:31.310183 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
> 2017-03-14T00:42:58.000Z kontena-agent: E, [2017-03-14T00:42:58.513088 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
> 2017-03-14T00:45:30.000Z weave: INFO: 2017/03/14 00:45:30.316532 Expired MAC 36:13:aa:e0:2b:6b at 36:13:aa:e0:2b:6b(knode2)
> 2017-03-14T00:45:31.000Z kontena-agent: E, [2017-03-14T00:45:31.312629 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
> 2017-03-14T00:45:57.000Z weave: INFO: 2017/03/14 00:45:57.237450 Expired MAC 96:68:c9:40:07:ac at 96:68:c9:40:07:ac(knode1)
> 2017-03-14T00:45:58.000Z kontena-agent: E, [2017-03-14T00:45:58.513911 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
> 2017-03-14T00:47:29.000Z kontena-agent: I, [2017-03-14T00:47:29.965673 #1]  INFO -- Kontena::ServicePods::Creator: creating service: nginx-1
> 2017-03-14T00:47:29.000Z kontena-agent: I, [2017-03-14T00:47:29.966598 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: nginx:latest
> 2017-03-14T00:47:49.000Z kontena-agent: I, [2017-03-14T00:47:49.489335 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: nginx:latest
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin: Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:2379 (Connection refused - connect(2) for "127.0.0.1" port 2379)
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:111:in `api_execute'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /app/app/etcd_client.rb:27:in `version'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /app/app/etcd_client.rb:22:in `initialize'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /app/config.ru:11:in `new'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /app/config.ru:11:in `block in <main>'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /app/config.ru:1:in `new'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /app/config.ru:1:in `<main>'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `eval'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `load'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:42:in `for'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:170:in `load_adapter'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:74:in `start'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/bin/thin:23:in `load'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin:   /usr/bin/thin:23:in `<top (required)>'
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin: Using rack adapter
> 2017-03-14T00:48:18.000Z kontena-ipam-plugin: bundler: failed to load command: thin (/usr/bin/thin)
> 2017-03-14T00:48:31.000Z kontena-agent: E, [2017-03-14T00:48:31.315545 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Excon::Error::Socket: Connection refused - connect(2) for 127.0.0.1:2275 (Errno::ECONNREFUSED)
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin: Using rack adapter
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin: bundler: failed to load command: thin (/usr/bin/thin)
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin: Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:2379 (Connection refused - connect(2) for "127.0.0.1" port 2379)
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:111:in `api_execute'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /app/app/etcd_client.rb:27:in `version'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /app/app/etcd_client.rb:22:in `initialize'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /app/config.ru:11:in `new'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /app/config.ru:11:in `block in <main>'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /app/config.ru:1:in `new'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /app/config.ru:1:in `<main>'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `eval'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `load'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:42:in `for'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:170:in `load_adapter'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:74:in `start'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/bin/thin:23:in `load'
> 2017-03-14T00:48:46.000Z kontena-ipam-plugin:   /usr/bin/thin:23:in `<top (required)>'
```

**Comment by jnummelin** [comment]
Creating nodes by cloning servers usually ends up badly as there are some components with some state stored in the server. In this case it seems that the Etcd is trying to start with bad configuration. Also on problem cloning also creates is that the Docker ID (which Kontena also uses to identify nodes) get copied and things fail in un-expected ways.

So I'd try to re-create the nodes without cloning.

**Comment by SpComb** [comment]
My guess would be that weave is confused by the cloned nodes, but I'm not sure exactly where to start diagnosing those kind of issues:

* https://github.com/weaveworks/weave/issues/2427

**Comment by giovannicandido** [comment]
@jnummelin Thank you for the tip. But my clone was made in a much minimal state, no docker, nothing installed only vim. On the nodes I have installed docker and kontena-agent. I check the network hardware mac, and is different. How do I check docker id? I guess they are different too.

I try to use kontena vagrant and virtualbox, as oficial plugin,  I get the log:

> 2017-03-14T22:13:54.000Z kontena-etcd: 2017-03-14 22:13:54.078724 W | etcdmain: proxy: could not retrieve cluster information from the given urls
2017-03-14T22:13:55.000Z kontena-etcd: 2017-03-14 22:13:55.080882 W | etcdserver: could not get cluster response from http://10.81.0.1:2380: Get http://10.81.0.1:2380/members: dial tcp 10.81.0.1:2380: getsockopt: connection refused

But after waiting a little bit, service is working.
I would like to use vmware because of performance, and will try installing the OS from the ground but, if not working I going to use vagrant and virtualbox for the evaluation.

**Comment by jnummelin** [comment]
Ok, I got the wrong impression about the clones from the original post. :) 

You can see the docker id from `docker info`

The errors indicate that etcd and/or weave on the nodes do not properly get up. What type of networking you have between the nodes?

**Comment by giovannicandido** [comment]
The nodes and master are in the same subnet.
There is no weave network in master, is that correct?

Here is the config

master


```
ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:da:5f:4b brd ff:ff:ff:ff:ff:ff
    inet 192.168.183.130/24 brd 192.168.183.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:feda:5f4b/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:02:28:7d:e7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2ff:fe28:7de7/64 scope link 
       valid_lft forever preferred_lft forever
5: veth8b1938e@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 3e:4b:db:c6:81:24 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::3c4b:dbff:fec6:8124/64 scope link 
       valid_lft forever preferred_lft forever
7: vetha5d24d8@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 26:0f:62:b8:36:c6 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::240f:62ff:feb8:36c6/64 scope link 
       valid_lft forever preferred_lft forever
9: veth1aab8cb@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether be:7f:6b:b9:75:29 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::bc7f:6bff:feb9:7529/64 scope link 
       valid_lft forever preferred_lft forever


```

node1
``` 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:cd:fd:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.183.132/24 brd 192.168.183.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fecd:fdee/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:aa:18:01:1d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UNKNOWN group default qlen 1
    link/ether 6e:6f:2d:fa:c5:84 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::6c6f:2dff:fefa:c584/64 scope link 
       valid_lft forever preferred_lft forever
6: weave: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default qlen 1000
    link/ether 96:68:c9:40:07:ac brd ff:ff:ff:ff:ff:ff
    inet 10.81.0.2/16 scope global weave
       valid_lft forever preferred_lft forever
    inet6 fe80::9468:c9ff:fe40:7ac/64 scope link 
       valid_lft forever preferred_lft forever
7: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 66:99:2a:27:45:91 brd ff:ff:ff:ff:ff:ff
9: vethwe-datapath@vethwe-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master datapath state UP group default qlen 1000
    link/ether 6e:0a:19:e5:85:9e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::6c0a:19ff:fee5:859e/64 scope link 
       valid_lft forever preferred_lft forever
10: vethwe-bridge@vethwe-datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master weave state UP group default qlen 1000
    link/ether d2:15:6f:29:60:21 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::d015:6fff:fe29:6021/64 scope link 
       valid_lft forever preferred_lft forever
11: vxlan-6784: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65485 qdisc noqueue master datapath state UNKNOWN group default qlen 1000
    link/ether 7a:b9:9f:a3:19:ee brd ff:ff:ff:ff:ff:ff
    inet6 fe80::78b9:9fff:fea3:19ee/64 scope link 
       valid_lft forever preferred_lft forever
```
node2

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:ac:bb:65 brd ff:ff:ff:ff:ff:ff
    inet 192.168.183.131/24 brd 192.168.183.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:feac:bb65/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:8f:74:4b:bf brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:8fff:fe74:4bbf/64 scope link 
       valid_lft forever preferred_lft forever
4: datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UNKNOWN group default qlen 1
    link/ether b6:a2:af:4f:80:d8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::b4a2:afff:fe4f:80d8/64 scope link 
       valid_lft forever preferred_lft forever
6: weave: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default qlen 1000
    link/ether 36:13:aa:e0:2b:6b brd ff:ff:ff:ff:ff:ff
    inet 10.81.0.1/16 scope global weave
       valid_lft forever preferred_lft forever
    inet6 fe80::3413:aaff:fee0:2b6b/64 scope link 
       valid_lft forever preferred_lft forever
7: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether f6:3a:57:5c:32:92 brd ff:ff:ff:ff:ff:ff
9: vethwe-datapath@vethwe-bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master datapath state UP group default qlen 1000
    link/ether d2:11:7d:7a:84:76 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::d011:7dff:fe7a:8476/64 scope link 
       valid_lft forever preferred_lft forever
10: vethwe-bridge@vethwe-datapath: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master weave state UP group default qlen 1000
    link/ether ce:00:20:d9:f4:aa brd ff:ff:ff:ff:ff:ff
    inet6 fe80::cc00:20ff:fed9:f4aa/64 scope link 
       valid_lft forever preferred_lft forever
11: vxlan-6784: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65485 qdisc noqueue master datapath state UNKNOWN group default qlen 1000
    link/ether 22:f1:ac:44:cd:c1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::20f1:acff:fe44:cdc1/64 scope link 
       valid_lft forever preferred_lft forever
13: vethe5a1129@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 3e:f4:20:0e:cf:44 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::3cf4:20ff:fe0e:cf44/64 scope link 
       valid_lft forever preferred_lft forever
15: vethwepl2460@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master weave state UP group default 
    link/ether 16:b2:ca:e6:fe:35 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::14b2:caff:fee6:fe35/64 scope link 
       valid_lft forever preferred_lft forever

```

**Comment by jakolehm** [comment]
@giovannicandido did you specify `ens33` as peer interface when you installed `kontena-agent` package?

**Comment by giovannicandido** [comment]
@jakolehm No. How and why?

**Comment by jakolehm** [comment]
@giovannicandido communication between nodes happens via peer network interface. Default for Ubuntu Xenial is eth1 (fallback is eth0). You can change peer interface setting via `/etc/kontena-agent.ev`. After this change you need to restart agents (or reboot nodes).

**Comment by giovannicandido** [comment]
@jakolehm Nice!

Cluster working good after changing the peer interface in master + all nodes

I will edit the documentation to add a note about it. A troubleshooting section in the installation folder sounds good?

**Comment by giovannicandido** [comment]
@jnummelin @SpComb  and @jakolehm  Thanks all for the help
