### ISSUE TITLE
No such image: weaveworks/weaveexec:1.8.2

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/kontena#1979]
I've had this error a few times during a deployment:

node1:
```
I, [2017-03-15T10:02:22.507868 #1]  INFO -- Kontena::NetworkAdapters::Weave: Attach container=e5a9ddc0e26ec87159d6ec95ba3fb55874fcbd1f9a2e9475a43aaf7df5c5f729 at cidr=10.81.128.23/16
E, [2017-03-15T10:02:22.515015 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: No such image: weaveworks/weaveexec:1.8.2

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:323:in `create'
	/app/lib/kontena/network_adapters/weave_executor.rb:22:in `execute'
	/app/lib/kontena/network_adapters/weave_executor.rb:115:in `attach'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2017-03-15T10:02:22.524812 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
```

node2:
```
I, [2017-03-15T10:02:25.713122 #1]  INFO -- Kontena::NetworkAdapters::Weave: Attach container=136ab994df38ba3cc1cc05925bc046280dad5b4c7039e74f69bdf2517550a834 at cidr=10.81.128.91/16
E, [2017-03-15T10:02:25.718683 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: No such image: weaveworks/weaveexec:1.8.2

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:323:in `create'
	/app/lib/kontena/network_adapters/weave_executor.rb:22:in `execute'
	/app/lib/kontena/network_adapters/weave_executor.rb:115:in `attach'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2017-03-15T10:02:25.722972 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
```

The error from kontena-cli after kontena stack deploy:
```
[API Client Response]: Headers: {Content-Type: application/json}  | Status: 200 | Body: "{\"id\":\"58c91716c08aaa00090083e8\",\"stack_id\":\"staging/staging-app\",\"cre..."
* Waiting for deployment to start.. fail
deploy timed out deploy timed out
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/stacks_helper.rb:26:in `rescue in wait_for_deployment_to_start'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/stacks_helper.rb:6:in `wait_for_deployment_to_start'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/deploy_command.rb:22:in `block in execute'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/spinner.rb:59:in `spin_no_tty'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/spinner.rb:82:in `spin'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/common.rb:280:in `spinner'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/deploy_command.rb:21:in `execute'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
/var/lib/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
/var/lib/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
/var/lib/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/bin/kontena:16:in `<top (required)>'
/usr/local/bin/kontena:23:in `load'
/usr/local/bin/kontena:23:in `<main>'
/var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/stacks_helper.rb:26:in `rescue in wait_for_deployment_to_start': deploy timed out (RuntimeError)
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/stacks_helper.rb:6:in `wait_for_deployment_to_start'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/deploy_command.rb:22:in `block in execute'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/spinner.rb:59:in `spin_no_tty'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/spinner.rb:82:in `spin'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/common.rb:280:in `spinner'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/cli/stacks/deploy_command.rb:21:in `execute'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
	from /var/lib/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
	from /var/lib/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/lib/kontena/command.rb:191:in `run'
	from /var/lib/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.1.0/gems/kontena-cli-1.1.2/bin/kontena:16:in `<top (required)>'
	from /usr/local/bin/kontena:23:in `load'
	from /usr/local/bin/kontena:23:in `<main>'
```

Kontena versions:
cli: 1.1.2
master: 1.1.2 
Docker version 1.12.5, build 047e51b/1.12.5
Linux 3.10.0-514.6.1.el7.x86_64
Storage driver: devicemapper

Sometimes deployment works, sometimes it doesn't.

The image is in docker in both nodes:
```
docker images |grep weaveexec
docker.io/weaveworks/weaveexec                        1.8.2               e630a5ba36c9        3 months ago        80.7 MB
```

**Comment by jnummelin** [comment]
Could you check docker logs on that same time, sounds really weird that the image is listed in `docker images` but agent is not able to use it :/

**Comment by panuhorsmalahti** [comment]
cat /var/log/messages | grep docker | grep " 12:02":
```
Mar 12 12:02:06 app-stg01 dockerd-current: time="2017-03-12T12:02:06.84849377+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:3848ebef9c7e35685bb5a9cb99df8149e42e581b2594f31e9162fd9d59f8ff18 starttime: open /proc/15607/stat: no such file or directory"
Mar 12 12:02:06 app-stg01 dockerd-current: time="2017-03-12T12:02:06.849554602+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:3848ebef9c7e35685bb5a9cb99df8149e42e581b2594f31e9162fd9d59f8ff18 (pid 15607) has become an orphan, killing it"
Mar 12 12:02:11 app-stg01 dockerd-current: time="2017-03-12T12:02:11.946346733+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:b71ba9acb41de748fd82c414abfbf82cacc1166faf81a31293142bb670b04f4a starttime: open /proc/15667/stat: no such file or directory"
Mar 12 12:02:11 app-stg01 dockerd-current: time="2017-03-12T12:02:11.946533576+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:b71ba9acb41de748fd82c414abfbf82cacc1166faf81a31293142bb670b04f4a (pid 15667) has become an orphan, killing it"
Mar 12 12:02:17 app-stg01 dockerd-current: time="2017-03-12T12:02:17.0405555+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:93bbd813d381003edb7f99400b42d9491136225021cabd24cbd7bc3bac177756 starttime: open /proc/15906/stat: no such file or directory"
Mar 12 12:02:17 app-stg01 dockerd-current: time="2017-03-12T12:02:17.04138265+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:93bbd813d381003edb7f99400b42d9491136225021cabd24cbd7bc3bac177756 (pid 15906) has become an orphan, killing it"
Mar 13 12:02:36 app-stg01 dockerd-current: time="2017-03-13T12:02:36.291533431+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:0ae80af536ef0e29b55ae70658226b43c34a3512a21b585818a9e4fc645c3911 starttime: open /proc/2137/stat: no such file or directory"
Mar 13 12:02:36 app-stg01 dockerd-current: time="2017-03-13T12:02:36.292595856+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:0ae80af536ef0e29b55ae70658226b43c34a3512a21b585818a9e4fc645c3911 (pid 2137) has become an orphan, killing it"
Mar 13 12:02:56 app-stg01 dockerd-current: time="2017-03-13T12:02:56.704530533+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:cdbd3e8b77942023ca166325a2410d710cdba11f8bd55932fa261846144db311 starttime: open /proc/2549/stat: no such file or directory"
Mar 13 12:02:56 app-stg01 dockerd-current: time="2017-03-13T12:02:56.704711322+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:cdbd3e8b77942023ca166325a2410d710cdba11f8bd55932fa261846144db311 (pid 2549) has become an orphan, killing it"
Mar 14 12:02:16 app-stg01 dockerd-current: time="2017-03-14T12:02:16.067079101+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:ba4b477b38013e42f55561ffc362f96f83122766b55bdf34a87fbbe00b96af0e starttime: open /proc/3570/stat: no such file or directory"
Mar 14 12:02:16 app-stg01 dockerd-current: time="2017-03-14T12:02:16.068380051+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:ba4b477b38013e42f55561ffc362f96f83122766b55bdf34a87fbbe00b96af0e (pid 3570) has become an orphan, killing it"
Mar 14 12:02:20 app-stg01 dockerd-current: time="2017-03-14T12:02:20.473286137+02:00" level=info msg="{Action=remove, LoginUID=4294967295, PID=29340}"
Mar 14 12:02:20 app-stg01 dockerd-current: time="2017-03-14T12:02:20.795220794+02:00" level=info msg="{Action=remove, LoginUID=4294967295, PID=29340}"
Mar 15 12:02:02 app-stg01 dockerd-current: time="2017-03-15T12:02:02.355419302+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:2e7c42a6d70c801c615fa9feb576f319b5449d806ccc88530543a2ef58628a20 starttime: open /proc/6372/stat: no such file or directory"
Mar 15 12:02:02 app-stg01 dockerd-current: time="2017-03-15T12:02:02.355588985+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:2e7c42a6d70c801c615fa9feb576f319b5449d806ccc88530543a2ef58628a20 (pid 6372) has become an orphan, killing it"
Mar 15 12:02:12 app-stg01 dockerd-current: time="2017-03-15T12:02:12.544830326+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:c38f146c6674276b3b040f5dfe1f1d640605af84efcc8c56b7f46bf23cf8a476 starttime: open /proc/6565/stat: no such file or directory"
Mar 15 12:02:12 app-stg01 dockerd-current: time="2017-03-15T12:02:12.545884288+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:c38f146c6674276b3b040f5dfe1f1d640605af84efcc8c56b7f46bf23cf8a476 (pid 6565) has become an orphan, killing it"
Mar 15 12:02:17 app-stg01 dockerd-current: time="2017-03-15T12:02:17.613572594+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:10e0b2cd364e5a7144e5c6c303777d149d891b24d87e6d37b37cb4c283ebc274 starttime: open /proc/6632/stat: no such file or directory"
Mar 15 12:02:17 app-stg01 dockerd-current: time="2017-03-15T12:02:17.613753609+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:10e0b2cd364e5a7144e5c6c303777d149d891b24d87e6d37b37cb4c283ebc274 (pid 6632) has become an orphan, killing it"
Mar 15 12:02:22 app-stg01 systemd: Started docker container e5a9ddc0e26ec87159d6ec95ba3fb55874fcbd1f9a2e9475a43aaf7df5c5f729.
Mar 15 12:02:22 app-stg01 systemd: Starting docker container e5a9ddc0e26ec87159d6ec95ba3fb55874fcbd1f9a2e9475a43aaf7df5c5f729.
Mar 15 12:02:22 app-stg01 kernel: docker0: port 10(veth8af9ffd) entered disabled state
Mar 15 12:02:22 app-stg01 kernel: docker0: port 10(veth8af9ffd) entered forwarding state
Mar 15 12:02:22 app-stg01 kernel: docker0: port 10(veth8af9ffd) entered forwarding state
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.493121370+02:00" level=info msg="{Action=logs, LoginUID=4294967295, PID=3189}"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.510147898+02:00" level=info msg="{Action=create, LoginUID=4294967295, PID=3189}"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.512796946+02:00" level=error msg="Handler for POST /v1.22/containers/create returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.512819026+02:00" level=error msg="Handler for POST /v1.22/containers/create returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.526400564+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.526422253+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.534161400+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.534185514+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.537507102+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.537531121+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.539781177+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.539800134+02:00" level=error msg="Handler for GET /v1.22/images/weaveworks/weaveexec:1.8.2/json returned error: No such image: weaveworks/weaveexec:1.8.2"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.542116299+02:00" level=info msg="{Action=create, LoginUID=4294967295, PID=3189}"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.714165869+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:fbebf92b7ce7135b831cae1560b05034852165ce56859d4eeab8bdb069e72f2d starttime: open /proc/6745/stat: no such file or directory"
Mar 15 12:02:22 app-stg01 dockerd-current: time="2017-03-15T12:02:22.714331414+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:fbebf92b7ce7135b831cae1560b05034852165ce56859d4eeab8bdb069e72f2d (pid 6745) has become an orphan, killing it"
Mar 15 12:02:23 app-stg01 dockerd-current: time="2017-03-15T12:02:23.886577265+02:00" level=error msg="Not continuing with pull after error: unknown: Not Found"
Mar 15 12:02:24 app-stg01 dockerd-current: time="2017-03-15T12:02:24.769961377+02:00" level=info msg="{Action=logs, Username=e907154, LoginUID=888200236, PID=6755}"
Mar 15 12:02:32 app-stg01 dockerd-current: time="2017-03-15T12:02:32.901272294+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:b9639ee71af8ea1265734bad86be0253e73f404e93ed055e7150ca9361f1c54d starttime: open /proc/7074/stat: no such file or directory"
Mar 15 12:02:32 app-stg01 dockerd-current: time="2017-03-15T12:02:32.901745755+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:b9639ee71af8ea1265734bad86be0253e73f404e93ed055e7150ca9361f1c54d (pid 7074) has become an orphan, killing it"
Mar 15 12:02:37 app-stg01 kernel: docker0: port 10(veth8af9ffd) entered forwarding state
Mar 15 12:02:38 app-stg01 dockerd-current: time="2017-03-15T12:02:38.000425298+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:17751af3a426ce022b8ab07f33763c0f122b4868ef290f1f56607ac7c8126147 starttime: open /proc/7139/stat: no such file or directory"
Mar 15 12:02:38 app-stg01 dockerd-current: time="2017-03-15T12:02:38.000610061+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:17751af3a426ce022b8ab07f33763c0f122b4868ef290f1f56607ac7c8126147 (pid 7139) has become an orphan, killing it"
Mar 15 12:02:48 app-stg01 dockerd-current: time="2017-03-15T12:02:48.203914156+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:8cfad339c619ba5c675f3d7760807e2d935e3df81ba8724d3b43bcbb6194d450 starttime: open /proc/7291/stat: no such file or directory"
Mar 15 12:02:48 app-stg01 dockerd-current: time="2017-03-15T12:02:48.204733444+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:8cfad339c619ba5c675f3d7760807e2d935e3df81ba8724d3b43bcbb6194d450 (pid 7291) has become an orphan, killing it"
Mar 15 12:02:53 app-stg01 dockerd-current: time="2017-03-15T12:02:53.286445464+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:3c0e29095edfce20aeb7a9d1bd22e56cbedd6dd89595aa72876055c025d82740 starttime: open /proc/7352/stat: no such file or directory"
Mar 15 12:02:53 app-stg01 dockerd-current: time="2017-03-15T12:02:53.28666722+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:3c0e29095edfce20aeb7a9d1bd22e56cbedd6dd89595aa72876055c025d82740 (pid 7352) has become an orphan, killing it"
Mar 15 12:02:58 app-stg01 dockerd-current: time="2017-03-15T12:02:58.368054755+02:00" level=warning msg="containerd: unable to save fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:cb8c01acef7aee6b8ceed79526cfd4390993e781969ec024b514e4dadfe19d70 starttime: open /proc/7414/stat: no such file or directory"
Mar 15 12:02:58 app-stg01 dockerd-current: time="2017-03-15T12:02:58.368230413+02:00" level=info msg="containerd: fa6f0085376fb15bf8cb7296ba6f2671623e70b71b1f7d275413518a5e54c43e:cb8c01acef7aee6b8ceed79526cfd4390993e781969ec024b514e4dadfe19d70 (pid 7414) has become an orphan, killing it"
```

**Comment by jnummelin** [comment]
Only thing that might seem distantly relevant is this:
```
Mar 15 12:02:23 node1 dockerd-current: time="2017-03-15T12:02:23.886577265+02:00" level=error msg="Not continuing with pull after error: unknown: Not Found"
```

The linked docker issue seem more relevant in properly named containers. When the `weaveexec` containers are spinned during deployment they are not given any names thus docker should create random names.

**Comment by SpComb** [comment]
What OS/Docker version is this?

> `Docker::Error::NotFoundError: No such image: weaveworks/weaveexec:1.8.2`

> ```
> $ docker images |grep weaveexec
> docker.io/weaveworks/weaveexec                        1.8.2               e630a5ba36c9        3 months ago        80.7 MB
> ```

What is the `docker.io` prefix in the `docker images` listing? This looks like some kind of RHEL/CentOS customization to pull either `registry.access.redhat.com/...` or `docker.io/...` images. Is the `docker.io/weaveworks/weaveexec` image name somehow misbehaving when used via the `Docker::Container.create({'Image' => 'weaveworks/weaveexec:1.8.2'})` API?

**Comment by panuhorsmalahti** [comment]
@SpComb 

Docker version 1.12.5, build 047e51b/1.12.5
Linux 3.10.0-514.6.1.el7.x86_64

It's the RHEL/CentOS customized version of docker.

**Comment by SpComb** [comment]
The RHEL/CentOS build of Docker seems to carry a [patch](https://github.com/projectatomic/docker/commit/a611d8221a179b01da4afabe98919b8fc61eb63e) for including the `docker.io` index name in the images... unclear to me how that is expected to behave. Are you supposed to use the fully qualified `docker.io/weaveworks/weaveexec` image name, or does the daemon/API resolve the `weaveworks/weaveexec` image name?

Does the agent `WeaveExecutor` always fail like that, or only sometimes? If this still happens, can you try running the agent with `-e WEAVE_IMAGE=docker.io/weaveworks/weave` `-e WEAVEEXEC_IMAGE=docker.io/weaveworks/weaveexec` and see if that fixes it?

**Comment by panuhorsmalahti** [comment]
I don't know what you're supposed to do, but pulling `weaveworks/weaveexec` works at least from the cli:

```
docker pull weaveworks/weaveexec
Using default tag: latest
Trying to pull repository registry.access.redhat.com/weaveworks/weaveexec ... 
Trying to pull repository docker.io/weaveworks/weaveexec ... 
latest: Pulling from docker.io/weaveworks/weaveexec
709515475419: Already exists 
...
```

I have not seen this error in the past two weeks.

**Comment by jnummelin** [comment]
I guess this has not been happening recently. I'll close, let's re-open if the issue sirfaces again.
