### ISSUE TITLE
Server exceptions with nil backtrace

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1997]
The server may occasionally raise an exception while logging an exception with `exc.backtrace.join("\n")`, where the `exc.backtrace` appears to be nil:

```
E, [2017-03-16T12:51:29.783964 #7] ERROR -- GridServiceInstanceDeployer: failed to deploy service instance ... to node ...
E, [2017-03-16T12:51:29.784596 #7] ERROR -- GridServiceInstanceDeployer: Connection timeout (5s)
E, [2017-03-16T12:51:29.814434 #7] ERROR -- GridServiceDeployer: Unknown error (...): NoMethodError undefined method `join' for nil:NilClass
Did you mean?  JSON
E, [2017-03-16T12:51:29.815038 #7] ERROR -- GridServiceDeployer: /app/app/services/grid_service_instance_deployer.rb:27:in `rescue in deploy'
/app/app/services/grid_service_instance_deployer.rb:17:in `deploy'
/app/app/services/grid_service_deployer.rb:112:in `block in deploy_service_instance'
```

The exception looks like an `RpcClient::TimeoutError`, raised by the [`RpcClient`](https://github.com/kontena/kontena/blob/v1.1.5.rc2/server/app/services/rpc_client.rb#L80):

```ruby
raise RpcClient::TimeoutError.new(503, "Connection timeout (#{self.timeout}s)")
```

Does raising an exception with `raise Exception.new("foo")`, as opposed to `raise Exception, "foo"`, result in a `nil` `backtrace`?

**Comment by kke** [comment]
Yes I think so. I think you can/should pass the backtrace to Exception.new.

**Comment by kke** [comment]
```ruby
  5 class RpcServer
 15   class Error < StandardError
 16     attr_accessor :code, :message, :backtrace
 17
 18     def initialize(code, message, backtrace = nil)
 19       self.code = code
 20       self.message = message
 21       self.backtrace = backtrace
 22     end
 23   end
```

Maybe that should be `backtrace = []` or `self.backtrace = Array(backtrace)`

**Comment by SpComb** [comment]
Why does the custom `Error` class define an `attr_accessor`for `message` or `backtrace`... sounds like a bug.

**Comment by SpComb** [comment]
The server has now already grown some bad workarounds for this:

```
./app/middlewares/websocket_backend.rb:    logger.error exc.backtrace.join("\n") if exc.backtrace
./app/mutations/grid_certificates/get_certificate.rb:      error exc.backtrace.join("\n") if exc.backtrace
./app/services/agent/node_plugger.rb:        error exc.backtrace.join("\n")
./app/services/cloud/rpc_server.rb:          error exc.backtrace.join("\n")
./app/services/rpc/node_volume_handler.rb:      error exc.backtrace.join("\n") if exc.backtrace
./app/services/grid_scheduler.rb:    debug exc.backtrace.join("\n") if exc.backtrace
./app/services/grid_service_deployer.rb:    error exc.backtrace.join("\n") if exc.backtrace
./app/services/grid_service_deployer.rb:    error exc.backtrace.join("\n") if exc.backtrace
./app/services/grid_service_instance_deployer.rb:    error exc.backtrace.join("\n") if exc.backtrace
./app/services/rpc_server.rb:        debug exc.backtrace.join("\n")
./app/services/rpc_server.rb:        error exc.backtrace.join("\n")
```
