### ISSUE TITLE
Observable race condition

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2037]
Sometimes observable/observer actors are crashing.

Backtrace:
```
kontena-agent | RuntimeError: can't add a new key into hash during iteration
kontena-agent | 	/app/lib/kontena/observable.rb:53:in `add_observer'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
kontena-agent | 	(celluloid):0:in `remote procedure call'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
kontena-agent | 	/app/lib/kontena/observer.rb:85:in `block in observe'
kontena-agent | 	/app/lib/kontena/observer.rb:83:in `each'
kontena-agent | 	/app/lib/kontena/observer.rb:83:in `observe'
kontena-agent | 	/app/lib/kontena/workers/service_pod_manager.rb:25:in `start'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | 	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
While I'm here, there's also a flaky spec:

```
  1) Kontena::Observable For chained observables propagates the observed value    

Failure/Error: expect(observer).to be_ready      

expected `#<Celluloid::Proxy::Cell(#<Class:0x007fe951347fa0>:0x3ff4a899b434) @state=#<Kontena::Observer::Observe:0x007fe951324208 @observables=[#<Celluloid::Proxy::Cell(#<Class:0x007fe951054be0>:0x3ff4a887ef88) @state=#<Kontena::Observer::Observe:0x007fe9528929a0 @observables=[#<Celluloid::Proxy::Cell(#<Class:0x007fe9512ccfa8>:0x3ff4a88baf74) @observers={#<Kontena::Observer::Observe:0x007fe9528929a0 @observables=[...], @block=#<Proc:0x007fe9528929c8@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:62>, @values={...=>"test"}>=>...} @observable_value="test">], @block=#<Proc:0x007fe9528929c8@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:62>, @values={#<Celluloid::Proxy::Cell(#<Class:0x007fe9512ccfa8>:0x3ff4a88baf74) @observers={#<Kontena::Observer::Observe:0x007fe9528929a0 @observables=[...], @block=#<Proc:0x007fe9528929c8@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:62>, @values={...=>"test"}>=>...} @observable_value="test">=>"test"}> @observers={#<Kontena::Observer::Observe:0x007fe951324208 @observables=[...], @block=#<Proc:0x007fe951324230@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:21>, @values={...=>"chained: test"}>=>...} @observable_value="chained: test">], @block=#<Proc:0x007fe951324230@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:21>, @values={#<Celluloid::Proxy::Cell(#<Class:0x007fe951054be0>:0x3ff4a887ef88) @state=#<Kontena::Observer::Observe:0x007fe9528929a0 @observables=[#<Celluloid::Proxy::Cell(#<Class:0x007fe9512ccfa8>:0x3ff4a88baf74) @observers={#<Kontena::Observer::Observe:0x007fe9528929a0 @observables=[...], @block=#<Proc:0x007fe9528929c8@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:62>, @values={...=>"test"}>=>...} @observable_value="test">], @block=#<Proc:0x007fe9528929c8@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:62>, @values={#<Celluloid::Proxy::Cell(#<Class:0x007fe9512ccfa8>:0x3ff4a88baf74) @observers={#<Kontena::Observer::Observe:0x007fe9528929a0 @observables=[...], @block=#<Proc:0x007fe9528929c8@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:62>, @values={...=>"test"}>=>...} @observable_value="test">=>"test"}> @observers={#<Kontena::Observer::Observe:0x007fe951324208 @observables=[...], @block=#<Proc:0x007fe951324230@/Users/jussi/code/kontena2/kontena/agent/spec/lib/kontena/observable_spec.rb:21>, @values={...=>"chained: test"}>=>...} @observable_value="chained: test">=>"chained: test"}>>.ready?` to return true, got false
     # ./spec/lib/kontena/observable_spec.rb:75:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:60:in `block (2 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
A bit more context for this race:

```
E, [2017-03-30T12:13:29.694953 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: No such image: redis:nonexist

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/image.rb:126:in `get'
	/app/lib/kontena/network_adapters/weave.rb:131:in `modify_create_opts'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
D, [2017-03-30T12:13:29.719774 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of redis-fail-4: running
I, [2017-03-30T12:13:29.723961 #1]  INFO -- Kontena::NetworkAdapters::Weave: initialized
I, [2017-03-30T12:13:29.735573 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating redis-fail-4
I, [2017-03-30T12:13:29.737796 #1]  INFO -- Kontena::ServicePods::Creator: creating service: redis-fail-4
I, [2017-03-30T12:13:29.747930 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
I, [2017-03-30T12:13:29.759387 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
D, [2017-03-30T12:13:34.195296 #1] DEBUG -- Kontena::Workers::NodeInfoWorker: update: #<Node:0x00560175978fc0>
D, [2017-03-30T12:13:34.195298 #1] DEBUG -- Kontena::Workers::NodeInfoWorker: notify: #<Kontena::Workers::StatsWorker:0x005601753674b0> <- #<Node:0x00560175978fc0>
D, [2017-03-30T12:13:34.195299 #1] DEBUG -- Kontena::Workers::NodeInfoWorker: observer: #<Kontena::NetworkAdapters::Weave:0x005601781c1a90> <- nil...
D, [2017-03-30T12:13:34.195299 #1] DEBUG -- Kontena::Workers::StatsWorker: configure stats: {"server"=>"127.0.0.1", "port"=>8125}
I, [2017-03-30T12:13:34.199638 #1]  INFO -- Kontena::Workers::StatsWorker: exporting stats via statsd to udp://127.0.0.1:8125
E, [2017-03-30T12:13:34.195300 #1] ERROR -- : Actor crashed!
RuntimeError: can't add a new key into hash during iteration
	/app/lib/kontena/observable.rb:53:in `add_observer'
	...
E, [2017-03-30T12:13:34.199560 #1] ERROR -- : Actor crashed!
RuntimeError: can't add a new key into hash during iteration
	/app/lib/kontena/observable.rb:53:in `add_observer'
    ...
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/observer.rb:85:in `block in observe'
	/app/lib/kontena/observer.rb:83:in `each'
	/app/lib/kontena/observer.rb:83:in `observe'
	/app/lib/kontena/network_adapters/weave.rb:42:in `start'
    ...
```

It happens if `add_observer` is called while the `Observable` actor is still working through `notify_observers`.
