### ISSUE TITLE
Agent actor calls to RpcClient#request may raise Celluloid::TaskTerminated after an RpcClient crash, leaving calling actors in a persistent vegetative state

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2063]
The agent's `Kontena::RpcClient` is a supervised actor which handles the websocket RPC request/response ID multiplexing. Other actors use synchronous `Celluloid::Actor[:rpc_client].request(...)` calls to send requests and receive responses. If the RPC request fails, either due to a timeout or an error response from the server, the `Kontena::RpcClient#request` method raises an `Kontena::RpcClient::Error`. This is propagated back to the calling actor, and that calling actor's `rpc_client.request(...)` call will fail with the `Kontena::RpcClient::Error` exception.

However, when the `Kontena::RpcClient#request` method raises an exception, the `RpcClient` actor also crashes. Normally, this is not a problem: it's a supervised actor, so it restarts and re-registers. Other actors might get some transient `Celluloid::DeadActorError`s while it's restarting, which cause the calling actors to crash and restart:

```
D, [2017-04-04T14:28:22.421336 #1] DEBUG -- Kontena::Workers::Volumes::VolumeManager: failed to request volumes from master: Celluloid::DeadActorError attempted to call a dead actor: request
E, [2017-04-04T14:28:22.430737 #1] ERROR -- : Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor: request
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/responses.rb:29:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/workers/volumes/volume_manager.rb:43:in `block in populate_volumes_from_master'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/volumes/volume_manager.rb:39:in `populate_volumes_from_master'
	/app/lib/kontena/workers/volumes/volume_manager.rb:29:in `block in start'
	/app/lib/kontena/workers/volumes/volume_manager.rb:27:in `loop'
	/app/lib/kontena/workers/volumes/volume_manager.rb:27:in `start'
```

Where this gets tricky is what happens if the `Kontena::RpcClient` actor has multiple `#request` tasks running when it crashes... only the crashing `request` call will propagate the `Kontena::RpcClient::Error` error back to the caller, while it seems that the other calling actors will receive a `Celluloid::TaskTerminated` instead. The effects of this `Celluloid::TaskTerminated` vary... it's not a `StandardError` so any `rescue => ...` will not trap it, and letting it propagate does not crash the calling actor, nor is it logged.

The `ServicePodManager` survives, because the `start` task uses `every(...) { ... }` to call the `populate_workers_from_master` which gets hit by the `Celluloid::TaskTerminated`, and it seems that each such timer loop is a separate task. If that task gets terminated, then it will be replaced by a new task.

The `VolumeManager` does not survive, because the `start` task uses a standard `loop` with `sleep` to call `populate_volumes_from_master`... if this gets hit by `Celluloid::TaskTerminated`, then the entire `start` task gets terminated, and the `VolumeManager` stops working.

```
D, [2017-04-04T14:34:12.383022 #1] DEBUG -- Kontena::Workers::Volumes::VolumeManager: failed to request volumes from master: Celluloid::TaskTerminated task was terminated
D, [2017-04-04T14:34:12.385909 #1] DEBUG -- Kontena::Workers::Volumes::VolumeManager: /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in `handle_crash'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in `run'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
(celluloid):0:in `remote procedure call'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
/app/lib/kontena/workers/volumes/volume_manager.rb:43:in `block in populate_volumes_from_master'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/workers/volumes/volume_manager.rb:39:in `populate_volumes_from_master'
/app/lib/kontena/workers/volumes/volume_manager.rb:29:in `block in start'
/app/lib/kontena/workers/volumes/volume_manager.rb:27:in `loop'
/app/lib/kontena/workers/volumes/volume_manager.rb:27:in `start'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

### Repro case
This causes the `RpcClient` actor to crash if there are other pending `request` tasks, which makes this issue very likely to occur-

```patch
diff --git a/agent/lib/kontena/rpc_client.rb b/agent/lib/kontena/rpc_client.rb
index 7be3f3a..0c30028 100644
--- a/agent/lib/kontena/rpc_client.rb
+++ b/agent/lib/kontena/rpc_client.rb
@@ -48,6 +48,8 @@ module Kontena
         raise TimeoutError.new(500, 'Request timed out') if time < (Time.now.utc - 30)
       end
       result, error = @requests.delete(id)
+      fail "crash with pending requests: #{@requests}" unless @requests.empty?
+
       if error
         raise Error.new(error['code'], error['message'])
       end
```

**Comment by SpComb** [comment]
Note that this also affects any other actors that service concurrent sync calls while crashing, not just the `RpcClient`.

I suspect the `Observable#add_observer` could also result in something similar....?

**Comment by SpComb** [comment]
Fixed for the `RpcClient` in #2008, but this may also affect other actors, such as the `NodeInfoWorker< Observable`.
