### ISSUE TITLE
1.2 Stack volumes explodes with external: false

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2092]
```
NoMethodError: undefined method `[]' for false:FalseClass
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:115:in `block in generate_volumes'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:112:in `each'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:112:in `map'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:112:in `generate_volumes'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:79:in `stack_from_reader'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:101:in `stack_read_and_dump'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/install_command.rb:23:in `execute'
```

For some reason, it seems to pass the `volume_Schema` validation:

```ruby
    def volume_schema
      {
        'external' => optional(-> (value) { value.is_a?(TrueClass) || (value.is_a?(Hash) && value['name'].is_a?(String)) })
      }
    end
```

We can either fix the validation to reject the `false`, or then support `false` and map it to `{"external": null}` in the API, or better yet, omit it.

**Comment by jnummelin** [comment]
Bug in HashValidator: https://github.com/jamesbrooks/hash_validator/pull/13
