### ISSUE TITLE
Secret update triggers update of linked service even value does not change

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2094]

**Comment by SpComb** [comment]
See https://github.com/kontena/kontena/issues/2081#issuecomment-292152633

```
I, [2017-04-06T15:01:24.530486 #624]  INFO -- GridSecrets::Update: force service development/wordpress/mysql update @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:658:in `yield_document'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:123:in `block in each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `block in each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/cursor.rb:29:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:78:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:122:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `each'
	/home/kontena/kontena/kontena/server/app/mutations/grid_secrets/common.rb:9:in `refresh_grid_services'
	/home/kontena/kontena/kontena/server/app/mutations/grid_secrets/update.rb:21:in `execute'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
	/home/kontena/kontena/kontena/server/app/routes/v1/secrets.rb:47:in `update_secret'
	/home/kontena/kontena/kontena/server/app/routes/v1/secrets.rb:75:in `block (4 levels) in <class:SecretsApi>'
```
