### ISSUE TITLE
e2e specs vpn create flaky

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2118]
No idea why, succeeds when run with `DEBUG_KOMMANDO=true`

```
  5) vpn create creates a vpn stack
     Failure/Error: expect(k.code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/features/vpn/create_spec.rb:6:in `block (2 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
Server logs hint at container port scheduling conflicts: `ERROR -- StackDeployWorker: service e2e/vpn/server deploy failed: Cannot find applicable node for service instance e2e/vpn/server-1: Did not find any nodes with unused ports: [1194]`

```
api_1      | I, [2017-04-20T14:07:59.681507 #62]  INFO -- StackDeployWorker: deploying service e2e/vpn/server...
api_1      | 172.19.0.1 - - [20/Apr/2017:14:07:59 +0000] "GET /v1/stacks/e2e/vpn/deploys/58f8c0bf5e7a74003e000198 HTTP/1.1" 200 346 0.1193
api_1      | I, [2017-04-20T14:08:00.211879 #66]  INFO -- GridServiceDeployer: starting to deploy e2e/vpn/server
api_1      | E, [2017-04-20T14:08:00.234446 #66] ERROR -- GridServiceDeployer: Cannot find applicable node for service instance e2e/vpn/server-1: Did not find any nodes with unused ports: [1194]
api_1      | E, [2017-04-20T14:08:00.697784 #62] ERROR -- StackDeployWorker: service e2e/vpn/server deploy failed: Cannot find applicable node for service instance e2e/vpn/server-1: Did not find any nodes with unused ports: [1194]
api_1      | E, [2017-04-20T14:08:00.698176 #62] ERROR -- StackDeployWorker: /app/app/jobs/stack_deploy_worker.rb:64:in `deploy_service'
api_1      | /app/app/jobs/stack_deploy_worker.rb:27:in `block in deploy_stack'
api_1      | /app/app/jobs/stack_deploy_worker.rb:25:in `each'
api_1      | /app/app/jobs/stack_deploy_worker.rb:25:in `deploy_stack'
api_1      | /app/app/jobs/stack_deploy_worker.rb:12:in `perform'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
api_1      | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```
