### ISSUE TITLE
e2e vagrant compose specs fail when run the first time

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2149]
The `test` container's `~/.kontena_client.json` gets mounted as an empty directory:

```
kontena master login --code initialadmincode --name compose-e2e http://localhost:9292
 [error] Errno::EISDIR : Is a directory @ io_fread - /root/.kontena_client.json
         Rerun the command with environment DEBUG=true set to get the full exception
rake aborted!
```

Workaround: `touch ./.kontena_client.json` before `docker-compose run --rm test`.

**Comment by SpComb** [comment]
Incorrect, touching to create an empty `.kontena_client.json` also breaks:

```
D, [2017-04-12T13:03:53.123236 #11] DEBUG -- CONFIG: Loading configuration from /root/.kontena_client.json
/kontena/cli/lib/kontena/cli/config.rb:191:in `parse_config_file': undefined method `has_key?' for nil:NilClass (NoMethodError)
    from /kontena/cli/lib/kontena/cli/config.rb:71:in `load_settings_from_config_file'
    from /kontena/cli/lib/kontena/cli/config.rb:32:in `initialize'
    from /usr/lib/ruby/2.3.0/singleton.rb:142:in `new'
    from /usr/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
    from /usr/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
    from /usr/lib/ruby/2.3.0/singleton.rb:140:in `instance'
    from /kontena/cli/lib/kontena/cli/common.rb:118:in `config'
    from /kontena/cli/lib/kontena/cli/master/login_command.rb:285:in `select_a_server'
    from /kontena/cli/lib/kontena/cli/master/login_command.rb:32:in `execute'
    from /kontena/cli/lib/kontena/command.rb:196:in `run'
    from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    from /kontena/cli/lib/kontena/command.rb:196:in `run'
    from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
    from /kontena/cli/lib/kontena/command.rb:196:in `run'
    from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
    from /usr/local/bin/kontena:17:in `<main>'
```
