### ISSUE TITLE
Server EM can block on Cloud::WebsocketClient#connect DNS lookups

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2150]
The new #2139 server Watchdog is barking:

```
I, [2017-04-12T16:50:46.858737 #31110]  INFO -- Watchdog<WebsocketBackend>: watchdog start
W, [2017-04-12T16:51:01.763966 #31110]  WARN -- Watchdog<WebsocketBackend>: watchdog delayed by 10.462s @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:673:in `bind_connect'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:653:in `connect'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/client.rb:50:in `initialize'
	/home/kontena/kontena/kontena/server/app/services/cloud/websocket_client.rb:105:in `new'
	/home/kontena/kontena/kontena/server/app/services/cloud/websocket_client.rb:105:in `connect'
	/home/kontena/kontena/kontena/server/app/services/cloud/websocket_client.rb:69:in `block in ensure_connect'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/em/timers.rb:56:in `fire'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
I, [2017-04-12T16:51:02.455117 #31110]  INFO -- Cloud::WebsocketClient: cloud connection opened to wss://socket.kontena.io
```

Tracing this out, the `eventmachine.rb:673#bind_connect` calls into the native `EventMachine.connect_server` method, which ends up in `EventMachine_t::ConnectToServer`. While the `connect` itself is non-blocking, it has to first resolve the `socket.kontena.io` address, and that seems to be a blocking operation: https://github.com/eventmachine/eventmachine/blob/v1.2.3/ext/em.cpp#L1206

```
	int gai = name2address (server, port, SOCK_STREAM, (struct sockaddr *)&bind_as, &bind_as_len);
...
	if (connect (sd, (struct sockaddr *)&bind_as, bind_as_len) == 0) {
```

**Comment by SpComb** [comment]
This should be fixed by rewriting the server `Cloud::WebsocketClient` to use a Celluloid actor with `Kontena::Websocket::Client` instead - then the DNS lookups would happen in the celluloid actor thread, and not block the EventMachine reactor used for the agent websocket connections.
