### ISSUE TITLE
CreateEventLog migration throws error if index is building

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2164]
```
I, [2017-04-17T10:31:17.298161 #1459]  INFO -- Mongodb::Migrator: migrating CreateEventLog
The operation: #<Moped::Protocol::Command
  @length=104
  @request_id=73
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="kontena_server.$cmd"
  @skip=0
  @limit=-1
  @selector={:convertToCapped=>"event_logs", :capped=>true, :size=>104857600}
  @fields=nil>
failed with error 12586: "exception: cannot perform operation: a background operation is currently running for database kontena_server"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
The operation: #<Moped::Protocol::Command
  @length=104
  @request_id=73
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="kontena_server.$cmd"
  @skip=0
  @limit=-1
  @selector={:convertToCapped=>"event_logs", :capped=>true, :size=>104857600}
  @fields=nil>
failed with error 12586: "exception: cannot perform operation: a background operation is currently running for database kontena_server"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:63:in `block in execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:608:in `block (3 levels) in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `map'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:607:in `block (2 levels) in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:663:in `read'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:90:in `command'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:73:in `block in command'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb:25:in `execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/database.rb:72:in `command'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/session.rb:83:in `command'
/app/db/migrations/24_create_event_log.rb:7:in `up'
/app/app/services/mongodb/migration.rb:6:in `migrate'
/app/app/services/mongodb/migration_proxy.rb:4:in `migrate'
/app/app/services/mongodb/migrator.rb:86:in `block in migrate_without_lock'
/app/app/services/mongodb/migrator.rb:83:in `each'
/app/app/services/mongodb/migrator.rb:83:in `migrate_without_lock'
/app/app/services/mongodb/migrator.rb:72:in `block in migrate'
/app/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
/app/app/models/distributed_lock.rb:24:in `with_lock'
/app/app/helpers/distributed_locks.rb:6:in `with_dlock'
/app/app/services/mongodb/migrator.rb:71:in `migrate'
config/puma.rb:10:in `block in _load_from'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `block in run_hooks'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `each'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:271:in `run_hooks'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:237:in `worker'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `fork'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `times'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:116:in `spawn_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:178:in `check_workers'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:444:in `run'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
/usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
/usr/bin/puma:22:in `load'
/usr/bin/puma:22:in `<main>'
```

**Comment by jakolehm** [comment]
Server recovers this error loop after background indexing completes. Not sure what we can actually do here?

**Comment by SpComb** [comment]
If the indexing blocks other operations also in the background mode, then I suppose we could revert back to doing them in the foreground, and just fix puma to not timeout the workers during the migrations instead?

**Comment by jakolehm** [comment]
It only blocks capped collection, but probably it would be safer not to spawn those index migrations to background thread.
