### ISSUE TITLE
Syntax errors in kontena.yml cause API 500 errors

### ISSUE THREAD

**Issue by xtagon** [kontena/kontena#2238]
Hi,

I found out that if my stack definition file has incorrect syntax for the `environment:` key, the API server returns a 500 error and the only way to see the error is to get it from the docker logs for kontena-server-api.

For example, I get a 500 error when I have a missing equals sign:

```
    environment:
      - KONTENA_LB_INTERNAL_PORT=4000
      - KONTENA_LB_VIRTUAL_HOST=www.example.com
      - PORT 4000
```

But even worse, I get a 500 when I try to use the YAML key/value syntax instead of a list of strings.

Here's an example of the error in the API server logs:

```
NoMethodError (undefined method `empty?' for nil:NilClass):
  /app/app/mutations/grid_services/update.rb:123:in `block in build_grid_service_envs'
  /app/app/mutations/grid_services/update.rb:122:in `each'
  /app/app/mutations/grid_services/update.rb:122:in `build_grid_service_envs'
  /app/app/mutations/grid_services/update.rb:73:in `execute'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /app/app/mutations/stacks/deploy.rb:47:in `block in create_or_update_services'
  /app/app/mutations/stacks/deploy.rb:43:in `each'
  /app/app/mutations/stacks/deploy.rb:43:in `create_or_update_services'
  /app/app/mutations/stacks/deploy.rb:31:in `execute'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:80:in `run'
  /usr/lib/ruby/gems/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /app/app/routes/v1/stacks_api.rb:52:in `deploy_stack'
  /app/app/routes/v1/stacks_api.rb:76:in `block (4 levels) in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1/stacks_api.rb:75:in `block (3 levels) in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:704:in `_verb'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:522:in `post'
  /app/app/routes/v1/stacks_api.rb:74:in `block (2 levels) in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1/stacks_api.rb:66:in `block in <class:StacksApi>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda/plugins/error_handler.rb:52:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /app/app/routes/v1_api.rb:20:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:794:in `match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `block in match_all'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `each'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `all?'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:802:in `match_all'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:770:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/app/routes/v1_api.rb:20:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:114:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:642:in `run'
  /app/server.rb:54:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:771:in `if_match'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:494:in `on'
  /app/server.rb:53:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `catch'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:248:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:222:in `block in build_rack_app'
  /app/app/middlewares/version_injector.rb:12:in `call'
  /app/app/middlewares/token_authentication.rb:73:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:59:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
  /usr/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by SpComb** [comment]
> But even worse, I get a 500 when I try to use the YAML key/value syntax instead of a list of strings.

The YAML hash syntax should work:

```yaml
    environment:
      KONTENA_LB_INTERNAL_PORT: 4000
      KONTENA_LB_VIRTUAL_HOST: www.example.com
      PORT: 4000
```

However, it looks like if you make it a YAML array of hashes by leaving in the leading `-`:

```yaml
    environment:
      - KONTENA_LB_INTERNAL_PORT: 4000
      - KONTENA_LB_VIRTUAL_HOST: www.example.com
      - PORT: 4000
```

Then the server validation error handling breaks and results in a HTTP 500 error:

```
ArgumentError (Invalid kind):
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:113:in `add_error'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/common.rb:13:in `add_service_error'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/common.rb:21:in `block in handle_service_outcome_errors'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/common.rb:20:in `each'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/common.rb:20:in `handle_service_outcome_errors'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/update.rb:42:in `block in validate'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/update.rb:28:in `each'
  /home/kontena/kontena/kontena/server/app/mutations/stacks/update.rb:28:in `validate'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:67:in `initialize'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `new'
  /home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/mutations-0.7.2/lib/mutations/command.rb:32:in `run'
  /home/kontena/kontena/kontena/server/app/routes/v1/stacks_api.rb:23:in `update_stack'
```

This seems to be because the mutations `array` validator will return an `Mutations::ErrorArray` in the form of something like `Mutations::ErrorHash({:env=>Mutations::ErrorArray([#<Mutations::ErrorAtom:0x0000000522ada8 @key=:env, @symbol=:string, @message=nil, @index=0>])})`, and this breaks `handle_service_outcome_errors` because the `atom.symbolic` is of the form `[:string]`, which is not valid for `add_error`.
