### ISSUE TITLE
[1.2.2.dev] GridServiceDeploy can get stuck in pending state if deploy create races with service remove

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2275]
There seems to be some race condition where a service can get removed after creating a `GridServiceDeploy`, but before running the deploy. The `GridServiceSchedulerWorker` will crash on the `GridServiceDeploy.grid_service` being `nil`, and the `GridServiceDeploy` will remain stuck in a pending state, being retried every 30s.

```
E, [2017-05-08T13:09:25.033175 #8694] ERROR -- : Actor crashed!
NoMethodError: undefined method `deploy_running?' for nil:NilClass
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:29:in `block in check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
	/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:24:in `with_lock'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:6:in `with_dlock'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:28:in `check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:12:in `block in watch'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `loop'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `watch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
Server logs when this happaned looks like this

```
127.0.0.1 - - [08/May/2017:11:05:44 +0300] "DELETE /v1/services/development/null/redis-test HTTP/1.1" 200 2 0.1612
D, [2017-05-08T11:05:44.010933 #3768] DEBUG -- Cloud::WebsocketClient: Sending notification message: [2, "GridService#delete", ["development", ["8b3eb564-744c-4516-92d2-3759cf95463e"], {"id"=>"development/null/redis-test", "created_at"=>"2017-04-28T13:47:01Z", "updated_at"=>"2017-04-28T13:47:01Z", "image"=>"redis:latest", "affinity"=>[], "name"=>"redis-test", "stateful"=>false, "user"=>nil, "instances"=>6, "cmd"=>nil, "entrypoint"=>nil, "net"=>"bridge", "dns"=>"redis-test.development.kontena.local", "ports"=>[], "env"=>[], "secrets"=>[], "memory"=>nil, "memory_swap"=>nil, "cpu_shares"=>nil, "volumes"=>[], "volumes_from"=>[], "cap_add"=>[], "cap_drop"=>[], "state"=>"running", "grid"=>{"id"=>"development"}, "stack"=>{"id"=>"development/null", "name"=>"null"}, "links"=>[], "log_driver"=>nil, "log_opts"=>{}, "strategy"=>"ha", "deploy_opts"=>{"wait_for_port"=>nil, "min_healt"=>0.8, "interval"=>nil}, "pid"=>nil, "instance_counts"=>{"total"=>6, "running"=>6}, "hooks"=>[], "revision"=>1, "stack_revision"=>nil}]]
D, [2017-05-08T11:05:44.033022 #3768] DEBUG -- Rpc::NodeServicePodHandler: pod list rpc took: 11ms
D, [2017-05-08T11:05:44.041682 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.072004 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.072185 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.072270 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.098363 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.105242 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.116758 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod_cache miss
D, [2017-05-08T11:05:44.138324 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod list rpc took: 109ms
D, [2017-05-08T11:05:44.250913 #3768] DEBUG -- Rpc::NodeServicePodHandler: pod list rpc took: 25ms
I, [2017-05-08T11:05:44.411655 #3768]  INFO -- GridScheduler: service development/null/redis-test has wrong number of instances (or they are not distributed correctly)
I, [2017-05-08T11:05:44.413807 #3768]  INFO -- GridScheduler: rescheduling service development/null/redis-test
D, [2017-05-08T11:05:44.474595 #3772] DEBUG -- Rpc::NodeServicePodHandler: pod list rpc took: 33ms
D, [2017-05-08T11:05:44.535993 #3768] DEBUG -- Rpc::NodeServicePodHandler: pod list rpc took: 8ms
E, [2017-05-08T11:05:44.560730 #3772] ERROR -- : Actor crashed!
NoMethodError: undefined method `deploy_running?' for nil:NilClass
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:29:in `block in check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
	/home/kontena/kontena/kontena/server/app/models/distributed_lock.rb:24:in `with_lock'
	/home/kontena/kontena/kontena/server/app/helpers/distributed_locks.rb:6:in `with_dlock'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:28:in `check_deploy_queue'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:12:in `block in watch'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `loop'
	/home/kontena/kontena/kontena/server/app/jobs/grid_service_scheduler_worker.rb:11:in `watch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
The strange part is that the `GridService` model's `grid_service_instances` relation uses `dependent: :destroy`, so destroying a `GridService` should nuke any created/queued/pending `GridServiceDeploy`s.

What probably happens here is that the `GridScheduler` started running before the `GridServices::Delete` request, so it picked up the list of `GridService` models, and then used that to create a `GridServiceDeploy >400ms later.  The `GridServices::Delete` would have destroyed the `GridService` in mongo between the `GridSchedulerJob#schedule_grid` querying `grid.grid_services.each do ...` and then calling `GridSheduler.check_service`. The `GridService` model being destroyed in mongo does not prevent creating a new `GridServiceDeploy` using that destroyed `grid_service_id` from the earlier query.

**Comment by SpComb** [comment]
This is a change per the `queued_at` logic in #2221, previously the `GridServiceSchedulerWorker` would probably crash in the same way, but now the `GridServiceDeploy` remains queued, and can get re-queued later.

This re-queueing behavior is intended to deal with workers that die before they can grab the dlock and start the deploy, but it's bad if it happens as a result of the `GridServiceDeploy` itself being corrupt like this, which just leaves it bouncing indefinitely.

**Comment by SpComb** [comment]
The possibility of ending up with such corrupt `GridServiceDeploy`s in the face of concurrent `GridServices::Remove` operation could also be considered a bug, but I suspect that would be much harder to fix. The server probably needs to be able to deal with such "corrupt" `GridServiceDeploy` objects.
