### ISSUE TITLE
e2e test compose setup is unreliable

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2295]
It tends to fail fairly often with an `invalid_grant` error for the initial `kontena master login` using the `INITIAL_ADMIN_CODE`.

```
$ docker-compose run --rm -e DEBUG=true test rake compose:setup
docker-compose up -d api
Starting test_mongodb_1
Recreating test_api_1
kontena master login --code initialadmincode --name compose-e2e http://localhost:9292
Running #<Kontena::MainCommand:0x00561d24a1e018> -- callback matcher = 'nil'
Running #<Kontena::Cli::MasterCommand:0x00561d24a35970> -- callback matcher = 'nil'
Running #<Kontena::Cli::Master::LoginCommand:0x00561d24a88558> -- callback matcher = 'master login'
D, [2017-05-08T13:21:47.918487 #11] DEBUG -- CONFIG: Loading configuration from /root/.kontena_client.json
D, [2017-05-08T13:21:47.919448 #11] DEBUG -- CONFIG: Configuration loaded with 1 servers.
D, [2017-05-08T13:21:47.919524 #11] DEBUG -- CONFIG: Current master: compose-e2e
D, [2017-05-08T13:21:47.919715 #11] DEBUG -- CONFIG: Current grid: e2e
D, [2017-05-08T13:21:47.922660 #11] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor}
[API Client Request]: POST http://localhost:9292/oauth2/token | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: "{\"grant_type\":\"authorization_code\",\"code\":\"initialadmincode\",\"client_i..."
[API Client Error]: 
D, [2017-05-08T13:21:47.999124 #11] DEBUG -- CLIENT: Request POST /oauth2/token: 404 Not Found: {"error":"invalid_grant","error_description":null}
/kontena/cli/lib/kontena/client.rb:534:in `handle_error_response': invalid_grant (Kontena::Errors::StandardError)
	from /kontena/cli/lib/kontena/client.rb:344:in `rescue in request'
	from /kontena/cli/lib/kontena/client.rb:285:in `request'
	from /kontena/cli/lib/kontena/client.rb:150:in `exchange_code'
	from /kontena/cli/lib/kontena/cli/master/login_command.rb:105:in `block in use_authorization_code'
	from /kontena/cli/lib/kontena/cli/common.rb:93:in `vspinner'
	from /kontena/cli/lib/kontena/cli/master/login_command.rb:104:in `use_authorization_code'
	from /kontena/cli/lib/kontena/cli/master/login_command.rb:49:in `execute'
	from /kontena/cli/lib/kontena/command.rb:200:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /kontena/cli/lib/kontena/command.rb:200:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /kontena/cli/lib/kontena/command.rb:200:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /usr/local/bin/kontena:17:in `<main>'
rake aborted!
Command failed with status (1): [kontena master login --code initialadminco...]
/kontena/test/Rakefile:58:in `block (2 levels) in <top (required)>'
Tasks: TOP => compose:setup => compose:setup_master
(See full trace by running task with --trace)
```

**Comment by matti** [comment]
Not only tests, but my various kontena automated setup scrips have seen this. I think there was an issue about this already.

**Comment by SpComb** [comment]
Looks like #1460, which I'm guessing was marked closed after #1921.. but it seems to be a different issue with the `INITIAL_ADMIN_CODE` that has not actually be fixed yet?

**Comment by SpComb** [comment]
For the e2e tests that I'm running, this might be happening because there's a stopped `mongodb` container left behind. `rake compose:setup` will start the existing `mongo` container, and spin up a new `api` container, so the initial admin code will naturally fail, because it's already been used prior.

**Comment by matti** [comment]
Hmmm, sounds like it could be happening for me also.

**Comment by SpComb** [comment]
Closing as this seems to be caused by leftover `mongodb` containers, aka. not running the teardown properly.
