### ISSUE TITLE
Flaky agent spec: Kontena::Workers::EventWorker#start starts processing events

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2321]
```
  1) Kontena::Workers::EventWorker#start starts processing events

     Failure/Error: expect(subject.wrapped_object).to receive(:stream_events)

       (#<Kontena::Workers::EventWorker:0x000000022220e8>).stream_events(any args)

           expected: 1 time with any arguments

           received: 0 times with any arguments

     # ./spec/lib/kontena/workers/event_worker_spec.rb:38:in `block (3 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
Also related

```
  1) Kontena::Workers::EventWorker#start streams and processes events

     Failure/Error: expect(rpc_client).to receive(:request).exactly(times).times

       (InstanceDouble(Kontena::RpcClient) (anonymous)).request(*(any args))

           expected: 100 times with any arguments

           received: 98 times with any arguments

     # ./spec/lib/kontena/workers/event_worker_spec.rb:41:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:86:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:85:in `block (2 levels) in <top (required)>'

```
