### ISSUE TITLE
Server WebsocketBackend NameError logging deadlock on RpcServer#inspect

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2348]
A typo causing a `NameError` in any `WebsocketBackend` handler method that logs the resulting `exc.message` results in a deadlock, as the `did_you_mean` core extension invokes `WebsocketBackend#inspect`. This triggers a celluloid call to `@rpc_server.inspect`, which deadlocks because the `RpcServer` actor is blocked on the `@queue.pop`, and does not dispatch the `inspect` call.

Caught by the watchdog:

```
W, [2017-05-22T15:47:55.001171 #28640]  WARN -- Watchdog<WebsocketBackend>: watchdog delayed by 1.001s @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:16:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_str'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `message'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `rescue in on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:69:in `on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:45:in `block in call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:106:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:139:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:105:in `start'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:87:in `block in start_driver'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:237:in `block in schedule'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

Some celluloid call tracing reveals the culprit:

```
I, [2017-05-22T15:53:51.003617 #30001]  INFO -- WebsocketBackend: node XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5 opened connection
CELLULOID Celluloid::Proxy::Cell CALL -> RpcServer#inspect @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:16:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_str'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `message'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `rescue in on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:69:in `on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:45:in `block in call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:106:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:139:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:105:in `start'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:87:in `block in start_driver'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:237:in `block in schedule'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

The horrible patch that fixes the issue, and proves that it's the `@rpc_server.inspect`:

```patch
--- a/server/app/middlewares/websocket_backend.rb
+++ b/server/app/middlewares/websocket_backend.rb
@@ -38,6 +38,14 @@ class WebsocketBackend
     watchdog
   end
 
+  def inspect
+    rpc_server = @rpc_server
+    @rpc_server = nil
+    super.tap {
+      @rpc_server = rpc_server
+    }
+  end
+
   def call(env)
```

**Comment by SpComb** [comment]
And to make this even worse, the watchdog does not rescue the puma worker from this deadlock, because it only aborts once... and something seems to catch that abort, and retry the deadlocked `RpcServer#inspect` call? :/

```
F, [2017-05-22T15:55:55.259051 #30005] FATAL -- Watchdog<WebsocketBackend>: watchdog timeout after 60.457s @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/home/kontena/kontena/kontena/server/lib/celluloid_tracer.rb:8:in `method_missing'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:16:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_str'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:10:in `to_s'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `message'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `rescue in on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:69:in `on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:45:in `block in call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:106:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:139:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:105:in `start'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:87:in `block in start_driver'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:237:in `block in schedule'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
CELLULOID Celluloid::Proxy::Cell CALL -> RpcServer#inspect @
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:16:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:6:in `inspect'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:6:in `to_str'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:6:in `to_s'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:6:in `call'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:6:in `original_message'
	/usr/lib/ruby/vendor_ruby/did_you_mean/spell_checkers/name_error_checkers.rb:11:in `new'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:24:in `spell_checker'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:20:in `corrections'
	/usr/lib/ruby/vendor_ruby/did_you_mean/core_ext/name_error.rb:13:in `to_s'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `message'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:105:in `rescue in on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:69:in `on_open'
	/home/kontena/kontena/kontena/server/app/middlewares/websocket_backend.rb:45:in `block in call'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:106:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket/api.rb:44:in `block in initialize'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `each'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:139:in `open'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:105:in `start'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:87:in `block in start_driver'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:237:in `block in schedule'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/home/kontena/kontena/kontena/server/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/home/kontena/kontena/kontena/server/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

The deadlocked puma worker remains out of action.
