### ISSUE TITLE
Kontena Node Health Command Broken

### ISSUE THREAD

**Issue by daniel-bytes** [kontena/kontena#2358]
When running `kontena node health $NODE`, receiving the following error message:
``` [error] ArgumentError : Can't load nodes/health_command or /kontena/cli/lib/kontena/cli/nodes/health_command```

This is happening on 1.3.0.dev

**Comment by SpComb** [comment]
What version? WFM with 1.2.2 and current 1.3.0.dev git master.

**Comment by daniel-bytes** [comment]
master

**Comment by SpComb** [comment]
Looks like the CLI `SubcommandLoader` will log that on any and all `LoadError` exceptions, so there could be something else that's breaking the `require`. Can you try with the following patch, do they get a better error message?

```patch
diff --git a/cli/lib/kontena/cli/subcommand_loader.rb b/cli/lib/kontena/cli/subcommand_loader.rb
index e188a56..54703b1 100644
--- a/cli/lib/kontena/cli/subcommand_loader.rb
+++ b/cli/lib/kontena/cli/subcommand_loader.rb
@@ -46,7 +46,8 @@ module Kontena::Cli
     def safe_require(path)
       require path
       true
-    rescue LoadError
+    rescue LoadError => exc
+      $stderr.puts "Failed to load #{path}: #{exc} @\n\t#{exc.backtrace.join("\n\t")}"
       false
     end

```

**Comment by SpComb** [comment]
> Looks like the CLI `SubcommandLoader` will log that on any and all `LoadError` exceptions, so there could be something else that's breaking the `require`.

These could e.g. be `LoadError`s caused by other `require`s deeper in the command rb file, like

```
Failed to load /home/kontena/kontena/kontena/cli/lib/kontena/cli/nodes/health_command: cannot load such file -- asdf @
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/nodes/health_command.rb:3:in `require'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/nodes/health_command.rb:3:in `<top (required)>'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/subcommand_loader.rb:47:in `require'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/subcommand_loader.rb:47:in `safe_require'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/subcommand_loader.rb:56:in `klass'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/subcommand_loader.rb:63:in `new'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:18:in `instantiate_subcommand'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:10:in `execute'
	/home/kontena/kontena/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	/home/kontena/kontena/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	bin/kontena:17:in `<top (required)>'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `load'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:27:in `run'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:332:in `exec'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:20:in `dispatch'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/cli.rb:11:in `start'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/exe/bundle:34:in `block in <top (required)>'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.13.5/exe/bundle:26:in `<top (required)>'
	/home/kontena/.local/bin/bundle:23:in `load'
	/home/kontena/.local/bin/bundle:23:in `<main>'
 [error] ArgumentError : Can't load nodes/health_command or /home/kontena/kontena/kontena/cli/lib/kontena/cli/nodes/health_command
```

The `require '/home/kontena/kontena/kontena/cli/lib/kontena/cli/nodes/health_command'` itself is fine, but some further `require` in that file raises a `LoadError`.

**Comment by daniel-bytes** [comment]
This is what I'm seeing now:
```
Failed to load node_command: cannot load such file -- node_command @
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:47:in `safe_require'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:55:in `klass'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:62:in `new'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:18:in `instantiate_subcommand'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:10:in `execute'
	/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	/kontena/cli/bin/kontena:17:in `<main>'
Failed to load nodes/health_command: cannot load such file -- nodes/health_command @
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:47:in `safe_require'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:55:in `klass'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:62:in `new'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:18:in `instantiate_subcommand'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:10:in `execute'
	/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	/kontena/cli/bin/kontena:17:in `<main>'
Failed to load /kontena/cli/lib/kontena/cli/nodes/health_command: unable to find a version of 'kontena-cli' to activate @
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require'
	/kontena/cli/lib/kontena/cli/nodes/health_command.rb:1:in `<top (required)>'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:47:in `safe_require'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:55:in `klass'
	/kontena/cli/lib/kontena/cli/subcommand_loader.rb:62:in `new'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:18:in `instantiate_subcommand'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:10:in `execute'
	/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	/kontena/cli/lib/kontena/command.rb:200:in `run'
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	/kontena/cli/bin/kontena:17:in `<main>'
```

**Comment by kke** [comment]
i wonder if this is a problem caused by the new plugin manager gem activation thing.

a plugin activates another kontena-cli.

**Comment by SpComb** [comment]
> ```
> Failed to load /kontena/cli/lib/kontena/cli/nodes/health_command: unable to find a version of 'kontena-cli' to activate @
	/home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require'
	/kontena/cli/lib/kontena/cli/nodes/health_command.rb:1:in `<top (required)>
> ```

That would be a the `require 'kontena/cli/helpers/health_helper'`... I'm guessing that `kontena etcd health`, `kontena grid health` and `kontena cloud master add` are also broken like that?

How exactly are you running the CLI? Via the `gem install` binstub, or via `bundle exec`, or something else?

**Comment by daniel-bytes** [comment]
This is happening when running directly off a cloned master, via `./bin/kontena`

**Comment by kke** [comment]
I'm doing the same thing, using rbenv, and it's working for me.

Perhaps you have some plugins installed that I don't.

`DEBUG=plugin` will give you extra info about what happens during plugin loading.

**Comment by kke** [comment]
Hmm, perhaps `lib/kontena_cli.rb`or `bin/kontena` should require the `kontena_cli.gemspec` and perhaps `Gem.loaded_specs['kontena-cli'].activate_dependencies`

**Comment by kke** [comment]
Gem.activate won't do anything if `Gem.loaded_specs.include?(GEM_NAME)` is true.

**Comment by daniel-bytes** [comment]
@kke : I'm seeing this before previous error with `DEBUG=plugin`:

```Activating plugin kontena-plugin-shell
Loading plugin kontena-plugin-shell
Plugin manager loaded features for kontena-plugin-shell: 
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/version.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/context.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/batch_do.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/exit.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/batch.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/context_top.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/help.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/debug.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/context_up.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/completer.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/commands/kontena.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/command.rb
- /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-linux/readline.so
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/session.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/shell_command.rb
- /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/x86_64-linux/etc.so
- /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb
- /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tmpdir.rb
- /home/ubuntu/.rbenv/versions/2.3.3/lib/ruby/2.3.0/tempfile.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena/plugin/shell/callbacks/stack_file.rb
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib/kontena_cli_plugin.rb
Plugin manager load paths added for kontena-plugin-shell: 
- /home/ubuntu/.kontena/gems/2.3.3/gems/kontena-plugin-shell-0.1.0.rc3/lib```

**Comment by kke** [comment]
Still happening?

**Comment by daniel-bytes** [comment]
@kke looks better now after grabbing latest master branch
