### ISSUE TITLE
CLI: 1.3.0.rc3 ruby 2.2 uninitialized constant Kontena::PluginManager::StringIO

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2442]
works with 2.3

```
/Users/uuser/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/kontena-cli-1.3.0.rc3/lib/kontena/plugin_manager.rb:205:in `dummy_ui': uninitialized constant Kontena::PluginManager::StringIO (NameError)
    from /Users/uuser/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/kontena-cli-1.3.0.rc3/lib/kontena/plugin_manager.rb:209:in `use_dummy_ui'
    from /Users/uuser/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/kontena-cli-1.3.0.rc3/lib/kontena/plugin_manager.rb:24:in `init'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/gems/kontena-cli-1.3.0.rc3/bin/kontena:17:in `<top (required)>'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/kontena:23:in `load'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/kontena:23:in `<main>'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'
/Users/uuser/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/kontena-cli-1.3.0.rc3/lib/kontena/plugin_manager.rb:205:in `dummy_ui': uninitialized constant Kontena::PluginManager::StringIO (NameError)
    from /Users/uuser/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/kontena-cli-1.3.0.rc3/lib/kontena/plugin_manager.rb:209:in `use_dummy_ui'
    from /Users/uuser/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/kontena-cli-1.3.0.rc3/lib/kontena/plugin_manager.rb:24:in `init'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/gems/kontena-cli-1.3.0.rc3/bin/kontena:17:in `<top (required)>'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/kontena:23:in `load'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/kontena:23:in `<main>'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/uuser/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jnummelin** [comment]
Works even on 2.2.3 :/
