### ISSUE TITLE
CLI: kontena node ls will cause TypeError when looped and new nodes appear

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2447]
```
while true; do
  kontena node ls
done
```

--> add 3 nodes:
```
 [error] TypeError : no implicit conversion of nil into String
         See /Users/mpa/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

```
E, [2017-06-08T13:35:57.896119 #30552] ERROR -- CLI: no implicit conversion of nil into String (TypeError)
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:69:in `+'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:69:in `block (2 levels) in node_data'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:68:in `each'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:68:in `block in node_data'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:54:in `each'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:54:in `flat_map'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:54:in `node_data'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/cli/nodes/list_command.rb:78:in `execute'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/command.rb:201:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/command.rb:201:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/lib/kontena/command.rb:201:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/Users/mpa/.rvm/gems/ruby-2.4.1/gems/kontena-cli-1.3.0.rc3/bin/kontena:18:in `<top (required)>'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/kontena:23:in `load'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/kontena:23:in `<main>'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/mpa/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by matti** [comment]
hmm, appeared again and no new nodes were joining

**Comment by jnummelin** [comment]
There's a brief period where node can be without a name. When it first calls home to master is has only unique ID and no name. The first time node sends it's full info to master, master stores the name (hostname).
