### ISSUE TITLE
e2e plugin install specs are failing

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2469]
This seems like a legit bug, as fixed in #2462

```
$ docker-compose run --rm -e DEBUG_KOMMANDO=true test rspec ./spec/features/plugin/install_spec.rb

plugin install
    *   Installing plugin aws .. |Called 'load' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).
    *   Installing plugin aws .. /Gem::InstallError : invalid gem: package is corrupt, exception while verifying: YAML data doesn't evaluate to gem specification (Gem::Exception) in /root/.kontena/gems/2.3.3/cache/kontena-cli-1.3.0.gem
 [fail] Installing plugin aws     
NAME  VERSION  DESCRIPTION
    *   Uninstalling plugin aws .. \RuntimeError : Plugin aws not installed
 [fail] Uninstalling plugin aws     
  installs a plugin (FAILED - 1)
    *   Installing plugin aws .. /Called 'load' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).
    *   Installing plugin aws .. -Gem::InstallError : invalid gem: package is corrupt, exception while verifying: YAML data doesn't evaluate to gem specification (Gem::Exception) in /root/.kontena/gems/2.3.3/cache/kontena-cli-1.3.0.gem
 [fail] Installing plugin aws     
NAME  VERSION  DESCRIPTION
    *   Uninstalling plugin aws .. \RuntimeError : Plugin aws not installed
 [fail] Uninstalling plugin aws     
  attempts to upgrade a plugin (FAILED - 2)

Failures:

  1) plugin install installs a plugin
     Failure/Error: expect(k.out).to match(/aws/)
     
       expected "\e[1mNAME\e[0m  \e[1mVERSION\e[0m  \e[1mDESCRIPTION\e[0m\r\n" to match /aws/
       Diff:
       @@ -1,2 +1,2 @@
       -/aws/
       +NAME  VERSION  DESCRIPTION
       
     # ./spec/features/plugin/install_spec.rb:12:in `block (2 levels) in <top (required)>'

  2) plugin install attempts to upgrade a plugin
     Failure/Error: expect(k.out).to match(/aws/)
     
       expected "\e[1mNAME\e[0m  \e[1mVERSION\e[0m  \e[1mDESCRIPTION\e[0m\r\n" to match /aws/
       Diff:
       @@ -1,2 +1,2 @@
       -/aws/
       +NAME  VERSION  DESCRIPTION
       
     # ./spec/features/plugin/install_spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 15.06 seconds (files took 0.20769 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/features/plugin/install_spec.rb:8 # plugin install installs a plugin
rspec ./spec/features/plugin/install_spec.rb:15 # plugin install attempts to upgrade a plugin

```

Also, it looks like the `kontena plugin install` command does not exit with a non-zero code on plugin install errors, or the spec would have failed earlier:

```
/kontena/test # kontena plugin install aws && echo yay it worked
    *   Installing plugin aws .. /Called 'load' without the :safe option -- defaulting to safe mode.
You can avoid this warning in the future by setting the SafeYAML::OPTIONS[:default_mode] option (to :safe or :unsafe).
/Gem::InstallError : invalid gem: package is corrupt, exception while verifying: YAML data doesn't evaluate to gem specification (Gem::Exception) in /root/.kontena/gems/2.3.3/cache/kontena-cli-1.3.0.gem
 [fail] Installing plugin aws     
yay it worked
```

**Comment by SpComb** [comment]
Passing now with 1.3.1 fixes in #2462

```
plugin install
  installs a plugin
  attempts to upgrade a plugin
```
