### ISSUE TITLE
Support for larger unsigned 64-bit integers in stats

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2520]
With ruby 2.4 (#2456), integers used in the agent RPC / server mongo are limited to `2**63 - 1` by the use of BSON signed 64-bit integers ([`BSON::Integer#MAX_64BIT`](http://www.rubydoc.info/github/mongodb/bson-ruby/BSON/Integer#MAX_64BIT-constant)) for mongodb:

```
     RangeError:
       18446744073709551615 is not a valid 8 byte integer value.
     # ./vendor/bundle/ruby/2.3.0/gems/bson-4.2.1/lib/bson/integer.rb:172:in `out_of_range!'
```

The MsgPack RPC used for the agent-server websocket is limited to unsigned 64-bit integers with a maximum value of `2**64 - 1` [1](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-int):

```
     Failure/Error: msg_data = MessagePack.dump([2, '/nodes/stats', params]).bytes
     RangeError:
       bignum too big to convert into `unsigned long long'
     # ./spec/services/rpc/node_handler_spec.rb:88:in `dump'
```

Previously with ruby 2.3 and the `Fixnum` / `Bignum` division, the server would convert ruby `Bignum` integers between `2**62` and `2**64 -1` as used in some specific stats-related RPCs into `Float` before storing into mongo: https://github.com/kontena/kontena/pull/2456/files#diff-77017bc3ae566137536d64fa5acf2799

**Comment by SpComb** [comment]
Ping @daniel-bytes - do you know if the agent/server node/container stats are likely to run into issues with large integers like this?

**Comment by daniel-bytes** [comment]
I think it depends on how the numbers are stored in mongodb.  Would have to set up some kind of tests.  Also I wonder how the REST API and JavaScript clients will act?

**Comment by SpComb** [comment]
Un-milestoning because it's still unclear what the impact of the broken handling of stats values between `2**63 - 1` and `2**64 - 1` is.
