### ISSUE TITLE
CLI: stack deploy gets stuck on wait_for_deployment_to_start if stack deploy errors on service removals, before starting any service deploys

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2523]
This happens in the fixed e2e `stack upgrade, for a stack that is linked to externally, fails to deploy if linked` spec, where the `StackDeployWorker` fails in the `remove_services` call:

```
api_1      | I, [2017-06-27T11:56:07.273253 #13]  INFO -- StackDeployWorker: removing following services: bar
api_1      | E, [2017-06-27T11:56:07.283861 #13] ERROR -- StackDeployWorker: service e2e/links-external-linked/bar remove failed: {"service"=>"Cannot delete service that is linked to another service (external-linking-service)"}
api_1      | E, [2017-06-27T11:56:07.286847 #13] ERROR -- StackDeployWorker: /app/app/jobs/stack_deploy_worker.rb:83:in `block in remove_services'
api_1      | /app/app/jobs/stack_deploy_worker.rb:80:in `each'
api_1      | /app/app/jobs/stack_deploy_worker.rb:80:in `remove_services'
api_1      | /app/app/jobs/stack_deploy_worker.rb:22:in `deploy_stack'
api_1      | /app/app/jobs/stack_deploy_worker.rb:12:in `perform'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

This puts the `StackDeploy` into an `error` state, without creating any associated `GridServiceDeploy`s, so the `/v1/stacks/.../deploys/...` API returns something like `{"state": "error", "service_deploys": []}`.

The CLI `kontena stack deploy` gets stuck on this, because the [`Kontena::Cli::Stacks::StacksHelper#wait_for_deployment_to_start`](https://github.com/kontena/kontena/blob/v1.3.1/cli/lib/kontena/cli/stacks/stacks_helper.rb#L9) expects the stack deploy to have non-empty `service_deploys` before it even tries to look at the `deployment['state']`:

```ruby
        until started
          deployment = client.get("stacks/#{deployment['stack_id']}/deploys/#{deployment['id']}")
          started = true if deployment['service_deploys'].size > 0
          sleep 1
        end
        if deployment['state'] == 'error'
```

**Comment by SpComb** [comment]
`DEBUG=api bundle exec bin/kontena stack deploy links-external-linked`
```
DEBUG Kontena CLI 1.4.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-hello
DEBUG Running Kontena::MainCommand with ["stack", "deploy", "links-external-linked"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::StackCommand with ["deploy", "links-external-linked"] -- callback matcher = 'nil'
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Configuration loaded with 3 servers.
DEBUG Current master: development
DEBUG Current grid: development
DEBUG Running Kontena::Cli::Stacks::DeployCommand with ["links-external-linked"] -- callback matcher = 'stacks deploy'
    *   Triggering deployment of stack links-external-linked .. \DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor}
DEBUG [Request]: POST http://localhost:9292/v1/stacks/development/links-external-linked/deploy | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: 
{}
    *   Triggering deployment of stack links-external-linked .. |DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"created","service_deploys":[]}
 [done] Triggering deployment of stack links-external-linked     
DEBUG [Request]: GET http://localhost:9292/v1/stacks/development/links-external-linked/deploys/59524bd753caed000801b6a3 | Headers: {Accept: application/json, Authorization: Bearer} 
    *   Waiting for deployment to start .. \DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"error","service_deploys":[]}
    *   Waiting for deployment to start .. /DEBUG [Request]: GET http://localhost:9292/v1/stacks/development/links-external-linked/deploys/59524bd753caed000801b6a3 | Headers: {Accept: application/json, Authorization: Bearer} 
    *   Waiting for deployment to start .. \DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"error","service_deploys":[]}
    *   Waiting for deployment to start .. /DEBUG [Request]: GET http://localhost:9292/v1/stacks/development/links-external-linked/deploys/59524bd753caed000801b6a3 | Headers: {Accept: application/json, Authorization: Bearer} 
    *   Waiting for deployment to start .. -DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"error","service_deploys":[]}
    *   Waiting for deployment to start .. |DEBUG [Request]: GET http://localhost:9292/v1/stacks/development/links-external-linked/deploys/59524bd753caed000801b6a3 | Headers: {Accept: application/json, Authorization: Bearer} 
    *   Waiting for deployment to start .. -DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"error","service_deploys":[]}
    *   Waiting for deployment to start .. |DEBUG [Request]: GET http://localhost:9292/v1/stacks/development/links-external-linked/deploys/59524bd753caed000801b6a3 | Headers: {Accept: application/json, Authorization: Bearer} 
    *   Waiting for deployment to start .. /DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"error","service_deploys":[]}
    *   Waiting for deployment to start .. \DEBUG [Request]: GET http://localhost:9292/v1/stacks/development/links-external-linked/deploys/59524bd753caed000801b6a3 | Headers: {Accept: application/json, Authorization: Bearer} 
    *   Waiting for deployment to start .. |DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.0.dev}  | Status: 200 | Body: 
{"id":"59524bd753caed000801b6a3","stack_id":"development/links-external-linked","created_at":"2017-06-27T12:13:11.181Z","state":"error","service_deploys":[]}
 [fail] Waiting for deployment to start     ^C
ERROR  (Interrupt)
/home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/stacks_helper.rb:10:in `sleep'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/stacks_helper.rb:10:in `block in wait_for_deployment_to_start'
/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/stacks_helper.rb:6:in `wait_for_deployment_to_start'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/deploy_command.rb:22:in `block in execute'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/spinner.rb:138:in `spin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/common.rb:36:in `spinner'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/deploy_command.rb:21:in `execute'
/home/kontena/kontena/kontena/cli/lib/kontena/command.rb:201:in `run'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/kontena/kontena/cli/lib/kontena/command.rb:201:in `run'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/kontena/kontena/cli/lib/kontena/command.rb:201:in `run'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
bin/kontena:18:in `<top (required)>'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/kontena/.gem/ruby/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/kontena/.local/bin/bundle:23:in `load'
/home/kontena/.local/bin/bundle:23:in `<main>'
DEBUG Execution took 6.877 seconds
DEBUG SystemExit status 130
```
