### ISSUE TITLE
kontena container ls: NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2551]
```
NoMethodError: undefined method `[]' for nil:NilClass
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:34:in `container_id'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:26:in `block in execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:80:in `format_row'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:89:in `block in rows'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:89:in `map'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:89:in `rows'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:66:in `table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:73:in `render'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:35:in `generate_table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:39:in `print_table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/containers/list_command.rb:25:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:201:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:201:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:201:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:18:in `<top (required)>'
```

Not all containers necessarily have a `node`, probably related to removed nodes AFAIK:

```json
      {
         "network_settings" : {
            "ports" : {},
            "ip_address" : "",
            "bridge" : "",
            "gateway" : "",
            "mac_address" : "",
            "ip_prefix_len" : 0,
            "port_mapping" : null
         },
         "ip_address" : null,
         "image" : "share_agent",
         "grid_id" : "development",
         "domainname" : "",
         "instance_number" : null,
         "status" : "running",
         "env" : [
            "KONTENA_URI=ws://192.168.66.1:9292",
            "LOG_LEVEL=0",
            "DEBUG=1",
            "KONTENA_NODE_TOKEN=Eaj...7OA==",
            "KONTENA_PEER_INTERFACE=eth1",
            "KONTENA_NODE_ID=development/core-02",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
         ],
         "cmd" : [
            "/app/bin/kontena-agent"
         ],
         "started_at" : "2017-06-20T13:05:38.935Z",
         "state" : {
            "error" : "",
            "restarting" : false,
            "dead" : false,
            "exit_code" : 0,
            "running" : true,
            "pid" : 8980,
            "oom_killed" : false,
            "paused" : false
         },
         "container_id" : "33058ecb2eea4f189aacac7e392a981363ab294df8a9a2790726fed4848a214c",
         "service_id" : null,
         "service_rev" : null,
         "id" : "share_agent_run_1",
         "deploy_rev" : null,
         "finished_at" : "0001-01-01T00:00:00.000Z",
         "name" : "share_agent_run_1",
         "created_at" : "2017-06-20T13:05:41.315Z",
         "hostname" : "core-02",
         "deleted_at" : null,
         "volumes" : [],
         "updated_at" : "2017-06-20T13:05:41.309Z"
      },
```

**Comment by SpComb** [comment]
Closing as duplicate of #1574
