### ISSUE TITLE
[1.3] kontena grid update does not notify nodes

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2584]
The server [`Grids::Update#notify_nodes`](https://github.com/kontena/kontena/blob/v1.3.3/server/app/mutations/grids/update.rb#L84) call to [`Agent::NodePlugger.new`](https://github.com/kontena/kontena/blob/v1.3.3/server/app/services/agent/node_plugger.rb#L10) was broken by the refactoring in #2144:

```
ArgumentError (wrong number of arguments (given 2, expected 1)):
  /app/app/services/agent/node_plugger.rb:10:in `initialize'
  /app/app/mutations/grids/update.rb:38:in `new'
  /app/app/mutations/grids/update.rb:38:in `block (2 levels) in notify_nodes'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
  /app/app/mutations/grids/update.rb:37:in `block in notify_nodes'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
  (celluloid):0:in `remote procedure call'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:142:in `value'
  /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:96:in `value'
  /app/app/mutations/grids/update.rb:30:in `execute'
```

This means that `kontena grid update` does not notify connected nodes of changes.

No specs, and this is a bare `Celluloid::Future` without `value`, so any errors just get ignored (see  #2126, there are several cases like this).

**Comment by SpComb** [comment]
Tested as fixed in #2595 1.3.4.rc1

`kontena grid update --statsd-server test test`
```

I, [2017-07-20T08:15:27.104957 #1]  INFO -- Kontena::Workers::NodeStatsWorker: exporting stats via statsd to udp://test:8125
E, [2017-07-20T08:15:27.116783 #1] ERROR -- Kontena::Workers::NodeStatsWorker: failed to configure statsd: getaddrinfo: Name does not resolve
```
