### ISSUE TITLE
Agent container exec only returns exit code 0 on Docker API errors

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2598]
To the CLI, this looks like the command succeeded without any output.

```
D, [2017-07-20T10:55:31.239057 #1] DEBUG -- Kontena::RpcServer: rpc request: Kontena::Rpc::DockerContainerApi#create_exec ["2b52d7ac3c70f4533a47d93cb81a8864eb2608705e0a986bdcced468f20e5025"]
I, [2017-07-20T10:55:31.243263 #1]  INFO -- Kontena::Actors::ContainerExec: initialized (session fe67ceb7-fc18-4f76-8890-24e9ce97e003)
D, [2017-07-20T10:55:31.275823 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#run_exec ["fe67ceb7-fc18-4f76-8890-24e9ce97e003", ["frobnicate"], false, false]
I, [2017-07-20T10:55:31.276201 #1]  INFO -- Kontena::Actors::ContainerExec: starting command: ["frobnicate"] (tty: false, stdin: false)
I, [2017-07-20T10:55:31.285781 #1]  INFO -- Kontena::Actors::ContainerExec: command finished: ["frobnicate"] with code 0
E, [2017-07-20T10:55:31.286979 #1] ERROR -- : Actor crashed!
Docker::Error::ServerError: Container 2b52d7ac3c70f4533a47d93cb81a8864eb2608705e0a986bdcced468f20e5025 is not running

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:50:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/exec.rb:22:in `create'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:75:in `exec'
	/app/lib/kontena/actors/container_exec.rb:44:in `block in run'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:142:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:96:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:446:in `defer'
	/app/lib/kontena/actors/container_exec.rb:38:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
D, [2017-07-20T10:55:31.297718 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#terminate_exec ["fe67ceb7-fc18-4f76-8890-24e9ce97e003"]
```

The agent [`Kontena::Actors::ContainerExec#run`](https://github.com/kontena/kontena/blob/v1.3.4/agent/lib/kontena/actors/container_exec.rb#L49-L51) calls `shutdown(exit_code)` from an `ensure` block, and initializes with `exit_code = 0`. The `Kontena::Rpc::DockerContainerApi` callls it via `executor.async.run(...)`, so the exception is discarded, and the server never sees it either. It only gets logged as an agent actor crash.

**Comment by SpComb** [comment]
Original example with an invalid `{cmd: { ... }}` frame sent to the server, caused a bit of debugging pain:

```
I, [2017-07-20T11:05:11.857640 #1]  INFO -- Kontena::Actors::ContainerExec: starting command: {"interactive"=>nil, "shell"=>nil, "tty"=>nil} (tty: false, stdin: false)
I, [2017-07-20T11:05:11.863475 #1]  INFO -- Kontena::Actors::ContainerExec: command finished: {"interactive"=>nil, "shell"=>nil, "tty"=>nil} with code 0
E, [2017-07-20T11:05:11.864462 #1] ERROR -- : Actor crashed!
Docker::Error::ServerError: json: cannot unmarshal object into Go value of type []string

	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:50:in `rescue in request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/exec.rb:22:in `create'
	/usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:75:in `exec'
	/app/lib/kontena/actors/container_exec.rb:44:in `block in run'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:142:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:96:in `value'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:446:in `defer'
	/app/lib/kontena/actors/container_exec.rb:38:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
Related issue about this kind of case: #1140
