### ISSUE TITLE
(Docs) Default command for s3 image registry fails

### ISSUE THREAD

**Issue by AustP** [kontena/kontena#2606]
In https://github.com/kontena/kontena/blob/master/docs/using-kontena/image-registry.md,
it instructs users who want to setup an image registry on s3 to use the following command:

    kontena registry create --s3-bucket=<bucket_name> --s3-region=<optional_aws_region>

Doing this results in a failure. The service will start and say it's running but will be in a constant state of restarting. Viewing the logs gives you the following information (repeated every ~5 seconds):

```
2017-07-22T21:39:55.000Z [1]: ~~ Kontena Registry ~~
2017-07-22T21:39:55.000Z [1]: 
2017-07-22T21:39:55.000Z [1]: 
2017-07-22T21:39:55.000Z [1]: panic: On Amazon S3 this storage driver can only be used with v4 authentication
2017-07-22T21:39:55.000Z [1]: 
2017-07-22T21:39:55.000Z [1]: goroutine 1 [running]:
2017-07-22T21:39:55.000Z [1]: panic(0xb7db80, 0xc420385b40)
2017-07-22T21:39:55.000Z [1]: 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-07-22T21:39:55.000Z [1]: github.com/docker/distribution/registry/handlers.NewApp(0x10667c0, 0xc42033d3e0, 0xc4201e7500, 0x10667c0)
2017-07-22T21:39:55.000Z [1]: 	/go/src/github.com/docker/distribution/registry/handlers/app.go:123 +0x3908
2017-07-22T21:39:55.000Z [1]: github.com/docker/distribution/registry.NewRegistry(0x7f345ea95198, 0xc42033d3e0, 0xc4201e7500, 0xc4201e7500, 0x0, 0x0)
2017-07-22T21:39:55.000Z [1]: 	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
```

The fix was simple enough but figuring it out took quite a while. This is the command that I ran:

    kontena registry create --s3-v4auth --s3-bucket=<bucket_name> --s3-region=<optional_aws_region>

After running that new command, the registry started up and I was able to push to it just fine.

I propose either updating the docs with that new command, or updating the registry create command to default that flag to true.

**Comment by SpComb** [comment]
#2242 fixes the docs, but I think the CLI default should also be changed to `--s3-v4auth`. Does someone who can readily test this want to make a PR? @jakolehm @jnummelin
