### ISSUE TITLE
Celluloid::DeadActorError: attempted to call a dead actor: network_ready?

### ISSUE THREAD

**Issue by GarPit** [kontena/kontena#2683]
Hello,

On any stack installation (via stack install) I'm getting this message and seems it can't create any instance of any service. Is there a workaround for this?

**Comment by SpComb** [comment]
Can you find the complete backtrace and any surrounding errors in the `kontena grid logs -c kontena-agent`?

This is a sign of weave network issues in the agent.

**Comment by GarPit** [comment]
```2017-08-11T12:12:17.000Z kontena-agent: I, [2017-08-11T12:12:17.349232 #1]  INFO -- Kontena::ServicePods::Creator: creating service: test1.app-1
2017-08-11T12:12:17.000Z kontena-agent: I, [2017-08-11T12:12:17.363678 #1]  INFO -- Kontena::NetworkAdapters::Weave: initialized
2017-08-11T12:12:17.000Z kontena-agent: W, [2017-08-11T12:12:17.374160 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync lb.internet_lb-1 at 2017-08-10 15:16:04 UTC: attempted to call a dead actor: network_ready?
2017-08-11T12:12:17.000Z kontena-agent: W, [2017-08-11T12:12:17.377630 #1]  WARN -- Kontena::Workers::ServicePodWorker: attempted to call a dead actor: network_ready? (Celluloid::DeadActorError)
2017-08-11T12:12:17.000Z kontena-agent: /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:9:in `method_missing'
2017-08-11T12:12:17.000Z kontena-agent: /app/lib/kontena/helpers/weave_helper.rb:66:in `block in wait_network_ready?'
2017-08-11T12:12:17.000Z kontena-agent: /app/lib/kontena/helpers/wait_helper.rb:33:in `block in wait_until'
2017-08-11T12:12:17.000Z kontena-agent: /app/lib/kontena/helpers/wait_helper.rb:32:in `loop'
2017-08-11T12:12:17.000Z kontena-agent: /app/lib/kontena/helpers/wait_helper.rb:32:in `wait_until'
2017-08-11T12:12:17.000Z kontena-agent: /app/lib/kontena/helpers/wait_helper.rb:63:in `wait_until!'
2017-08-11T12:12:17.000Z kontena-agent: /app/lib/kontena/helpers/weave_helper.rb:65:in `wait_network_ready?'```

**Comment by GarPit** [comment]
Also, this ERROR:

```
2017-08-11T12:12:17.000Z kontena-agent: I, [2017-08-11T12:12:17.409385 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
2017-08-11T12:12:17.000Z kontena-agent: E, [2017-08-11T12:12:17.679830 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "<redacted>", "--trusted-subnets", ""]
2017-08-11T12:12:17.000Z kontena-agent: weave is already running; you can stop it with 'weave stop-router'.
2017-08-11T12:12:17.000Z kontena-agent:
2017-08-11T12:12:17.000Z kontena-agent: I, [2017-08-11T12:12:17.698792 #1]  INFO -- Kontena::NetworkAdapters::Weave: router does not have any known peers```

**Comment by SpComb** [comment]
Those two error logs don't reveal anything. There should be some `ERROR -- : Actor crashed!` errors/stacktraces from before the `Celluloid::DeadActorError`, which would tell what happened.

**Comment by GarPit** [comment]
Will this help? (no `Actor crashed` actually)

```
2017-08-11T13:26:57.000Z kontena-agent: I, [2017-08-11T13:26:57.142600 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating lb.internet_lb-1
2017-08-11T13:26:57.000Z kontena-agent: I, [2017-08-11T13:26:57.142843 #1]  INFO -- Kontena::ServicePods::Creator: creating service: lb.internet_lb-1
2017-08-11T13:26:57.000Z kontena-agent: W, [2017-08-11T13:26:57.188272 #1]  WARN -- Kontena::RpcClient: RPC request /node_service_pods/set_state failed: RuntimeError: Instance not found
2017-08-11T13:26:57.000Z kontena-agent: E, [2017-08-11T13:26:57.761956 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "<redacted>", "--trusted-subnets", ""]
2017-08-11T13:26:57.000Z kontena-agent: weave is already running; you can stop it with 'weave stop-router'.
2017-08-11T13:26:57.000Z kontena-agent:
2017-08-11T13:26:57.000Z kontena-agent: I, [2017-08-11T13:26:57.780347 #1]  INFO -- Kontena::NetworkAdapters::Weave: router does not have any known peers
```

**Comment by SpComb** [comment]
The `launch-router` ERROR is routine, and should be ignored: #1397

There must be an `Actor crashed` error somewhere, but it's possible that it won't show up in the `kontena grid logs` if the agent was disconnected from the master when it happened. Can you try `kontena node ssh the-broken-node docker logs kontena-agent` instead, which should show all logs since the last restart, including those where the agent was offline? Include as much context around any `Actor crashed` messages up to the `Celluloid::DeadActorError`.

Regardless, there are known cases where the agent is unable to recover from weave actor crashes, and you can probably fix your issue by restating the agent (`kontena node ssh ... systemctl restart kontena-agent`). It would still be nice to see the agent logs showing the exact cause of the crash, and test that the new agent code in #2582 would be able to handle it.

**Comment by SpComb** [comment]
Here's the similar case that I saw, where etcd was unavailable during the agent startup. The agent [`Kontena::Launchers::IpamPlugin#start`](https://github.com/kontena/kontena/blob/3b5a3d8c2846cd4757ad70a1d23df3eea1000213/agent/lib/kontena/launchers/ipam_plugin.rb#L41-L45) uses `wait_until ` instead of `wait_until!`, so it proceeds to notify `ipam:start` if the wait for the IPAM plugin to be ready times out. The `Kontena::NetworkAdapters::Weave` proceeds to request the default pool, and then crashes on that failing.

```
D, [2017-08-21T09:04:10.742996 #1] DEBUG -- Kontena::ServicePods::Creator: waiting 1.7s of 300.0s until: network ready
D, [2017-08-21T09:04:10.824548 #1] DEBUG -- Kontena::NetworkAdapters::IpamClient: Request POST /Plugin.Activate: 500 Internal Server Error: {"Error":"503 \"Service Unavailable\""}
D, [2017-08-21T09:04:10.832075 #1] DEBUG -- Kontena::ServicePods::Creator: waiting 1.8s of 300.0s until: network ready
D, [2017-08-21T09:04:11.069453 #1] DEBUG -- Kontena::NetworkAdapters::IpamClient: Request POST /Plugin.Activate: 500 Internal Server Error: {"Error":"503 \"Service Unavailable\""}
D, [2017-08-21T09:04:11.165305 #1] DEBUG -- Kontena::NetworkAdapters::IpamClient: Request POST /Plugin.Activate: 500 Internal Server Error: {"Error":"503 \"Service Unavailable\""}
W, [2017-08-21T09:04:11.191214 #1]  WARN -- Kontena::Launchers::IpamPlugin: timeout after waiting 300.3s of 300.0s until: IPAM running
D, [2017-08-21T09:04:11.228268 #1] DEBUG -- Kontena::NetworkAdapters::IpamCleaner: ipam signalled ready, starting cleanup loop
I, [2017-08-21T09:04:11.231388 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network with subnet=10.81.0.0/16 iprange=10.81.128.0/17
D, [2017-08-21T09:04:11.245218 #1] DEBUG -- Kontena::NetworkAdapters::IpamClient: reserving pool kontena with subnet 10.81.0.0/16 and iprange 10.81.128.0/17
D, [2017-08-21T09:04:11.468031 #1] DEBUG -- Kontena::NetworkAdapters::IpamClient: Request POST /IpamDriver.RequestPool: 500 Internal Server Error: {"Error":"503 \"Service Unavailable\""}
E, [2017-08-21T09:04:12.792533 #1] ERROR -- : Actor crashed!
Kontena::NetworkAdapters::IpamError: 503 "Service Unavailable"
	/app/lib/kontena/network_adapters/ipam_client.rb:117:in `handle_error_response'
	/app/lib/kontena/network_adapters/ipam_client.rb:47:in `rescue in reserve_pool'
	/app/lib/kontena/network_adapters/ipam_client.rb:34:in `reserve_pool'
	/app/lib/kontena/network_adapters/weave.rb:188:in `ensure_default_pool'
	/app/lib/kontena/network_adapters/weave.rb:154:in `on_ipam_start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
W, [2017-08-21T09:04:12.923082 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync ingress-lb.lb-1 at 2017-08-21 08:49:03 UTC: attempted to call a dead actor: network_ready?
W, [2017-08-21T09:04:12.936796 #1]  WARN -- Kontena::Workers::ServicePodWorker: attempted to call a dead actor: network_ready? (Celluloid::DeadActorError)
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:9:in `method_missing'
/app/lib/kontena/helpers/weave_helper.rb:66:in `block in wait_network_ready?'
/app/lib/kontena/helpers/wait_helper.rb:33:in `block in wait_until'
/app/lib/kontena/helpers/wait_helper.rb:32:in `loop'
/app/lib/kontena/helpers/wait_helper.rb:32:in `wait_until'
/app/lib/kontena/helpers/wait_helper.rb:63:in `wait_until!'
/app/lib/kontena/helpers/weave_helper.rb:65:in `wait_network_ready?'
/app/lib/kontena/service_pods/creator.rb:41:in `perform'
/app/lib/kontena/workers/service_pod_worker.rb:120:in `ensure_running'
/app/lib/kontena/workers/service_pod_worker.rb:97:in `ensure_desired_state'
/app/lib/kontena/workers/service_pod_worker.rb:76:in `block in apply'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/workers/service_pod_worker.rb:74:in `apply'
/app/lib/kontena/workers/service_pod_worker.rb:33:in `update'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
W, [2017-08-21T09:04:12.929637 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync redis-1 at 2017-08-21 08:49:03 UTC: attempted to call a dead actor: network_ready?
```
