### ISSUE TITLE
Flaky agent spec: Kontena::Workers::FluentdWorker#configure creates fluentd logger and starts forwarding

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2726]
Looks like this might result in a DNS lookup that times out?

```
  1) Kontena::Workers::FluentdWorker#configure creates fluentd logger and starts forwarding

     Failure/Error: subject.configure(info)

     Timeout::Error:

       execution expired

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'

     # ./vendor/bundle/ruby/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'

     # ./vendor/bundle/ruby/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'

     # ./spec/lib/kontena/workers/fluentd_worker_spec.rb:27:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:79:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:78:in `block (2 levels) in <top (required)>
```

**Comment by jnummelin** [comment]
fixed in #2738 as it now mocks all operation with Fluentd
