### ISSUE TITLE
Agent container exec input can block the entire RPC server

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2740]
Using `kontena service exec -i` to write large amounts of input to the stdin of an exec process that does not read that input, the agent RPC server can block:

```
$ python3 -c "while True: print('spam'*32)" | bundle exec bin/kontena service exec -i redis sleep 300
...
$ bundle exec bin/kontena etcd health core-01
⊗ Node core-01 is unhealthy: Connection timeout (10s)
```

In this state, the agent remains running and connected, because only the `Kontena::RpcServer` actor is blocked:

```
D, [2017-08-28T10:21:47.867357 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#tty_input ["1dc66a62-b6e9-4fd7-925a-366b06f2b331", "spamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspam\n"]
D, [2017-08-28T10:21:47.879046 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#tty_input ["1dc66a62-b6e9-4fd7-925a-366b06f2b331", "spamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspam\n"]
D, [2017-08-28T10:21:47.905532 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#tty_input ["1dc66a62-b6e9-4fd7-925a-366b06f2b331", "spamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspamspam\n"]



D, [2017-08-28T10:21:53.725282 #1] DEBUG -- Kontena::RpcClient: waiting 0.6s of 30.0s until: request /node_volumes/list has response wth id=2118173953
D, [2017-08-28T10:21:54.158082 #1] DEBUG -- Kontena::RpcClient: waiting 1.0s of 30.0s until: request /node_volumes/list has response wth id=2118173953
```

Call path:
* [`Kontena::WebsocketClient#on_message`](https://github.com/kontena/kontena/blob/4b80b456c275ba13ffa449ecc86db0da00356df7/agent/lib/kontena/websocket_client.rb#L274): `Actor[:rpc_server].async.handle_notification(...)`
* [`Kontena::RpcServer#handle_notification`](https://github.com/kontena/kontena/blob/4b80b456c275ba13ffa449ecc86db0da00356df7/agent/lib/kontena/rpc_server.rb#L73): `Kontena::Rpc::DockerContainerApi.send(:tty_input)` (in exclusive mode)
* [`Kontena::Rpc::DockerContainerApi#tty_input`](https://github.com/kontena/kontena/blob/4b80b456c275ba13ffa449ecc86db0da00356df7/agent/lib/kontena/rpc/docker_container_api.rb#L150): `Celluloid::Actor["container_exec_*"].input(...)` (sync celluloid call in exclusive mode)
* [`Kontena::Actors::ContainerExec#input`](https://github.com/kontena/kontena/blob/4b80b456c275ba13ffa449ecc86db0da00356df7/agent/lib/kontena/actors/container_exec.rb#L26): `@write_pipe.write(input)`

The `Kontena::RpcServer` actor will thus block any further requests/notifications from the `Kontena::WebsocketClient` actor until the exclusive call to the `Kontena::Actors::ContainerExec` actor `@write_pipe.write(...)` returns.

The other end of the `stdin` pipe is read by the `Docker::Exec#start` => [`Docker::Util.hijack_for`](https://github.com/swipely/docker-api/blob/v1.33.6/lib/docker/util.rb#L68) thread... I guess at some point the exec process stdin pipe fills up, the Docker engine stops reading from the API socket, and then eventually the `IO.copy_stream` blocks on the socket write, allowing the `stdin` pipe to fill up, and then the container exec input call blocks.

Fix for this would probably be to make sure the `Kontena::Rpc::DockerContainerApi#tty_input` RPC handler is async, by changing the sync call to `executor.async.input(...)`. This should still preserve message ordering.

**Comment by SpComb** [comment]
The `TTIN` dump is now sadly missing the threads spawned by the `docker-api` gem, but it shows the blocking `Kontena::RpcServer` and `Kontena::Actors::ContainerExec` threads:

```
Celluloid::Actor 0x42ecbdbe18
Celluloid::Cell 0x42ecbdec94: Kontena::RpcServer
State: Running (executing tasks)
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'
	/usr/lib/ruby/gems/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/app/lib/kontena/rpc/docker_container_api.rb:150:in `tty_input'
	/app/lib/kontena/rpc_server.rb:73:in `handle_notification'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:74:in `block (2 levels) in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:74:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'


	Tasks:
	  1) Celluloid::Task::Fibered[call]: running
	      {:dangerous_suspend=>false, :method_name=>:handle_notification}
		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.

Celluloid::Actor 0x42edaece0c
Celluloid::Cell 0x42edaecfc4: Kontena::Actors::ContainerExec
State: Running (executing tasks)
	/app/lib/kontena/actors/container_exec.rb:26:in `write'
	/app/lib/kontena/actors/container_exec.rb:26:in `input'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:74:in `block (2 levels) in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:74:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'


	Tasks:
	  1) Celluloid::Task::Fibered[call]: receiving
	      {:dangerous_suspend=>false, :method_name=>:run}
		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.


	  2) Celluloid::Task::Fibered[call]: running
	      {:dangerous_suspend=>false, :method_name=>:input}
		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
```

**Comment by SpComb** [comment]
Here's the additional `docker-api` threads from #2742:

```
Thread 0x5f85a3f6e4 <>
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/util.rb:68:in `copy_stream'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/util.rb:68:in `block (2 levels) in hijack_for'

Thread 0x5f85a3f590 <>
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/util.rb:79:in `readpartial'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/util.rb:79:in `block (2 levels) in hijack_for'
```

**Comment by SpComb** [comment]
Logging errors from within the `Kontena::Actors::ContainerExec#run` `defer` block:

```
E, [2017-08-28T11:23:05.571059 #1] ERROR -- Kontena::Actors::ContainerExec: Broken pipe - write (Errno::EPIPE) (Excon::Error::Socket)
/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/util.rb:68:in `copy_stream'
/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/util.rb:68:in `block (2 levels) in hijack_for'
```

The stdin-copy thread crashing does not close the `stdin` pipe, and there's still a reference to it in `@read_pipe`, which is what leaves the `input` => `@write_pipe.write` call stalled.
