### ISSUE TITLE
kontena node/labels update does not notify nodes

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2746]
Affects 1.3 and 1.4. 

This means that changes to node `region` labels are not applied until weave is restarted manually on the nodes.

Very similar to #2584, shows up in the #2699 logging.. except that in 1.4, #2306 overrode `HostNodes::Update#notify_node`, it breaks differently on 1.4:

```
E, [2017-08-29T05:44:24.602482 #13] ERROR -- HostNodes::Update: wrong number of arguments (given 2, expected 1) (ArgumentError)
/app/app/mutations/host_nodes/update.rb:55:in `notify_node'
/app/app/mutations/host_nodes/common.rb:7:in `block in notify_grid'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
/app/app/mutations/host_nodes/common.rb:6:in `notify_grid'
/app/app/mutations/host_nodes/update.rb:25:in `block in execute'
/app/app/helpers/async_helper.rb:11:in `block in async_thread'
172.17.0.1 - - [29/Aug/2017:05:44:24 +0000] "PUT /v1/nodes/development/core-01 HTTP/1.1" 200 1726 0.1076
```

**Comment by SpComb** [comment]
With the way that the provisioning plugins configure the node `region` labels, the broken node_info update on node labels changes means that provisioned nodes can get stuck with the wrong region / weave peer IPs until rebooted/restarted: https://github.com/kontena/kontena-plugin-aws/blob/a6a6684d649fb3cd31290cda1f3c436554b2afa7/lib/kontena/machine/aws/node_provisioner.rb#L99-L109

The plugins only set the `region` labels on the node using `HostNode::Update once the the agent has connected, updated and the `HostNode` shows up with the right name. That means that the first node info that the agent sees will have the default region and the public peer IPs?

The broken node update means that the agent will end up stuck with the wrong peer IPs until it restarts, or the node info otherwise updates.
