### ISSUE TITLE
server MongoPubSub error when running mongo "repairDatabase"

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2759]
Does this matter? repairDatabase is completed successfully (manually ran).

```
ERROR -- MongoPubsub: error while tailing: GetMore command executor error: OperationFailed: Operation aborted because: cursor killed (96)
ERROR -- MongoPubsub: ["/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/result.rb:256:in `validate!'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/executable.rb:37:in `block in execute'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server/connection_pool.rb:107:in `with_connection'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/server.rb:242:in `with_connection'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/operation/executable.rb:35:in `execute'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:188:in `block in get_more'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/retryable.rb:51:in `read_with_retry'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:187:in `get_more'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:113:in `each'", "/usr/lib/ruby/gems/2.3.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'", "/usr/lib/ruby/gems/2.3.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'", "/app/app/services/mongo_pubsub.rb:155:in `block in tail!'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'", "/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'"]
2017-09-02T13:21:29.274077+00:00 app[web.1]: I, [2017-09-02T13:21:29.273955 #8]  INFO -- MongoPubsub: starting to tail collection
```

**Comment by jakolehm** [comment]
No, server will reconnect tail.
