### ISSUE TITLE
[1.4] ServicePodWorker cannot restart container if it crashes during wait_for_port

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2775]
The new 1.4 `ServicePodWorker` based restart policies do not interact well with the use of `wait_for_port` in service container deployments. If deploying a new service container, and the container crashes while the `ServicePodWorker` -> `ServicePods::Creator` is stuck in the `wait_for_port` loop, then the container will not be restarted until after the 5-minute timeout.

```
$ kontena service create --cmd 'sleep 3' --deploy-wait-for-port 6379 redis-waitforport redis 
 [done] Creating redis-waitforport service      
$ kontena service deploy redis-waitforport
 [fail] Deploying service redis-waitforport      
 [error] 500 : halting deploy of development/null/redis-waitforport, one or more instances failed:
	⊗ Failed to deploy instance development/null/redis-waitforport-1 to node core-01: Timeout::Error: Timeout after waiting 300.0s until: service development/null/redis-waitforport-1 is running on node development/core-01 at 2017-09-06 13:26:01 UTC
```

```
I, [2017-09-06T13:26:01.971726 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating redis-waitforport-1
I, [2017-09-06T13:26:01.971821 #1]  INFO -- Kontena::ServicePods::Creator: creating service: redis-waitforport-1
...
I, [2017-09-06T13:26:06.401003 #1]  INFO -- Kontena::ServicePods::Creator: service started: redis-waitforport-1
I, [2017-09-06T13:26:06.401925 #1]  INFO -- Kontena::ServicePods::Creator: waiting for port redis-waitforport-1:6379 to respond


W, [2017-09-06T13:31:06.407741 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync redis-waitforport-1 at 2017-09-06 13:26:01 UTC: execution expired
W, [2017-09-06T13:31:06.408051 #1]  WARN -- Kontena::Workers::ServicePodWorker: execution expired (Timeout::Error)
/app/lib/kontena/service_pods/creator.rb:195:in `sleep'
/app/lib/kontena/service_pods/creator.rb:195:in `block in wait_for_port'
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/app/lib/kontena/service_pods/creator.rb:194:in `wait_for_port'
/app/lib/kontena/service_pods/creator.rb:73:in `perform'
/app/lib/kontena/workers/service_pod_worker.rb:174:in `ensure_running'
/app/lib/kontena/workers/service_pod_worker.rb:151:in `ensure_desired_state'
/app/lib/kontena/workers/service_pod_worker.rb:125:in `block in apply'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/workers/service_pod_worker.rb:123:in `apply'
I, [2017-09-06T13:31:06.438808 #1]  INFO -- Kontena::Workers::ServicePodWorker: restarting redis-waitforport-1 because it has stopped
D, [2017-09-06T13:31:06.440276 #1] DEBUG -- Kontena::Workers::ServicePodWorker: restart triggered (from 2017-09-06 13:31:06 UTC)
D, [2017-09-06T13:31:06.440385 #1] DEBUG -- Kontena::Workers::ServicePodWorker: state of redis-waitforport-1: running
I, [2017-09-06T13:31:06.461033 #1]  INFO -- Kontena::Workers::ServicePodWorker: starting redis-waitforport-1
```

The `ServicePodWorker#apply` -> `ensure_running` happens in exclusive mode, which blocks the actor from seeing the `on_container_event` notifications. Even if it wasn't in exclusive mode, the `sleep` happens in the `ServicePods::Creator` class, so it's an actual blocking `Kernel#sleep`, not a suspending `Celluloid#sleep`.

**Comment by SpComb** [comment]
Changed in #2776 to fail the deploy if the container gets restarted during the `wait_for_port`.
