### ISSUE TITLE
Server stack remove: GridServices::Stop: can't modify frozen BSON::Document (RuntimeError)

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2777]
Shows up in the #2699 logging when removing a stack, which tries to stop the stack services. Not entirely sure what the `frozen BSON::Document` is, but I'm guessing this is from the [`StackRemoveWorker#stop_stack`](https://github.com/kontena/kontena/blob/45cf5ffaa02493ff0ee180fbcae33379d5f41c5b/server/app/jobs/stack_remove_worker.rb#L19) -> [`GridServices::Stop#execute` `async_thread do grid_service.set_state('stopped')`](https://github.com/kontena/kontena/blob/45cf5ffaa02493ff0ee180fbcae33379d5f41c5b/server/app/mutations/grid_services/stop.rb#L13) racing with the [`StackRemoveWorker#remove_stack`](https://github.com/kontena/kontena/blob/45cf5ffaa02493ff0ee180fbcae33379d5f41c5b/server/app/jobs/stack_remove_worker.rb#L26) -> [`GridServices::Delete#execute` `grid_service.destroy`](https://github.com/kontena/kontena/blob/45cf5ffaa02493ff0ee180fbcae33379d5f41c5b/server/app/mutations/grid_services/delete.rb#L19). The async stop thread is trying to mutate the the `GridService` after it has been destroyed by the main thread.

```
172.17.0.1 - - [07/Sep/2017:11:10:03 +0000] "DELETE /v1/stacks/development/test HTTP/1.1" 200 2 0.1173
E, [2017-09-07T11:10:03.573530 #21] ERROR -- GridServices::Stop: can't modify frozen BSON::Document (RuntimeError)
/usr/lib/ruby/gems/2.4.0/gems/bson-4.2.1/lib/bson/document.rb:68:in `[]='
/usr/lib/ruby/gems/2.4.0/gems/bson-4.2.1/lib/bson/document.rb:68:in `[]='
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/attributes.rb:182:in `block in write_attribute'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/threaded/lifecycle.rb:31:in `_assigning'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/attributes.rb:170:in `write_attribute'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/fields.rb:462:in `block (2 levels) in create_field_setter'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/attributes/processing.rb:100:in `process_attribute'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/settable.rb:34:in `block (2 levels) in set'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable.rb:172:in `block in process_atomic_operations'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable.rb:167:in `each'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable.rb:167:in `process_atomic_operations'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/settable.rb:24:in `block in set'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable.rb:145:in `prepare_atomic_operation'
/usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/persistable/settable.rb:23:in `set'
/app/app/models/grid_service.rb:105:in `set_state'
/app/app/mutations/grid_services/stop.rb:16:in `rescue in block in execute'
/app/app/mutations/grid_services/stop.rb:12:in `block in execute'
/app/app/helpers/async_helper.rb:11:in `block in async_thread'
```

**Comment by SpComb** [comment]
Yes, [`Mongoid::Document#destroy`](https://github.com/mongodb/mongoid/blob/v5.2.1/lib/mongoid/persistable/destroyable.rb#L24) calls [`#delete`](https://github.com/mongodb/mongoid/blob/v5.2.1/lib/mongoid/persistable/deletable.rb#L23) -> [`#prepare_delete`](https://github.com/mongodb/mongoid/blob/v5.2.1/lib/mongoid/persistable/deletable.rb#L116), which `freeze`s the document after it's been deleted.

It doesn't make sense to trigger the async stop mutation for the stack services right before destroying them. With the async stop, the agents would need to pull the updated service instances before they get destroyed, which is highly unlikely to happen.
