### ISSUE TITLE
Flaky agent spec: Kontena::Observer For a supervised observer that observes a supervised actor by name restarts after the observable crashes and waits for it to update

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2800]
```
  1) Kontena::Observer For a supervised observer that observes a supervised actor by name restarts after the observable crashes and waits for it to update

     Failure/Error: expect(@observer_actor.values).to eq [1]

       expected: [1]

            got: nil

       (compared using ==)

     # ./spec/lib/kontena/observer_spec.rb:545:in `block (3 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
Also for the same spec:

```
  1) Kontena::Observer For a supervised observer that observes a supervised actor by name restarts after the observable crashes and waits for it to update

     Failure/Error: expect{@observer_actor.ping}.to raise_error(Celluloid::DeadActorError)

     Timeout::Error:

       execution expired

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'

     # ./vendor/bundle/ruby/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:77:in `block in receive'

     # ./vendor/bundle/ruby/2.4.0/gems/timers-4.1.1/lib/timers/wait.rb:14:in `for'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:76:in `receive'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:50:in `wait'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:141:in `suspend'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:41:in `response'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'

     # ./vendor/bundle/ruby/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'

     # ./spec/lib/kontena/observer_spec.rb:568:in `block (4 levels) in <top (required)>'

     # ./spec/lib/kontena/observer_spec.rb:568:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:86:in `block (3 levels) in <top (required)>'

     # ./spec/spec_helper.rb:85:in `block (2 levels) in <top (required)>'

     # ./spec/spec_helper.rb:78:in `block (2 levels) in <top (required)>'

     # ./spec/spec_helper.rb:69:in `block (2 levels) in <top (required)>'
```
