### ISSUE TITLE
e2e specs: stack install from file returns error if file not found

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2805]
Looks like the error message has changed; the new `Can't determine stack file origin for '...'` is maybe also less clear than "no such file"?

```
stack install
  from file
 [error] RuntimeError : Can't determine stack file origin for 'foo.yml'
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
 [error] 404 : Not Found (/v1/stacks/e2e/simple)
    returns error if file not found (FAILED - 1)

Failures:

  1) stack install from file returns error if file not found
     Failure/Error: expect(k.out.match(/no such file/i)).to be_truthy
     
       expected: truthy value
            got: nil
     # ./spec/features/stack/install_spec.rb:34:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/install_spec.rb:31:in `block (3 levels) in <top (required)>'
```

**Comment by kke** [comment]
```diff
-expect(k.out.match(/no such file/i)).to be_truthy
+expect(k.out).to match /no such file/i
```
💭

**Comment by SpComb** [comment]
> :thought_balloon:

Yeah, re-running with `-e DEBUG_KOMMANDO=1` is required to make any sense of the spec failures.
