### ISSUE TITLE
e2e specs: stack install from file returns error if file is invalid

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2806]
Not sure what's happening here... the invalid stack is supposed to fail validation, but it's actually getting POST'd to the server?

```
stack install
  from file
 [fail] Creating stack simple      
 [error] 422 : Unprocessable Entity:
	services: Services isn't an array
	volumes: Volumes isn't an array
 [error] 404 : Not Found (/v1/stacks/e2e/simple)
    returns error if file is invalid (FAILED - 1)

Failures:

  1) stack install from file returns error if file is invalid
     Failure/Error: expect(k.out.match(/validation failed/i)).to be_truthy
     
       expected: truthy value
            got: nil
     # ./spec/features/stack/install_spec.rb:42:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/install_spec.rb:39:in `block (3 levels) in <top (required)>'
```

**Comment by kke** [comment]
It has something to do with this:
https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/stacks/yaml/reader.rb#L320

```ruby
          exit_with_error("Image is missing for #{name}. Aborting.") unless service_config['image'] # why isn't this a validation?
```
