### ISSUE TITLE
e2e specs: stack validate service_link returns an error if link does not exist

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2807]
The `lb: from: service_link` error is reported a part of the YAML output (`errors: presence: Required value missing`), but the command still exits with success. Not entirely sure how it's supposed to behave?

```
stack validate
  service_link
---
# /kontena/test/spec/fixtures/stack/service_link/kontena.yml
stack: test/test
version: 0.1.0
variables:
  lb:
    label: lb
    type: string
    from:
      service_link:
        prompt: Select link
        image: redis
      env: lb
    to:
      env: lb
    errors:
      presence: Required value missing
    value: 
  GRID:
    label: GRID
    type: string
    from:
      env: GRID
    to:
      env: GRID
    errors: {}
    value: validate
  STACK:
    label: STACK
    type: string
    from:
      env: STACK
    to:
      env: STACK
    errors: {}
    value: test
  PLATFORM:
    label: PLATFORM
    type: string
    from:
      env: PLATFORM
    to:
      env: PLATFORM
    errors: {}
    value: validate-platform
services:
  nginx:
    image: nginx:1-alpine
    links:
    - 
 [error] 404 : Not Found (/v1/stacks/e2e/simple)
    returns an error if link does not exist (FAILED - 1)

Failures:

  1) stack validate service_link returns an error if link does not exist
     Failure/Error: expect(k.code).not_to eq(0)
     
       expected: value != 0
            got: 0
     
       (compared using ==)
     # ./spec/features/stack/validate_spec.rb:25:in `block (4 levels) in <top (required)>'
     # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:32:in `chdir'
     # ./spec/support/shell.rb:32:in `with_fixture_dir'
     # ./spec/features/stack/validate_spec.rb:23:in `block (3 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
Seems to be fixed in #2812, although the resulting error is not formatted nicely:

```
stack validate
  service_link
 [error] RuntimeError : Variable validation failed: {"lb"=>{:presence=>"Required value missing"}} in /kontena/test/spec/fixtures/stack/service_link/kontena.yml
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
 [error] 404 : Not Found (/v1/stacks/e2e/simple)
    returns an error if link does not exist

```
