### ISSUE TITLE
e2e plugin support specs: Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2811]
When running with `docker-compose run test`, the `bundle exec ruby ...` somehow fails: `bundle exec ruby -e 'puts "Hello World"'`
```
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

Not sure why, the `Gemfile` has `gem 'dotenv'`, and `gem list` shows `dotenv`?

```
plugin support
  spinner
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    is available by including Kontena::Cli::ShellSpinner (FAILED - 1)
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    is available by including Kontena::Cli::Common (FAILED - 2)
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    is available without including anything (FAILED - 3)
  client
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    does not need be required (FAILED - 4)
  config
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    does not need to be required (FAILED - 5)
  common
Could not find gem 'dotenv' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    has access to the essentials (FAILED - 6)

Failures:

  1) plugin support spinner is available by including Kontena::Cli::ShellSpinner
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:7:in `block (3 levels) in <top (required)>'

  2) plugin support spinner is available by including Kontena::Cli::Common
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:13:in `block (3 levels) in <top (required)>'

  3) plugin support spinner is available without including anything
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:19:in `block (3 levels) in <top (required)>'

  4) plugin support client does not need be required
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:27:in `block (3 levels) in <top (required)>'

  5) plugin support config does not need to be required
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:35:in `block (3 levels) in <top (required)>'

  6) plugin support common has access to the essentials
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:43:in `block (3 levels) in <top (required)>'

Finished in 6.61 seconds (files took 0.28762 seconds to load)
6 examples, 6 failures

Failed examples:

rspec ./spec/features/plugin/run_spec.rb:5 # plugin support spinner is available by including Kontena::Cli::ShellSpinner
rspec ./spec/features/plugin/run_spec.rb:11 # plugin support spinner is available by including Kontena::Cli::Common
rspec ./spec/features/plugin/run_spec.rb:17 # plugin support spinner is available without including anything
rspec ./spec/features/plugin/run_spec.rb:25 # plugin support client does not need be required
rspec ./spec/features/plugin/run_spec.rb:33 # plugin support config does not need to be required
rspec ./spec/features/plugin/run_spec.rb:41 # plugin support common has access to the essentials
```

**Comment by SpComb** [comment]
This time for the `rspec` gem:

```
plugin support
  spinner
Could not find gem 'rspec' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    is available by including Kontena::Cli::ShellSpinner (FAILED - 1)
Could not find gem 'rspec' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    is available by including Kontena::Cli::Common (FAILED - 2)
Could not find gem 'rspec' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    is available without including anything (FAILED - 3)
  client
Could not find gem 'rspec' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    does not need be required (FAILED - 4)
  config
Could not find gem 'rspec' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    does not need to be required (FAILED - 5)
  common
Could not find gem 'rspec' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
    has access to the essentials (FAILED - 6)

Failures:

  1) plugin support spinner is available by including Kontena::Cli::ShellSpinner
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:7:in `block (3 levels) in <top (required)>'

  2) plugin support spinner is available by including Kontena::Cli::Common
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:13:in `block (3 levels) in <top (required)>'

  3) plugin support spinner is available without including anything
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:19:in `block (3 levels) in <top (required)>'

  4) plugin support client does not need be required
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:27:in `block (3 levels) in <top (required)>'

  5) plugin support config does not need to be required
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:35:in `block (3 levels) in <top (required)>'

  6) plugin support common has access to the essentials
     Failure/Error: expect(k.code).to be_zero
       expected `7.zero?` to return true, got false
     # ./spec/features/plugin/run_spec.rb:43:in `block (3 levels) in <top (required)>'

Finished in 6.06 seconds (files took 0.27844 seconds to load)
6 examples, 6 failures

Failed examples:

rspec ./spec/features/plugin/run_spec.rb:5 # plugin support spinner is available by including Kontena::Cli::ShellSpinner
rspec ./spec/features/plugin/run_spec.rb:11 # plugin support spinner is available by including Kontena::Cli::Common
rspec ./spec/features/plugin/run_spec.rb:17 # plugin support spinner is available without including anything
rspec ./spec/features/plugin/run_spec.rb:25 # plugin support client does not need be required
rspec ./spec/features/plugin/run_spec.rb:33 # plugin support config does not need to be required
rspec ./spec/features/plugin/run_spec.rb:41 # plugin support common has access to the essentials
```

**Comment by SpComb** [comment]
This is probably part of the same issue:

```
plugin support
  spinner
There was an error while trying to write to `/kontena/test/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
    is available by including Kontena::Cli::ShellSpinner (FAILED - 1)
There was an error while trying to write to `/kontena/test/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
    is available by including Kontena::Cli::Common (FAILED - 2)
There was an error while trying to write to `/kontena/test/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
    is available without including anything (FAILED - 3)
  client
There was an error while trying to write to `/kontena/test/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
    does not need be required (FAILED - 4)
  config
There was an error while trying to write to `/kontena/test/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
    does not need to be required (FAILED - 5)
  common
There was an error while trying to write to `/kontena/test/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
    has access to the essentials (FAILED - 6)
```
