### ISSUE TITLE
Flaky server spec: MongoPubsub.publish cleanups threads

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2837]
Possibly some side-effect of #2785?

```
  1) MongoPubsub.publish cleanups threads

     Failure/Error: expect(thread_count == Thread.list.count).to be_truthy

       expected: truthy value

            got: false

     # ./spec/services/mongo_pubsub_spec.rb:107:in `block (3 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
Fixing the `expect(...).to eq ...` and repeating the spec shows that some thread hasn't been cleaned up yet:

```
  1) MongoPubsub.publish cleanups threads
     Failure/Error: expect(Thread.list.count).to eq(thread_count)
       
       expected: 19
            got: 20
       
       (compared using ==)
     # ./spec/services/mongo_pubsub_spec.rb:107:in `block (3 levels) in <top (required)>'
```

I suspect this is just a timing issue in the spec that didn't happen before #2785... not sure if the spec even tested anything, because the `Celluloid::Future` threads used to only get spawned on actual messages, but this spec doesn't publish anything.
