### ISSUE TITLE
[1.4] Service hook exec output logging is broken

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2842]
From #2750: the agent `Kontena::ServicePods::Creator#log_hook_output` still uses the old `/containers/log` RPC method, since replaced by `log_batch`:

```
E, [2017-09-19T17:34:09.621277 #20] ERROR -- RpcServer: NoMethodError: undefined method `log' for #<Rpc::ContainerHandler:0x00563c48d184b0>
E, [2017-09-19T17:34:09.621405 #20] ERROR -- RpcServer: /app/app/services/rpc_server.rb:87:in `handle_notification'
/app/app/services/rpc_server.rb:45:in `process!'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
Fixed in #2701
