### ISSUE TITLE
CLI tty exec fails with non-ASCII input

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2871]
With `kontena service exec -it`, and entering some UTF-8/non-ASCII input (high bit set):

```
DEBUG websocket exec write: {"stdin"=>"\xC3\xA4"} 
ERROR "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `encode'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:90:in `websocket_exec_write'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:109:in `block (2 levels) in websocket_exec_write_thread'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:41:in `block (2 levels) in read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:39:in `loop'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:39:in `block in read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:37:in `raw'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:37:in `read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:108:in `block in websocket_exec_write_thread'
```

The non-tty `kontena service exec -i` does handle UTF-8:

```
$ echo 'fåå' > unicode.txt
$ sha1sum unicode.txt 
8f9c3ee212dc345afa87c5aa7c3d6ccdf9511b19  unicode.txt
$ bin/kontena service exec -i redis cat < unicode.txt | sha1sum 
8f9c3ee212dc345afa87c5aa7c3d6ccdf9511b19  -
```

But it does not handle arbitrary binary input:

```
$ dd if=/dev/urandom of=random.bin bs=1k count=1
1+0 records in
1+0 records out
1024 bytes (1,0 kB, 1,0 KiB) copied, 0,00329882 s, 310 kB/s
$ sha1sum random.bin 
c0c07e2da48d871ed1f5d2d46ab5e14bb838190a  random.bin
$ bundle exec bin/kontena service exec -i redis cat < random.bin | sha1sum 
 [error] RuntimeError : stdin read JSON::GeneratorError: source sequence is illegal/malformed utf-8
         See /home/kontena/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
da39a3ee5e6b4b0d3255bfef95601890afd80709  -
```
```
DEBUG websocket exec write: {"stdin"=>"\xF9\xB4\xFA\xE1\xE9E\x81\x9B\xD8\u000F\xC9Ƿ8v\u001E3\xF4DS\u0002\u0010\xE9\xA36\xF9!\u0005\x87\xC5\u00151s\\c\xCE-w\xC3$M\u001D=o\u0016\u0010\x87\xB8%x\xE2\tL\x9D\u00194,,N\u001E\x93\xE6\u0011w?\xBC\x9A\xCCy\xAE5Gk\xC5\u001F\xD4`\xAAZ\x83>\x9D\u001A\xBDmf\x8E\x96\u0010\xF2\u0006Qx[:\n"}
ERROR source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:90:in `websocket_exec_write'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:109:in `block (2 levels) in websocket_exec_write_thread'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:47:in `read_stdin'
/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:108:in `block in websocket_exec_write_thread'
ERROR websocket exec error: stdin read JSON::GeneratorError: source sequence is illegal/malformed utf-8
```

**Comment by SpComb** [comment]
This is a regression in 1.4, valid UTF-8 input works fine in the 1.3 `kontena service exec`.

With the arbitrary binary input (invalid UTF-8), the 1.3 `kontena service exec` seems to hang without errors.

**Comment by SpComb** [comment]
Actually, this isn't a regression in 1.4, it looks like this also affects 1.3, I just got mislead by the weird way that the 1.3 CLI breaks: the exception in the `Thread.new { STDIN.raw { ...  } }` block puts the CLI stdin back into local echo mode before getting ignored, so the first non-ascii input gets lost. The following input shows up via local tty echo, but the exec input is dead, and the input never gets sent to the remote container tty.

```
"\xC3" from ASCII-8BIT to UTF-8 @ /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `encode'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:224:in `generate'
	/home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/json-2.0.2/lib/json/common.rb:394:in `dump'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:15:in `block (2 levels) in stream_stdin_to_ws'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:13:in `raw'
	/home/kontena/kontena/kontena/cli/lib/kontena/cli/helpers/exec_helper.rb:13:in `block in stream_stdin_to_ws'
```
