### ISSUE TITLE
Agent ServicePodManager fails on broken containers

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2873]
It is possible for a Docker container to show up in `Docker::Container.all`, but be broken such a way that `Docker::Container#json` fails. This leaves the `ServicePodManager` in a persistent broken state where it is unable to even terminate the affected container.

 This could also happen on a race where the container is removed in between the call to `Docker::Container.all` and `Docker::Container#json`.

```
E, [2017-09-28T11:40:10.136415 #1] ERROR -- : Actor crashed!
Docker::Error::NotFoundError: stat /var/lib/docker/overlay2/a1a4c16d1c38ea238c658305786852ea552cff0f8e65a61773f95307650b0ce2: no such file or directory

   /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
   /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
   /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
   /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:153:in `block (2 levels) in <class:Container>'
   /app/lib/docker/container.rb:224:in `cached_json'
   /app/lib/docker/container.rb:14:in `labels'
   /app/lib/docker/container.rb:119:in `service_id'
   /app/lib/kontena/workers/service_pod_manager.rb:80:in `block in populate_workers_from_docker'
   /app/lib/kontena/workers/service_pod_manager.rb:78:in `each'
   /app/lib/kontena/workers/service_pod_manager.rb:78:in `populate_workers_from_docker'
   /app/lib/kontena/workers/service_pod_manager.rb:30:in `start'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
   /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
In this case, the broken container shows up with status `Dead`.
