### ISSUE TITLE
Certificate auto-renewal can fail if domain authz's linked service has been removed

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#2881]
This will cause only the single cert renewal to fail but causes lot of "vomit" on the logs. And having this pop up as ` undefined method `stack' for nil:NilClass (NoMethodError)` does not make it easy to figure out.

```
api_1      | E, [2017-09-29T10:40:08.614963 #13] ERROR -- CertificateRenewJob: undefined method `stack' for nil:NilClass (NoMethodError)
api_1      | /app/app/jobs/certificate_renew_job.rb:56:in `block in authorize_domains'
api_1      | /app/app/jobs/certificate_renew_job.rb:49:in `each'
api_1      | /app/app/jobs/certificate_renew_job.rb:49:in `authorize_domains'
api_1      | /app/app/jobs/certificate_renew_job.rb:39:in `renew_certificate'
api_1      | /app/app/jobs/certificate_renew_job.rb:32:in `block in renew_certificates'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:678:in `yield_document'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:130:in `block in each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/query_cache.rb:221:in `each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual/mongo.rb:129:in `each'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/mongoid-5.2.1/lib/mongoid/contextual.rb:20:in `each'
api_1      | /app/app/jobs/certificate_renew_job.rb:31:in `renew_certificates'
api_1      | /app/app/jobs/certificate_renew_job.rb:23:in `block (2 levels) in perform'
api_1      | /app/app/helpers/distributed_locks.rb:7:in `block in with_dlock'
api_1      | /app/app/models/distributed_lock.rb:24:in `with_lock'
api_1      | /app/app/helpers/distributed_locks.rb:6:in `with_dlock'
api_1      | /app/app/jobs/certificate_renew_job.rb:22:in `block in perform'
api_1      | /app/app/jobs/certificate_renew_job.rb:20:in `loop'
api_1      | /app/app/jobs/certificate_renew_job.rb:20:in `perform'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
api_1      | /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by SpComb** [comment]
The `GridService` should probably have `has_many :grid_domain_authorizations, dependent: :destroy`.
