### ISSUE TITLE
child stack install fails on stack.parent.to_path

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2883]
From #2866: Installing a new stack with dependencies will create the child stacks with a `parent_name`, such that the [`stack.has_parent?`](https://github.com/kontena/kontena/blob/c29a5a5f2da95fd412d55632e3ff798378d988d1/server/app/views/v1/stacks/_stack.json.jbuilder#L19) is true, but the `stack.parent` is `nil`, which causes the request to fail on [`stack.parent.to_path`](https://github.com/kontena/kontena/blob/c29a5a5f2da95fd412d55632e3ff798378d988d1/server/app/views/v1/stacks/_stack.json.jbuilder#L21):

```
NoMethodError (undefined method `to_path' for nil:NilClass):
  /app/app/views/v1/stacks/_stack.json.jbuilder:21:in `block (3 levels) in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:35:in `block in set!'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:258:in `block in _merge_block'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:301:in `_scope'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:258:in `_merge_block'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:35:in `set!'
  /app/app/views/v1/stacks/_stack.json.jbuilder:20:in `block (2 levels) in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:15:in `partial!'
  /app/app/views/v1/stacks/show.json.jbuilder:1:in `block (2 levels) in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `eval'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:52:in `block in evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:16:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:8:in `initialize'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `new'
  /usr/lib/ruby/gems/2.4.0/gems/jbuilder-2.2.5/lib/jbuilder.rb:21:in `encode'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-jbuilder-0.6.1/lib/tilt/jbuilder.rb:46:in `evaluate'
  /usr/lib/ruby/gems/2.4.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/render.rb:265:in `render'
  /app/app/routes/v1/grids/grid_stacks.rb:16:in `block (3 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:460:in `is'
  /app/app/routes/v1/grids/grid_stacks.rb:7:in `block (2 levels) in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:758:in `_verb'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:540:in `post'
  /app/app/routes/v1/grids/grid_stacks.rb:6:in `block in <top (required)>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/multi_route.rb:211:in `route'
  /app/app/routes/v1/grids_api.rb:60:in `block (3 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:59:in `block (2 levels) in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1/grids_api.rb:55:in `block in <class:GridsApi>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/error_handler.rb:66:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/app/routes/v1_api.rb:13:in `block (2 levels) in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:857:in `match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `block in match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `each'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `all?'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `match_all'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:831:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/app/routes/v1_api.rb:13:in `block in <class:Api>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
  /app/server.rb:54:in `block (2 levels) in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
  /app/server.rb:53:in `block in <class:Server>'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
  /app/app/middlewares/version_injector.rb:12:in `call'
  /app/app/middlewares/token_authentication.rb:70:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
  /app/app/middlewares/websocket_backend.rb:74:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

172.17.0.1 - - [29/Sep/2017:11:51:49 +0000] "POST /v1/grids/development/stacks HTTP/1.1" 500 35 0.1525
```

**Comment by SpComb** [comment]
The `if stack.has_parent?` should probably just be replaced with `if parent_stack = stack.parent`. That would also avoid the two calls to `stack.parent.*`, which are both separate queries ATM.
