### ISSUE TITLE
NoMethodError : undefined method `get_screen_size' for Readline:Module when used in terraform

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2955]
Saw this for the first time, not happening always?
```
google_compute_firewall.internal: Modifying... (ID: allow-internal)
  source_ranges.2947016772: "" => "10.132.0.0/20"
  source_ranges.3703411150: "10.152.0.0/20" => ""
google_compute_disk.initials[2] (local-exec):  [error] NoMethodError : undefined method `get_screen_size' for Readline:Module
google_compute_disk.initials[2] (local-exec):          See /Users/mpa/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
google_compute_disk.initials[2] (local-exec): no node found with prefix i-3
google_compute_disk.initials[0] (local-exec):  [error] NoMethodError : undefined method `get_screen_size' for Readline:Module
google_compute_disk.initials[0] (local-exec):          See /Users/mpa/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
google_compute_disk.initials[0] (local-exec): no node found with prefix i-1
google_compute_disk.initials[1] (local-exec):  [error] NoMethodError : undefined method `get_screen_size' for Readline:Module
google_compute_disk.initials[1] (local-exec):          See /Users/mpa/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
google_compute_disk.initials[1] (local-exec): no node found with prefix i-2
```

**Comment by kke** [comment]
Maybe installing the gem `rb-readline` could help?

What's the backtrace like?

**Comment by matti** [comment]
```
E, [2017-10-23T10:59:46.287455 #3337] ERROR -- CLI: undefined method `get_screen_size' for Readline:Module (NoMethodError)
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-screen-0.5.0/lib/tty/screen/size.rb:68:in `from_readline'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-screen-0.5.0/lib/tty/screen/size.rb:23:in `size'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-screen-0.5.0/lib/tty/screen.rb:45:in `size'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-screen-0.5.0/lib/tty/screen.rb:26:in `size'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-screen-0.5.0/lib/tty/screen.rb:31:in `width'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:121:in `block in initialize'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:121:in `fetch'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:121:in `initialize'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer.rb:94:in `new'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer.rb:94:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer.rb:77:in `render_with'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table.rb:451:in `render_with'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table.rb:425:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:74:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:35:in `generate_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:39:in `print_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/nodes/list_command.rb:94:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/bin/kontena:18:in `<top (required)>'
/opt/kontena/embedded/bin/kontena:23:in `load'
/opt/kontena/embedded/bin/kontena:23:in `<main>'
```

**Comment by piotrmurach** [comment]
I've released new versions of `tty-table` and `tty-screen` which fix this issue.

**Comment by SpComb** [comment]
@kke CLI gemspec probably needs a PR to bump `tty-table` to `~> 0.9.0`?

**Comment by kke** [comment]
Yes

**Comment by SpComb** [comment]
Any idea how to repro this for testing? It's not just `kontena node list | grep ...` with a non-tty stdout.

**Comment by matti** [comment]
This happens in terraform local-exec at least.
