### ISSUE TITLE
CLI NoMethodError: undefined method `debug?' for #<Kontena::MainCommand:0x000000026c6450>

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2985]
CLI fails on unhandled exceptions like internal server errors in DEBUG mode:

```
DEBUG Request GET /v1/certificates/development/test.188.226.131.23.xip.io/export: 500 Internal Server Error: {"message":"Internal server error"}
bundler: failed to load command: bin/kontena (bin/kontena)
NoMethodError: undefined method `debug?' for #<Kontena::MainCommand:0x000000026c6450>
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:244:in `rescue in run'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:200:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:19:in `<top (required)>'
```

https://github.com/kontena/kontena/blob/3d608c58a0c0ce046e3a3f2065c39431b2fbc13f/cli/lib/kontena/command.rb#L244

Looks like the `Kontena::Command#run` rescue handler fails for anything that doesn't include `Kontena::Cli::Common` with `debug?` - that includes the top-level `Kontena::MainCommand`?

**Comment by SpComb** [comment]
Oops, this is fixed for `StandardError`, but still broken for `Kontena::Errors::StandardError` as raised for non-2xx server responses: https://github.com/kontena/kontena/blob/7fe2f4797b97977c63822d95a4c1123adc81e925/cli/lib/kontena/command.rb#L234-L235

```
DEBUG [Request]: GET http://localhost:9292/v1/services/development/null/test | Headers: {Accept: application/json, Authorization: Bearer} 
DEBUG [Error]: Expected([200, 201, 204]) <=> Actual(404 Not Found)

DEBUG Request GET /v1/services/development/null/test: 404 Not Found: {"error":"Not found"}
bundler: failed to load command: bin/kontena (bin/kontena)
NoMethodError: undefined method `debug?' for #<Kontena::Cli::ServiceCommand:0x000000021081d0>
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:235:in `rescue in run'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:200:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:19:in `<top (required)>'
```
