### ISSUE TITLE
Actor crashed - network_ready - container went missing

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#3027]
I'm not really sure what is going on here but I'm seeing lots of fatal errors in my kontena agent logs and I cannot deploy services because of them...

I upgraded to 1.3.5 and am trying to setup a firewall to lock down weave, of course using a docker container:

```yml
stack: firewall
version: 0.5.1
description: Global firewall services

variables:
  # A comma-separated list of IPs to allow for Weave
  firewall_weave_static:
    type: string
    from:
      vault: FIREWALL_WEAVE_STATIC
      prompt: List of IPs/CIDRs to allow for Weave (specify local networks, not public)
    to:
      vault: FIREWALL_WEAVE_STATIC

services:
  weave:
    image: colinmollenhour/confd-firewall
    secrets:
      - secret: FIREWALL_WEAVE_STATIC
        name: FW_STATIC
        type: env
    environment:
      - FW_MODE=host
      - FW_SERVICE=weave
      - FW_PROTO=tcp,udp
      - FW_PORTS=6783:6784
    cap_add:
      - NET_ADMIN
    network_mode: host
    instances: 1
    deploy:
      strategy: daemon
      min_health: 0.0
```

This is a simplified example (the full version uses etcd to discover nodes for updating firewall rules dynamically, but the containers won't even start so it shouldn't matter).

```
I, [2017-11-08T22:28:37.538185 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: colinmollenhour/confd-firewall:latest
I, [2017-11-08T22:28:37.721664 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: colinmollenhour/confd-firewall:latest
W, [2017-11-08T22:32:36.940923 #1]  WARN -- Kontena::Launchers::IpamPlugin: timeout after waiting 301.6s of 300.0s until: IPAM running
W, [2017-11-08T22:33:35.763972 #1]  WARN -- Kontena::Workers::WeaveWorker: timeout after waiting 360.4s of 300.0s until: weave running
E, [2017-11-08T22:33:35.765415 #1] ERROR -- : Actor crashed!
Timeout::Error: Timeout after waiting 300.0s until: weave running
        /app/lib/kontena/helpers/wait_helper.rb:66:in `wait_until!'
        /app/lib/kontena/helpers/weave_helper.rb:59:in `wait_weave_running?'
        /app/lib/kontena/workers/weave_worker.rb:51:in `on_dns_add'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2017-11-08T22:33:35.774817 #1]  INFO -- Kontena::Workers::WeaveWorker: initialized
W, [2017-11-08T22:34:35.864862 #1]  WARN -- Kontena::ServicePods::Creator: timeout after waiting 358.1s of 300.0s until: network ready
W, [2017-11-08T22:34:35.869376 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync firewall.weave-1 at 2017-11-08 22:28:37 UTC: Timeout after waiting 300.0s until: network ready
W, [2017-11-08T22:34:35.869474 #1]  WARN -- Kontena::Workers::ServicePodWorker: Timeout after waiting 300.0s until: network ready (Timeout::Error)
/app/lib/kontena/helpers/wait_helper.rb:66:in `wait_until!'
/app/lib/kontena/helpers/weave_helper.rb:65:in `wait_network_ready?'
/app/lib/kontena/service_pods/creator.rb:41:in `perform'
/app/lib/kontena/workers/service_pod_worker.rb:120:in `ensure_running'
/app/lib/kontena/workers/service_pod_worker.rb:97:in `ensure_desired_state'
/app/lib/kontena/workers/service_pod_worker.rb:76:in `block in apply'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/workers/service_pod_worker.rb:74:in `apply'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2017-11-08T22:34:35.908165 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating firewall.weave-1
I, [2017-11-08T22:34:35.908322 #1]  INFO -- Kontena::ServicePods::Creator: creating service: firewall.weave-1
I, [2017-11-08T22:35:35.959154 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network with subnet=10.81.0.0/16 iprange=10.81.128.0/17
E, [2017-11-08T22:35:43.018658 #1] ERROR -- : Actor crashed!
Kontena::NetworkAdapters::IpamError: 500 "Internal Server Error"
        /app/lib/kontena/network_adapters/ipam_client.rb:117:in `handle_error_response'
        /app/lib/kontena/network_adapters/ipam_client.rb:47:in `rescue in reserve_pool'
        /app/lib/kontena/network_adapters/ipam_client.rb:34:in `reserve_pool'
        /app/lib/kontena/network_adapters/weave.rb:190:in `ensure_default_pool'
        /app/lib/kontena/network_adapters/weave.rb:156:in `on_ipam_start'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-11-08T22:35:43.026216 #1] ERROR -- : Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor: already_started?
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/responses.rb:29:in `value'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        /app/lib/kontena/workers/weave_worker.rb:23:in `initialize'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-11-08T22:35:43.027220 #1] ERROR -- : Error ( RuntimeError ) at start of supervised instance of Kontena::Workers::WeaveWorker
E, [2017-11-08T22:35:43.027474 #1] ERROR -- : Actor crashed!
RuntimeError: a container instance went missing. This shouldn't be!
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-supervision-0.20.5/lib/celluloid/supervision/container.rb:118:in `restart_actor'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `block in call'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
W, [2017-11-08T22:35:43.031655 #1]  WARN -- Kontena::Workers::ServicePodWorker: failed to sync firewall.weave-1 at 2017-11-08 22:28:37 UTC: attempted to call a dead actor: network_ready?
W, [2017-11-08T22:35:43.031757 #1]  WARN -- Kontena::Workers::ServicePodWorker: attempted to call a dead actor: network_ready? (Celluloid::DeadActorError)
/usr/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/responses.rb:29:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
/app/lib/kontena/helpers/weave_helper.rb:66:in `block in wait_network_ready?'
/app/lib/kontena/helpers/wait_helper.rb:33:in `block in wait_until'
/app/lib/kontena/helpers/wait_helper.rb:32:in `loop'
/app/lib/kontena/helpers/wait_helper.rb:32:in `wait_until'
/app/lib/kontena/helpers/wait_helper.rb:63:in `wait_until!'
/app/lib/kontena/helpers/weave_helper.rb:65:in `wait_network_ready?'
/app/lib/kontena/service_pods/creator.rb:41:in `perform'
/app/lib/kontena/workers/service_pod_worker.rb:120:in `ensure_running'
/app/lib/kontena/workers/service_pod_worker.rb:97:in `ensure_desired_state'
/app/lib/kontena/workers/service_pod_worker.rb:76:in `block in apply'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
/app/lib/kontena/workers/service_pod_worker.rb:74:in `apply'
/app/lib/kontena/workers/service_pod_worker.rb:33:in `update'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

The container adds firewall rules via iptables to deny traffic to non-whitelisted IPs. Here is a script that effectively does the same thing, only not dynamic or dockerized:

```sh
#!/bin/bash

set -e -x

IF=$(ip route | awk '/^default/{print $5}')

# Cleanup
iptables -D INPUT -i $IF -p tcp -m tcp --dport 6783:6784 -j DOCKER-HOST-kontena || true
iptables -D INPUT -i $IF -p udp -m udp --dport 6783:6784 -j DOCKER-HOST-kontena || true
iptables -F DOCKER-HOST-kontena || true
iptables -X DOCKER-HOST-kontena || true

[[ $1 = "disable" ]] && exit 1

iptables -N DOCKER-HOST-kontena
iptables -A DOCKER-HOST-kontena -s 10.99.0.0/20 -j RETURN
iptables -A DOCKER-HOST-kontena -s 99.99.0.0/20 -j RETURN
iptables -A DOCKER-HOST-kontena -j DROP

iptables -I INPUT -i $IF -p tcp -m tcp --dport 6783:6784 -j DOCKER-HOST-kontena
iptables -I INPUT -i $IF -p udp -m udp --dport 6783:6784 -j DOCKER-HOST-kontena
```

However, I've tried many times removing the firewall rules, removing the leftover containers (if any) checking that the agents are still healthy (checked agents, etcd, weave for errors like timeouts) and I still can't deploy this stack...

Is this a bug or user error, and how can I get this up an running?

**Comment by SpComb** [comment]
All of those errors point at etcd or weave being unhealthy: the `kontena-ipam-plugin` can't start if etcd isn't working, and `kontena-etcd` can't work if the `weave` overlay network doesn't work. Basic weave troubleshooting is checking `ip addr show dev weave` on the nodes, and checking connectivity between the nodes with `ping 10.81.0.X`. Since you're setting up iptables `INPUT` drop rules, you also need to verify that the `etcd` service also works: `curl http://10.81.0.X:2379/health`.

To reset the iptables rules completely, you may want to try rebooting the nodes. If `ping 10.81.0.X` works and you can deploy services after rebooting, then try re-configuring those iptables rules and see if the `ping` stops working, or if `etcd` stops working - I expect it would.

There's several things you need to take into account when setting up `iptables` `INPUT` rules, based on the [Node Infrastructure Services](https://www.kontena.io/docs/advanced/networking.html#node-infrastructure-services): 
* The `kontena-etcd` connections on `127.0.0.1`, `10.81.0.X` and the `docker0` bridge IP on TCP port 2379/2380
* Weave TCP port 6783 + IPSec ESP between the nodes using their public/private IP

In particular, whitelisting UDP port 6783/6784 traffic from the external node addresses is not going to work re IPSec. You need to match the overlay network packets twice in your iptables ruleset: first the IPSec ESP packets with the external node addresses, and then the decapsulated pcakets with the overlay network addresses.

---

BTW the timing in those logs is odd, normally this would be #2683 but the timing here should be much faster, on the order of <1s, not three minutes:

```
W, [2017-11-08T22:32:36.940923 #1]  WARN -- Kontena::Launchers::IpamPlugin: timeout after waiting 301.6s of 300.0s until: IPAM running
I, [2017-11-08T22:35:35.959154 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network with subnet=10.81.0.0/16 iprange=10.81.128.0/17
E, [2017-11-08T22:35:43.018658 #1] ERROR -- : Actor crashed!
```

Also:

```
W, [2017-11-08T22:33:35.763972 #1]  WARN -- Kontena::Workers::WeaveWorker: timeout after waiting 360.4s of 300.0s until: weave running
W, [2017-11-08T22:34:35.864862 #1]  WARN -- Kontena::ServicePods::Creator: timeout after waiting 358.1s of 300.0s until: network ready
```

Not sure what's going on there to cause the agent to slow down that badly... must be hitting some timeouts because of the `-j DROP`?

**Comment by colinmollenhour** [comment]
So I did the following steps:

1. Completely shut down and removed all kontena-agent containers on this grid including weave, ipam, etcd and cadvisor containers then rebooted all nodes and verified that iptables rules are the defaults and all table policies are ACCEPT so nothing is being blocked at all. 
2. Verified hostnames and private IP addresses:
  - test2.local.lan -> 10.99.159.131
  - test3.local.lan -> 10.99.159.135
  - test4.local.lan -> 10.99.159.133
3. Verified weave adapter is up and noted IPs using `ip addr show dev weave`.
  - test2.local.lan -> 10.81.0.1
  - test3.local.lan -> 10.81.0.2
  - test4.local.lan -> 10.81.0.3
4. Checked weave logs for errors and now I see the following:

```
INFO: 2017/11/09 17:41:06.802756 ->[10.99.159.133:41783] connection accepted
INFO: 2017/11/09 17:41:06.807222 ->[10.99.159.133:41783|ea:ba:c8:b5:52:f9(test2.local.lan)]: connection shutting down due to error
: local "ea:ba:c8:b5:52:f9(test2.local.lan)" and remote "ea:ba:c8:b5:52:f9(test4.local.lan)" peer names collision
INFO: 2017/11/09 17:41:06.891905 ->[10.99.159.133:6783] attempting connection
INFO: 2017/11/09 17:41:06.892141 ->[10.99.159.135:6783] attempting connection
INFO: 2017/11/09 17:41:06.895306 ->[10.99.159.135:6783|ea:ba:c8:b5:52:f9(test2.local.lan)]: connection shutting down due to error:
 local "ea:ba:c8:b5:52:f9(test2.local.lan)" and remote "ea:ba:c8:b5:52:f9(test3.local.lan)" peer names collision
INFO: 2017/11/09 17:41:06.896793 ->[10.99.159.133:6783|ea:ba:c8:b5:52:f9(test2.local.lan)]: connection shutting down due to error:
 local "ea:ba:c8:b5:52:f9(test2.local.lan)" and remote "ea:ba:c8:b5:52:f9(test4.local.lan)" peer names collision
INFO: 2017/11/09 17:41:07.034099 ->[10.99.159.135:57308] connection accepted
INFO: 2017/11/09 17:41:07.037021 ->[10.99.159.135:57308|ea:ba:c8:b5:52:f9(test2.local.lan)]: connection shutting down due to error
: local "ea:ba:c8:b5:52:f9(test2.local.lan)" and remote "ea:ba:c8:b5:52:f9(test3.local.lan)" peer names collision
```

Checking `ifconfig | grep 52:f9` on each node I see:

```
root@test2:~/kontena-agent# ifconfig | grep 52:f9
weave     Link encap:Ethernet  HWaddr ea:ba:c8:b5:52:f9
root@test3:~/kontena-agent# ifconfig | grep f9
weave     Link encap:Ethernet  HWaddr ea:ba:c8:b5:52:f9
root@test4:~/kontena-agent# ifconfig | grep f9
weave     Link encap:Ethernet  HWaddr ea:ba:c8:b5:52:f9
```

So the weave interfaces all have the exact same MAC address.. Is that normal? I was using tmux synchronized panes so thought it could be a timing issue so I repeated all of the above steps making sure that the weave interface was removed after reboot and then started each agent waiting in between and they still all got the same MAC address.. How do I fix this?

----

The firewall rules I am intending to add are only:

```
-N DOCKER-HOST-kontena
-A DOCKER-HOST-kontena -s 10.99.0.0/20 -j RETURN  # private IPs
-A DOCKER-HOST-kontena -s 99.99.0.0/20 -j RETURN  # public IPs
-A DOCKER-HOST-kontena -j REJECT

-I INPUT -i bond0 -p tcp -m tcp --dport 6783:6784 -j DOCKER-HOST-kontena
-I INPUT -i bond0 -p udp -m udp --dport 6783:6784 -j DOCKER-HOST-kontena
```

Since the firewall default policies are ACCEPT adding these rules should not break esp packets, correct? Do you see any issues with adding these rules? Also, for better security are there some rules I should add to block unauthorized ESP packets?

**Comment by colinmollenhour** [comment]
Ok so researching further I see that /etc/machine-id is identical on the nodes.. I changed two of these and am trying to get it all working again but it is one issue after another..

**Comment by colinmollenhour** [comment]
On the subject of firewalls, since nodes connect to the master before they connect to each-other, couldn't the agent automatically add firewall rules such that the nodes are only exposed to each-other? That is:

- New node connects, master now knows node's public and private IP address.
- Master notifies other nodes of new node IP address, agents update firewalls to allow new node.
- Once new node is connected, it adds it's own firewall rules to block traffic not coming from the other nodes.

This is basically what I'm trying to accomplish but I'm having to do it outside of the core using additional services and it seems everyone would benefit from this being either the default functionality or supported as an option.

**Comment by colinmollenhour** [comment]
Ok, so I actually seem to have everything working including the firewall rules. I don't know if it is blocking ESP packets so I'd love some guidance on how to handle those with iptables.

Suggestions for features/bug fixes if interested:

- I think the upgrade to weave caused the MAC addresses to no longer be unique due to my duplicate machine IDs (thanks, packet.net). Perhaps this could have been detected and warned ahead of time somehow?
- Have `kontena node ls` report if there are cluster problems.. Too many times it has taken me too long to realize there is some sort of issue with etcd/ipam/etc.  In this case I didn't suspect that issue because it was working before but I think it broke due to my recent upgrade or reboot and duplicate machine ids and not the firewall.
- Built-in firewall protection would be awesome!
- Some new command to give a detailed report on health issues.. looking for and trying to decipher ruby stack traces is not very helpful for people like me that don't know the internals well enough.
- Stack deploy command could use the above detailed health report to give errors before trying to deploy. E.g. "Warning: Etcd cluster is unhealthy on node-1. Deploy is likely to fail."

**Comment by SpComb** [comment]
Yes, this looks like an issue where the `iptables` rules themselves were fine, but weave was unhealthy - I'm guessing that `ping 10.81.0.X` was not working in this case, even before adding the `iptables` rules?

I definitely also agree that the error handling/reporting for these kind of situations needs to be improved, there's a wide variety of causes for this kind of breakage, and trying to diagnose the underlying problems from stack deploy errors like `Celluloid::DeadActorError: attempted to call a dead actor: network_ready?` is hard. Better diagnostics for these kinds of issues is exactly the underlying motivation for the WIP agent refactoring in #2582 and the related `Kontena::Observable` mechanism in  #2704, but that's stalled because of other work on 1.4. 

#2062 is the general issue for the concept of actively monitored "node health", which is a broad topic that covers everything from not having the server schedule instances onto unhealthy nodes to trying to report some kind of more useful errors for stack deploys. I definitely agree that the agent should be aware of things like weave errors, and it should be able to report some kind of human-readable error for diagnostics in that situation.

There is the `kontena etcd health` command that actively queries each etcd node, and that will also reveal `10.81.0.X` connectivity problems. In 1.4 the `kontena node health` will also show that information. But agreed that users are unlikely to know to run those commands, and turning to `kontena node ls` for diagnostics currently only really shows the agent websocket connection state. Explicitly querying the health of all nodes synchronously is too slow for `kontena node ls`, we need the agent to be actively reporting it...

---

Re the underlying issue with the weave node identity conflicts, there's a history of similar issues on various providers, but that used to be about machines with hardcoded/cloned `/sys/class/dmi/id/product_uuid`:

* https://github.com/weaveworks/weave/issues/2427
* https://github.com/kontena/kontena/issues/1541

I think this it first time I've heard of duplicate `/etc/machine-id` on packet.net nodes? Sounds like something that would be worth reporting...

**Comment by colinmollenhour** [comment]
Thanks for all the great feedback!

I've got the firewall running on production now with no issues, although I still don't fully understand what went wrong on my test cluster. I'm a little worried about what would happen if such an issue happened on production because the only way I got it all working again was to completely remove all docker containers and kontena-related volumes on all nodes and bring them back up one at a time. I think my etcd cluster somehow got corrupted on one of the other grids that didn't have hte duplicate machine-id issue so that wasn't the only problem. Resetting is both slow and error-prone so it would be great if there was some sort of command to "reset" etcd when it blows up.. What is the simplest way to do this? I was doing something like:

```
$ docker-compose down (removes kontena-agent)
$ docker stop kontena-etcd kontena-ipam-plugin kontena-cadvisor weave
$ docker rm kontena-etcd kontena-ipam-plugin kontena-cadvisor weave
$ docker volume prune
$ docker-compose up -d
```

Is there a faster or less-destructive way?

The packet.net nodes are over a year old so I assume they've fixed the duplicate machine-id issue by now although I think I'll add resetting the machine-id to my node provisioning script to be safe.

Lastly, would you answer this question, please?

> Also, for better security are there some rules I should add to block unauthorized ESP packets?
