### ISSUE TITLE
Agent RPC request timeouts on a server RpcServer actor crash

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3035]
Simulating an unhandled exception in the server [`RpcServer`](https://github.com/kontena/kontena/blob/v1.4.0/server/app/services/rpc_server.rb), the actor will crash:

```
E, [2017-11-13T13:13:10.806116 #17] ERROR -- : Actor crashed!
RuntimeError: oops
	/app/app/services/rpc_server.rb:88:in `handle_notification'
	/app/app/services/rpc_server.rb:45:in `process!'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

If the `RpcServer` actor crashes, it does not get supervised, because it is spawned in the `WebsocketBackend` middleware without `supervise`: https://github.com/kontena/kontena/blob/b9428ffc718da5427d6356705e830b127269bc6c/server/app/middlewares/websocket_backend.rb#L41-L42

The server worker with the crashed `RpcServer` actor will behave badly: agents connected to that worker will still remain connected, and even things like `kontena node health` will work, because the server -> agent RPC `/etcd/health` requests do not pass through the `RpcServer` actor. However, any RPC requests from the agent will just get stuck in the [`@queue`](https://github.com/kontena/kontena/blob/v1.4.0/server/app/middlewares/websocket_backend.rb#L295) because the actor is no longer processing them... that shows up as RPC timeouts on the agent:

```
W, [2017-11-13T13:18:50.498394 #1]  WARN -- Kontena::RpcClient: observe timeout 30.00s: Kontena::RpcClient::RequestObservable</node_service_pods/list@203381531>? (Kontena::RpcClient::TimeoutError)
/app/lib/kontena/rpc_client.rb:77:in `rescue in request'
/app/lib/kontena/rpc_client.rb:74:in `request'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

One possible crash cause for the server `RpcServer` actor is the mongo [`Grid.find(...)`](https://github.com/kontena/kontena/blob/v1.4.0/server/app/services/rpc_server.rb#L106) query used to initialize the RPC handlers.

**Comment by SpComb** [comment]
This is specific to the server worker process... restarting the `kontena-agent` may appear to fix the problem if the agent connects to a different server worker process with a healthy `RpcServer` actor.

Looks like symptoms of this kind of broken server worker process on 1.4 include a node that's stuck in the `connecting` state, in case it reconnects to a broken server worker process... if it remains connected to the same worker process where the `RpcServer` actor crashed, that symptom won't show up

```
NAME        VERSION     STATUS          INITIAL   LABELS
⊛ core-01   1.4.0.dev   connecting 3m   1 / 1     region=test
⊛ core-02   1.4.0.dev   online 4m       -         region=test,test=label
```
