### ISSUE TITLE
Server Celluloid supervisor crash on fast actor crash-restart-crash loop

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3039]
See https://github.com/celluloid/celluloid-supervision/issues/28

If a supervised actor crashes early during startup (`initialize` -> `async.foo` -> `fail`), then it is possible for the supervising `Celluloid::Supervision::Container` to also [crash](https://github.com/celluloid/celluloid-supervision/blob/v0.20.5/lib/celluloid/supervision/container.rb#L118) with a race condition: `RuntimeError: a container instance went missing. This shouldn't be!`

This supervisor crash causes any remaining actors supervised by that supervision container to also be terminated. This is a very similar issue to https://github.com/kontena/kontena/issues/2733#issuecomment-335462866, where the server is missing functionality equivalent to  [`Celluloid::Supervision::Container.run`](https://github.com/celluloid/celluloid-supervision/blob/v0.20.5/lib/celluloid/supervision/container.rb#L48) that would react to the supervision container crashes.

---

Testing with a supervised `RpcServer` actor that's rigged to crash on any `/*/stat` notifications:

```
D, [2017-11-13T16:59:56.730709 #20] DEBUG -- RpcServer: notification handler="containers" method="stat"
E, [2017-11-13T16:59:56.730907 #20] ERROR -- : Actor crashed!
RuntimeError: oops
	/app/app/services/rpc_server.rb:96:in `handle_notification'
	/app/app/services/rpc_server.rb:53:in `process!'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
D, [2017-11-13T16:59:56.733422 #20] DEBUG -- RpcServer: notification handler="containers" method="stat"
E, [2017-11-13T16:59:56.734641 #20] ERROR -- : Actor crashed!
RuntimeError: oops
	/app/app/services/rpc_server.rb:96:in `handle_notification'
	/app/app/services/rpc_server.rb:53:in `process!'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
D, [2017-11-13T16:59:56.735541 #20] DEBUG -- RpcServer: notification handler="containers" method="stat"
E, [2017-11-13T16:59:56.735663 #20] ERROR -- : Actor crashed!
RuntimeError: oops
	/app/app/services/rpc_server.rb:96:in `handle_notification'
	/app/app/services/rpc_server.rb:53:in `process!'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

These RPCs tend to come in bursts, so after about 5-10 such crashes, this fairly reliably triggers https://github.com/celluloid/celluloid-supervision/issues/28

```
E, [2017-11-13T16:59:56.736185 #20] ERROR -- : Error ( RuntimeError ) at start of supervised instance of RpcServer
E, [2017-11-13T16:59:56.736294 #20] ERROR -- : Actor crashed!
RuntimeError: a container instance went missing. This shouldn't be!
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/container.rb:118:in `restart_actor'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `block in call'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

As a result, any other supervised actors in the same supervision group also get shut down; in this hypothetical case, that would be the `MongoPubsub` actor (logged from a debugging `finalizer`):

```
I, [2017-11-13T16:59:56.736615 #20]  INFO -- MongoPubsub: terminated
```

The effects of this vary depending on what actor crashed on startup, and triggered which supervision container to crash... if it's an actor in the default supervision group, then that would will break the server because of `MongoPubsub` (see also #3038):

```
W, [2017-11-13T17:01:54.395513 #20]  WARN -- GridServiceInstanceDeployer: Failed t:
o deploy service instance development/null/redis-1 to node core-02: Celluloid::DeadActorError: attempted to call a dead actor: actors
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:9:in `method_missing'
/app/app/services/mongo_pubsub.rb:135:in `subscribe'
/app/app/services/rpc_client.rb:72:in `subscribe_to_response'
/app/app/services/rpc_client.rb:51:in `request'
/app/app/services/grid_service_instance_deployer.rb:138:in `notify_node'
/app/app/services/grid_service_instance_deployer.rb:103:in `deploy_service_instance'
/app/app/services/grid_service_instance_deployer.rb:58:in `ensure_service_instance'
/app/app/services/grid_service_instance_deployer.rb:29:in `deploy'
/app/app/services/grid_service_deployer.rb:116:in `block in deploy_service_instance'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

**Comment by SpComb** [comment]
Repro case, which requires a delayed crash because just crashing right in the first `initialize` during boot will propagate the exception up the main puma worker thread, so puma handles the crash:

```
diff --git a/server/app/services/mongo_pubsub.rb b/server/app/services/mongo_pubsub.rb
index 84a6b2b..e740fef 100644
--- a/server/app/services/mongo_pubsub.rb
+++ b/server/app/services/mongo_pubsub.rb
@@ -56,6 +56,7 @@ class MongoPubsub
     # The collection session is local to this Actor's thread
     @collection = model.collection
     @subscriptions = []
+    fail "asdf" if @@fail ||= false
     async.tail!
   end
 
@@ -100,6 +101,11 @@ class MongoPubsub
     @subscriptions.each do |subscription|
       subscription.queue_message(data.dup) if subscription.channel == channel
     end
+    if @@fail
+      fail "fail!"
+    else
+      @@fail = true
+    end
   end
 
   # Stop all subscribers
```

Fallout is that the celluloid supervisor seems to crash even without the restart loop triggering the `RuntimeError: a container instance went missing. This shouldn't be!` race?

```
I, [2017-11-20T12:29:18.207203 #8]  INFO -- WebsocketBackend: node core-01 agent version 1.4.0.dev connected at 2017-11-20 12:29:18 UTC, 0.02s ago
I, [2017-11-20T12:29:18.233681 #8]  INFO -- Agent::NodePlugger: Connected node development/core-01 at 2017-11-20 12:29:18 UTC
E, [2017-11-20T12:29:18.300036 #8] ERROR -- : Actor crashed!
RuntimeError: fail!
	/app/app/services/mongo_pubsub.rb:105:in `queue_message'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-11-20T12:29:18.302898 #8] ERROR -- : Actor crashed!
RuntimeError: asdf
	/app/app/services/mongo_pubsub.rb:59:in `initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-11-20T12:29:18.303001 #8] ERROR -- : Error ( RuntimeError ) at start of supervised instance of MongoPubsub
E, [2017-11-20T12:29:18.303968 #8] ERROR -- : Actor crashed!
RuntimeError: asdf
	/app/app/services/mongo_pubsub.rb:59:in `initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:207:in `new_link'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/container/instance.rb:34:in `start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/container/instance.rb:57:in `restart'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/container.rb:121:in `block in restart_actor'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/container.rb:121:in `restart_actor'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `block in call'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-11-20T12:29:18.328870 #8] ERROR -- RpcServer: Celluloid::DeadActorError: attempted to call a dead actor: nil?
E, [2017-11-20T12:29:18.402064 #8] ERROR -- RpcServer: Celluloid::DeadActorError: attempted to call a dead actor: nil?
E, [2017-11-20T12:29:18.439737 #8] ERROR -- RpcServer: Celluloid::DeadActorError: attempted to call a dead actor: nil?
E, [2017-11-20T12:29:18.890054 #8] ERROR -- RpcServer: Celluloid::DeadActorError: attempted to call a dead actor: nil?
E, [2017-11-20T12:29:19.109898 #8] ERROR -- RpcServer: Celluloid::DeadActorError: attempted to call a dead actor: nil?
```
