### ISSUE TITLE
cli: kontena external-registry ls -q gives exception when empty

### ISSUE THREAD

**Issue by matti** [kontena/kontena#3050]
```
$ kontena external-registry ls
NAME  USERNAME  EMAIL
```

```
$ kontena external-registry ls -q
 [error] NoMethodError : undefined method `map' for "name":String
```

```
E, [2017-11-16T11:00:44.252777 #75815] ERROR -- CLI: undefined method `map' for "name":String (NoMethodError)
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:72:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:35:in `generate_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/table_generator.rb:39:in `print_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/cli/external_registries/list_command.rb:20:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/lib/kontena/command.rb:213:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.4.0/bin/kontena:18:in `<top (required)>'
/opt/kontena/embedded/bin/kontena:23:in `load'
/opt/kontena/embedded/bin/kontena:23:in `<main>'
```

**Comment by SpComb** [comment]
Seems to only happen when empty, dunno why

```
$ bin/kontena external-registry ls -q
 [error] NoMethodError : undefined method `map' for "name":String
Did you mean?  tap
         See /home/kontena/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
$ bin/kontena external-registry add -u test -e test@test -p 'test' images.example.com
 [done] Adding https://images.example.com to external registries      
$ bin/kontena external-registry ls -q
images.example.com
```

```
NoMethodError: undefined method `map' for "name":String
Did you mean?  tap
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:72:in `render'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:35:in `generate_table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/table_generator.rb:39:in `print_table'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/external_registries/list_command.rb:20:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:19:in `<top (required)>'
```

**Comment by kke** [comment]
I guess it never calls the `fields` if `data.empty?`
