### ISSUE TITLE
e2e spec failures with unexpected `stty: standard input` CLI output

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3058]
Several e2e specs involving `kontena * list` commands (using `tty-table` -> `tty-screen`?) are failing when run in the Vagrant/docker-compose e2e spec environment:

```
  1) complete master names for master use
     Failure/Error: expect(rows).to include master_name unless master_name == current_master_name
       expected [] to include "stty: standard input"
     # ./spec/features/completer/completer_spec.rb:63:in `block (4 levels) in <top (required)>'
     # ./spec/features/completer/completer_spec.rb:62:in `each'
     # ./spec/features/completer/completer_spec.rb:62:in `block (3 levels) in <top (required)>'

  2) complete master names can complete master names for master rm
     Failure/Error: expect(rows).to include master_name
       expected ["compose-e2e"] to include "stty: standard input"
     # ./spec/features/completer/completer_spec.rb:72:in `block (4 levels) in <top (required)>'
     # ./spec/features/completer/completer_spec.rb:71:in `each'
     # ./spec/features/completer/completer_spec.rb:71:in `block (3 levels) in <top (required)>'

  3) complete master queries with current master set can complete node names
     Failure/Error: expect(rows).to include node_name
       expected ["localhost"] to include "stty: standard input"
     # ./spec/features/completer/completer_spec.rb:98:in `block (5 levels) in <top (required)>'
     # ./spec/features/completer/completer_spec.rb:97:in `each'
     # ./spec/features/completer/completer_spec.rb:97:in `block (4 levels) in <top (required)>'

  4) external-registry ls when not empty returns a list
     Failure/Error: expect(k.out.lines.first).to match(/NAME/)
     
       expected "stty: standard input\r\n" to match /NAME/
       Diff:
       @@ -1,2 +1,2 @@
       -/NAME/
       +stty: standard input
       
     # ./spec/features/external_registry/list_spec.rb:33:in `block (3 levels) in <top (required)>'

  5) external-registry ls when not empty -q outputs the registry name
     Failure/Error: expect(k.out.strip).to eq 'registry.domain.com'
     
       expected: "registry.domain.com"
            got: "stty: standard input\r\nregistry.domain.com"
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,3 @@
       +stty: standard input
        registry.domain.com
       
     # ./spec/features/external_registry/list_spec.rb:44:in `block (4 levels) in <top (required)>'

  22) volume list --quiet lists volume names
      Failure/Error: expect(k.out.lines.sort.map(&:chomp)).to eq ["testVol", "testVol2"]
      
        expected: ["testVol", "testVol2"]
             got: ["stty: standard input", "testVol", "testVol2"]
      
        (compared using ==)
      # ./spec/features/volume/list_spec.rb:27:in `block (3 levels) in <top (required)>'

```

**Comment by SpComb** [comment]
Confirm that this is some combination of alpine Linux + rspec + kommando that's causing stty to output that to stderr:

```
  1) stty outputs size
     Failure/Error: expect(k.out).to match /\d+ \d+/
     
       expected "execve(\"/bin/stty\", [\"stty\", \"size\"], [/* 24 vars */]) = 0\r\narch_prctl(ARCH_SET_FS, 0x7f5b92...andard input\r\n)  = 21\r\nexit_group(0)                           = ?\r\n+++ exited with 0 +++\r\n" to match /\d+ \d+/
       Diff:
       @@ -1,2 +1,13 @@
       -/\d+ \d+/
       +execve("/bin/stty", ["stty", "size"], [/* 24 vars */]) = 0
       +arch_prctl(ARCH_SET_FS, 0x7f5b927e8b48) = 0
       +set_tid_address(0x7f5b927e8b80)         = 29
       +mprotect(0x7f5b927e5000, 4096, PROT_READ) = 0
       +mprotect(0x55a34ec87000, 16384, PROT_READ) = 0
       +getuid()                                = 0
       +ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
       +ioctl(0, TIOCGWINSZ, {ws_row=0, ws_col=0, ws_xpixel=0, ws_ypixel=0}) = 0
       +write(2, "stty: standard input\n", 21stty: standard input
       +)  = 21
       +exit_group(0)                           = ?
       ++++ exited with 0 +++
       
     # ./spec/test.rb:4:in `block (2 levels) in <top (required)>'
```

## On Ubuntu 

This does not happen on Ubuntu Linux with glibc:

```
stty
execve("/bin/stty", ["stty", "size"], [/* 80 vars */]) = 0
brk(NULL)                               = 0x1148000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff2a181c000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=121962, ...}) = 0
mmap(NULL, 121962, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff2a17fe000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff2a122f000
mprotect(0x7ff2a13ef000, 2097152, PROT_NONE) = 0
mmap(0x7ff2a15ef000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7ff2a15ef000
mmap(0x7ff2a15f5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7ff2a15f5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff2a17fd000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff2a17fc000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff2a17fb000
arch_prctl(ARCH_SET_FS, 0x7ff2a17fc700) = 0
mprotect(0x7ff2a15ef000, 16384, PROT_READ) = 0
mprotect(0x610000, 4096, PROT_READ)     = 0
mprotect(0x7ff2a181e000, 4096, PROT_READ) = 0
munmap(0x7ff2a17fe000, 121962)          = 0
brk(NULL)                               = 0x1148000
brk(0x1169000)                          = 0x1169000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=4228896, ...}) = 0
mmap(NULL, 4228896, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff2a0e26000
close(3)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
read(3, "# Locale name alias data base.\n#"..., 4096) = 2995
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/usr/lib/locale/C.UTF-8/LC_MESSAGES", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=30, ...}) = 0
close(3)                                = 0
open("/usr/lib/locale/C.UTF-8/LC_MESSAGES/SYS_LC_MESSAGES", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=48, ...}) = 0
mmap(NULL, 48, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff2a181b000
close(3)                                = 0
open("/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=26258, ...}) = 0
mmap(NULL, 26258, PROT_READ, MAP_SHARED, 3, 0) = 0x7ff2a1814000
close(3)                                = 0
open("/usr/lib/locale/C.UTF-8/LC_COLLATE", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1514422, ...}) = 0
mmap(NULL, 1514422, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff2a1689000
close(3)                                = 0
open("/usr/lib/locale/C.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=158652, ...}) = 0
mmap(NULL, 158652, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff2a1662000
close(3)                                = 0
open("/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=619, ...}) = 0
mmap(NULL, 619, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff2a1813000
close(3)                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=0, ws_col=0, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=0, ws_col=0, ws_xpixel=0, ws_ypixel=0}) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 23), ...}) = 0
write(1, "0 0\n", 40 0
)                    = 4
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
  outputs size when run with kommando
```

**Comment by SpComb** [comment]
Reported as an issue in `tty-screen`, I think it should be suppressing the `stderr` output from `stty` in this case: https://github.com/piotrmurach/tty-screen/issues/6

**Comment by kke** [comment]
https://github.com/piotrmurach/tty-screen/issues/6 is solved so this should be fixable

**Comment by SpComb** [comment]
It only happens when running the specs in an `alpine` container, and I've stopped doing that for other reasons since.

Wouldn't hurt to update the CLI deps and then get this closed.
