### ISSUE TITLE
Kontena::NetworkAdapters::IpamError: 10.81.0.0 conflict: Create conflict with /kontena/ipam/subnets/10.81.0.0@10: Key already exists

### ISSUE THREAD

**Issue by jamo** [kontena/kontena#3063]
On a fresh node created with the web-ui.

```
I, [2017-11-20T09:30:12.063444 #1]  INFO -- Kontena::LoadBalancers::Registrator: fetching containers information
I, [2017-11-20T09:30:12.322157 #1]  INFO -- Kontena::Launchers::IpamPlugin: waited 3.4s of 300.0s until: IPAM running yielded Hash
I, [2017-11-20T09:30:12.323527 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network with subnet=10.81.0.0/16 iprange=10.81.128.0/17
I, [2017-11-20T09:30:12.330075 #1]  INFO -- Kontena::Workers::LogWorker: waited 8.4s of 300.0s until: etcd running yielded TrueClass
I, [2017-11-20T09:30:12.330235 #1]  INFO -- Kontena::Workers::LogWorker: start streaming logs from containers
E, [2017-11-20T09:30:12.347341 #1] ERROR -- : Actor crashed!
Kontena::NetworkAdapters::IpamError: 10.81.0.0 conflict: Create conflict with /kontena/ipam/subnets/10.81.0.0@10: Key already exists
	/app/lib/kontena/network_adapters/ipam_client.rb:117:in `handle_error_response'
	/app/lib/kontena/network_adapters/ipam_client.rb:47:in `rescue in reserve_pool'
	/app/lib/kontena/network_adapters/ipam_client.rb:34:in `reserve_pool'
	/app/lib/kontena/network_adapters/weave.rb:188:in `ensure_default_pool'
	/app/lib/kontena/network_adapters/weave.rb:154:in `on_ipam_start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

<details>

```
eff73f27f978        kontena/agent:latest        "/app/bin/kontena-age"   28 minutes ago      Up 28 minutes                           kontena-agent
core@hidden-snow-191 ~ $ docker logs eff73f27f978
I, [2017-11-20T09:29:38.680218 #1]  INFO -- Kontena::Agent: initializing agent (version 1.4.0)
I, [2017-11-20T09:29:38.684157 #1]  INFO -- Kontena::Observable::Registry: initialized
I, [2017-11-20T09:29:38.685770 #1]  INFO -- Kontena::Workers::NodeInfoWorker: initialized
I, [2017-11-20T09:29:38.687553 #1]  INFO -- Kontena::RpcClient: initialized
I, [2017-11-20T09:29:38.688603 #1]  INFO -- Kontena::WebsocketClient: initialized with node token 6b4732cf1..., node ID W5QY:3CBH:XDGM:2H5A:2Y33:WTFV:6DNK:G2O7:Y22A:NRAW:TJBD:IWOV
I, [2017-11-20T09:29:38.689939 #1]  INFO -- Kontena::Launchers::IpamPlugin: initialized
I, [2017-11-20T09:29:38.696060 #1]  INFO -- Kontena::NetworkAdapters::IpamCleaner: initialized
I, [2017-11-20T09:29:39.689098 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://misty-moon-5532.platforms.eu-west-1.kontena.cloud
W, [2017-11-20T09:29:40.097935 #1]  WARN -- Kontena::WebsocketClient: secure connection established without KONTENA_SSL_VERIFY=true: /CN=*.platforms.eu-west-1.kontena.cloud (issuer /C=US/O=Amazon/OU=Server CA 1B/CN=Amazon)
I, [2017-11-20T09:29:45.848955 #1]  INFO -- Kontena::Launchers::IpamPlugin: ipam image pulled: kontena/ipam-plugin:0.2.2
I, [2017-11-20T09:29:45.849917 #1]  INFO -- Kontena::Launchers::Cadvisor: initialized
I, [2017-11-20T09:29:45.851070 #1]  INFO -- Kontena::Launchers::Etcd: initialized
I, [2017-11-20T09:29:45.853376 #1]  INFO -- Kontena::NetworkAdapters::Weave: initialized
I, [2017-11-20T09:29:45.862925 #1]  INFO -- Kontena::Launchers::Cadvisor: pulling image google/cadvisor:v0.24.1
I, [2017-11-20T09:29:45.872162 #1]  INFO -- Kontena::NetworkAdapters::Weave: pulling weaveworks/weave:1.9.3
I, [2017-11-20T09:29:45.873807 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
I, [2017-11-20T09:29:45.878810 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
I, [2017-11-20T09:29:49.570231 #1]  INFO -- Kontena::Launchers::Cadvisor: starting cadvisor service
I, [2017-11-20T09:30:03.906703 #1]  INFO -- Kontena::NetworkAdapters::Weave: image weaveworks/weave:1.9.3 pulled
I, [2017-11-20T09:30:03.908805 #1]  INFO -- Kontena::LoadBalancers::Configurer: initialized
I, [2017-11-20T09:30:03.910861 #1]  INFO -- Kontena::LoadBalancers::Registrator: initialized
I, [2017-11-20T09:30:03.929977 #1]  INFO -- Kontena::Workers::LogWorker: initialized
I, [2017-11-20T09:30:03.933894 #1]  INFO -- Kontena::Workers::ContainerInfoWorker: initialized
I, [2017-11-20T09:30:03.944655 #1]  INFO -- Kontena::Workers::EventWorker: initialized
I, [2017-11-20T09:30:03.945543 #1]  INFO -- Kontena::Workers::EventWorker: started to stream docker container events
I, [2017-11-20T09:30:03.960119 #1]  INFO -- Kontena::Workers::NodeStatsWorker: initialized
I, [2017-11-20T09:30:03.962015 #1]  INFO -- Kontena::Workers::StatsWorker: initialized
I, [2017-11-20T09:30:03.969810 #1]  INFO -- Kontena::Workers::WeaveWorker: initialized
I, [2017-11-20T09:30:03.973565 #1]  INFO -- Kontena::Workers::ImageCleanupWorker: initialized
I, [2017-11-20T09:30:03.976559 #1]  INFO -- Kontena::Workers::HealthCheckWorker: initialized
I, [2017-11-20T09:30:03.977577 #1]  INFO -- Kontena::Workers::FluentdWorker: initialized
I, [2017-11-20T09:30:03.980171 #1]  INFO -- Kontena::Workers::ServicePodManager: populating service pod workers from docker
I, [2017-11-20T09:30:03.983573 #1]  INFO -- Kontena::Workers::Volumes::VolumeManager: syncing volumes from docker
I, [2017-11-20T09:30:07.129667 #1]  INFO -- Kontena::NetworkAdapters::Weave: attaching router
I, [2017-11-20T09:30:07.724127 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers 172.31.21.74
I, [2017-11-20T09:30:08.035061 #1]  INFO -- Kontena::NetworkAdapters::Weave: Exposed host node at cidr=10.81.0.1/16
I, [2017-11-20T09:30:08.358436 #1]  INFO -- Kontena::Launchers::IpamPlugin: network started, launching ipam...
I, [2017-11-20T09:30:08.359757 #1]  INFO -- Kontena::Workers::WeaveWorker: attaching network to existing containers
I, [2017-11-20T09:30:08.525926 #1]  INFO -- Kontena::Launchers::Etcd: etcd container does not exist
I, [2017-11-20T09:30:08.525970 #1]  INFO -- Kontena::Launchers::Etcd: checking if etcd previous membership needs to be updated
I, [2017-11-20T09:30:08.526066 #1]  INFO -- Kontena::Launchers::Etcd: connecting to existing etcd at http://10.81.0.3:2379/v2/members
I, [2017-11-20T09:30:08.886881 #1]  INFO -- Kontena::Launchers::IpamPlugin: started ipam-plugin service
I, [2017-11-20T09:30:11.614565 #1]  INFO -- Kontena::Launchers::Etcd: retrying next etcd host
I, [2017-11-20T09:30:11.614737 #1]  INFO -- Kontena::Launchers::Etcd: connecting to existing etcd at http://10.81.0.2:2379/v2/members
I, [2017-11-20T09:30:11.620015 #1]  INFO -- Kontena::Launchers::Etcd: starting etcd service as a cluster member with initial state: new
I, [2017-11-20T09:30:11.620100 #1]  INFO -- Kontena::Launchers::Etcd: cluster members: node-1=http://10.81.0.1:2380,node-2=http://10.81.0.2:2380,node-3=http://10.81.0.3:2380
I, [2017-11-20T09:30:11.843317 #1]  INFO -- Kontena::Launchers::Etcd: started etcd service
I, [2017-11-20T09:30:12.063444 #1]  INFO -- Kontena::LoadBalancers::Registrator: fetching containers information
I, [2017-11-20T09:30:12.322157 #1]  INFO -- Kontena::Launchers::IpamPlugin: waited 3.4s of 300.0s until: IPAM running yielded Hash
I, [2017-11-20T09:30:12.323527 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network with subnet=10.81.0.0/16 iprange=10.81.128.0/17
I, [2017-11-20T09:30:12.330075 #1]  INFO -- Kontena::Workers::LogWorker: waited 8.4s of 300.0s until: etcd running yielded TrueClass
I, [2017-11-20T09:30:12.330235 #1]  INFO -- Kontena::Workers::LogWorker: start streaming logs from containers
E, [2017-11-20T09:30:12.347341 #1] ERROR -- : Actor crashed!
Kontena::NetworkAdapters::IpamError: 10.81.0.0 conflict: Create conflict with /kontena/ipam/subnets/10.81.0.0@10: Key already exists
	/app/lib/kontena/network_adapters/ipam_client.rb:117:in `handle_error_response'
	/app/lib/kontena/network_adapters/ipam_client.rb:47:in `rescue in reserve_pool'
	/app/lib/kontena/network_adapters/ipam_client.rb:34:in `reserve_pool'
	/app/lib/kontena/network_adapters/weave.rb:188:in `ensure_default_pool'
	/app/lib/kontena/network_adapters/weave.rb:154:in `on_ipam_start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2017-11-20T09:30:12.353685 #1]  INFO -- Kontena::NetworkAdapters::Weave: initialized
I, [2017-11-20T09:30:12.364162 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
I, [2017-11-20T09:30:12.367287 #1]  INFO -- Kontena::NetworkAdapters::WeaveExecutor: initialized
I, [2017-11-20T09:30:12.621998 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers 172.31.21.74
I, [2017-11-20T09:30:12.847777 #1]  INFO -- Kontena::NetworkAdapters::Weave: Exposed host node at cidr=10.81.0.1/16
I, [2017-11-20T09:30:13.031017 #1]  INFO -- Kontena::Launchers::IpamPlugin: network started, launching ipam...
I, [2017-11-20T09:30:13.031757 #1]  INFO -- Kontena::Workers::WeaveWorker: attaching network to existing containers
I, [2017-11-20T09:30:13.047034 #1]  INFO -- Kontena::Launchers::IpamPlugin: ipam-plugin is already running
I, [2017-11-20T09:30:13.050917 #1]  INFO -- Kontena::Launchers::Etcd: etcd is already running
I, [2017-11-20T09:30:13.097445 #1]  INFO -- Kontena::NetworkAdapters::Weave: network and ipam ready, ensuring default network with subnet=10.81.0.0/16 iprange=10.81.128.0/17
I, [2017-11-20T09:57:21.136646 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating hidden-snow-191-shell-6474-1
I, [2017-11-20T09:57:21.136779 #1]  INFO -- Kontena::ServicePods::Creator: creating service: hidden-snow-191-shell-6474-1
I, [2017-11-20T09:57:21.137930 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/nsenter:latest
I, [2017-11-20T09:57:23.088558 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/nsenter:latest
I, [2017-11-20T09:57:23.252514 #1]  INFO -- Kontena::NetworkAdapters::Weave: Create container=hidden-snow-191-shell-6474-1 in network=kontena with overlay_cidr=10.81.128.76/16
I, [2017-11-20T09:57:23.469966 #1]  INFO -- Kontena::ServicePods::Creator: service started: hidden-snow-191-shell-6474-1
I, [2017-11-20T09:57:23.517861 #1]  INFO -- Kontena::NetworkAdapters::Weave: Attach container=c3d3163d795f5d0aa3b4a6d19045651d11a4a9b376834d48b9995f52589e3534 at cidr=10.81.128.76/16
I, [2017-11-20T09:57:24.671295 #1]  INFO -- Kontena::Actors::ContainerExec: initialized (session 7de5151f-e404-4ed3-9a21-b6f08b8728a7)
I, [2017-11-20T09:57:24.780994 #1]  INFO -- Kontena::Actors::ContainerExec: starting command: ["/bin/sh", "-c", "nsenter --target 1 --mount --uts --net --pid -- su  - core"] (tty: true, stdin: true)
I, [2017-11-20T09:57:24.885008 #1]  INFO -- Kontena::Actors::ContainerExec: tty resized to 151x44
I, [2017-11-20T09:57:54.407180 #1]  INFO -- Kontena::Actors::ContainerExec: ["/bin/sh", "-c", "nsenter --target 1 --mount --uts --net --pid -- su  - core"] exit with code 0: ["/bin/sh", "-c", "nsenter --target 1 --mount --uts --net --pid -- su  - core"]
I, [2017-11-20T09:57:54.858907 #1]  INFO -- Kontena::Workers::ServicePodWorker: terminating hidden-snow-191-shell-6474-1
I, [2017-11-20T09:57:54.866591 #1]  INFO -- Kontena::ServicePods::Terminator: terminating service: /hidden-snow-191-shell-6474-1
I, [2017-11-20T09:57:55.150677 #1]  INFO -- Kontena::NetworkAdapters::Weave: Remove container=c3d3163d795f5d0aa3b4a6d19045651d11a4a9b376834d48b9995f52589e3534 from network=kontena at cidr=10.81.128.76/16
I, [2017-11-20T09:57:58.900226 #1]  INFO -- Kontena::Workers::ServicePodWorker: creating hidden-snow-191-shell-5497-1
I, [2017-11-20T09:57:58.900372 #1]  INFO -- Kontena::ServicePods::Creator: creating service: hidden-snow-191-shell-5497-1
I, [2017-11-20T09:57:58.901615 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/nsenter:latest
I, [2017-11-20T09:58:00.026985 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/nsenter:latest
I, [2017-11-20T09:58:00.080276 #1]  INFO -- Kontena::NetworkAdapters::Weave: Create container=hidden-snow-191-shell-5497-1 in network=kontena with overlay_cidr=10.81.128.74/16
I, [2017-11-20T09:58:00.284887 #1]  INFO -- Kontena::ServicePods::Creator: service started: hidden-snow-191-shell-5497-1
I, [2017-11-20T09:58:00.334251 #1]  INFO -- Kontena::NetworkAdapters::Weave: Attach container=a5087302aa55ca13363b34d16d4779384bc6cc309e05890f48f8b93373009976 at cidr=10.81.128.74/16
I, [2017-11-20T09:58:02.313099 #1]  INFO -- Kontena::Actors::ContainerExec: initialized (session 77afc1f1-8672-491c-902c-ea06313b51ce)
I, [2017-11-20T09:58:02.406366 #1]  INFO -- Kontena::Actors::ContainerExec: starting command: ["/bin/sh", "-c", "nsenter --target 1 --mount --uts --net --pid -- su  - core"] (tty: true, stdin: true)
I, [2017-11-20T09:58:02.499346 #1]  INFO -- Kontena::Actors::ContainerExec: tty resized to 151x44
```
 
</details>

**Comment by jamo** [comment]
We can see this only on 1/3 of nodes created.

**Comment by SpComb** [comment]
I assume this happens when creating a new platform with multiple nodes, and not when creating a single-node platform or if adding new nodes to an existing platform one by one? This looks like missing retry-on-conflict handling in the `kontena-ipam`, but based on the logs, it looks like the agent was able to recover from the resulting `Kontena::NetworkAdapters::Weave` actor crash? Did you notice any actual side-effects in terms of deployment timeouts/errors?

In terms of the `kontena-ipam` it sounds like a relatively harmless race with multiple nodes concurrently requesting the `kontena` network address pool. The IPAM is supposed to handle those conflicts, but it looks like that only happens for the `/kontena/ipam/pools/...` nodes and dynamic `/kontena/ipam/subnets/...` allocations, but not static `/kontena/ipam/subnets/...` allocations, which is a bug: https://github.com/kontena/kontena-ipam/issues/77

**Comment by jamo** [comment]
It indeed happened on 1/3 nodes where initial size was 3. Created via kontena cloud.

Seems that the node was able to recover from the error; we were inspecting the logs just for the sake of looking at the logs,  while we spotted this one.

Just wanted to report it in case there was more to it...

**Comment by SpComb** [comment]
Yeah, it's an issue that should be fixed, but if the agent was able to recover from it without any side-effects, and it's a relatively rare race-condition, then it's not very high-priority.

In the end it's just a question of whether the retry happens at the `kontena-ipam` or the `kontena-agent` level of the stack... the `kontena-ipam` is simpler and would be much less prone to any side-effects when recovering from this conflict.
