### ISSUE TITLE
Agent: shutdown deadlock on LogWorker exclusive sleep affects automatic agent version upgrades

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3067]
There is a deadlock in the `kontena-agent` 1.4.0 `Agent.shutdown` logic used to handle automatic agent version upgrades, which means that the agent will keep reconnecting to the server instead of shutting down. It seems like the agent will eventually shutdown once a 300s timeout expires, which should allow it to get re-started with the new version?

The effective deadlock is in `Kontena::WebsocketClient#on_close` => `Kontena::Agent.shutdown` => `Kontena::Workers::LogWorker#terminate` => `Kontena::Launchers::Etcd#running?`, because the `LogWorker` will be stuck in an exclusive sleep waiting for etcd actor to be ready, which will not happen until the websocket is connected and the server sends the node info.

It looks like this was introduced in #2728 for 1.4.0, because it wrapped the entire `LogWorker#start` method in `exclusive { ... }`, including the[ `wait_until!("etcd running") { Actor[:etcd_launcher].running? }`](https://github.com/kontena/kontena/blob/98dacbfc75006e73c361d94210ba1377e7da9302/agent/lib/kontena/workers/log_worker.rb#L78). It looks like `exclusive { sleep }` will also block actor termination, causing the `@supervisor.shutdown` to block.

---

[Tracing `Celluloid.shutdown`](https://gist.github.com/SpComb/1700fd30fca8f8f90bd52d5217c5c777), this exclusive sleep prevents `Kontena::Agent.shutdown` from completing if the etcd launcher is not yet running:

```
I, [2017-11-21T12:54:50.071965 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
I, [2017-11-21T12:54:50.099709 #1]  INFO -- Kontena::WebsocketClient: unsecure connection established without SSL
D, [2017-11-21T12:54:50.113744 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::AgentApi#master_info [{"version"=>"1.4.0.dev"}]
D, [2017-11-21T12:54:50.117461 #1] DEBUG -- Kontena::WebsocketClient: Server closed connection with code 4010: agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
E, [2017-11-21T12:54:50.117534 #1] ERROR -- Kontena::WebsocketClient: master does not accept our version (1.5.0.dev): agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
I, [2017-11-21T12:54:50.117602 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T12:54:50.117645 #1]  INFO -- Kontena::Agent: Shutting down...
TERMINATE Kontena::Workers::Volumes::VolumeManager @ /app/lib/celluloid/shutdown_tracer.rb:4:in `terminate'
JOIN #<Celluloid::Proxy::Actor(23a72b2b-b124-490a-8b2a-000000020016) alive>... @ /app/lib/celluloid/shutdown_tracer.rb:24:in `join'
....
TERMINATE Kontena::Workers::LogWorker @ /app/lib/celluloid/shutdown_tracer.rb:4:in `terminate'
JOIN #<Celluloid::Proxy::Actor(23a72b2b-b124-490a-8b2a-00000002000c) alive>... @ /app/lib/celluloid/shutdown_tracer.rb:24:in `join'
D, [2017-11-21T13:17:04.240718 #1] DEBUG -- Kontena::Workers::LogWorker: waiting 1.0s of 300.0s until: etcd running
```

Depending on the exact ordering of how the supervised actors are shut down (not sure if deterministic or not?), this means that the agent will actually keep reconnecting instead of shutting down:

```
I, [2017-11-21T13:17:04.722431 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
I, [2017-11-21T13:17:04.741880 #1]  INFO -- Kontena::WebsocketClient: unsecure connection established without SSL
D, [2017-11-21T13:17:04.743424 #1] DEBUG -- Kontena::Workers::LogWorker: waiting 1.5s of 300.0s until: etcd running
D, [2017-11-21T13:17:04.746609 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::AgentApi#master_info [{"version"=>"1.4.0.dev"}]
D, [2017-11-21T13:17:04.747783 #1] DEBUG -- Kontena::WebsocketClient: Server closed connection with code 4010: agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
E, [2017-11-21T13:17:04.748006 #1] ERROR -- Kontena::WebsocketClient: master does not accept our version (1.5.0.dev): agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
I, [2017-11-21T13:17:04.748619 #1]  INFO -- Kontena::WebsocketClient: reconnect attempt 1 in 0.65s...
I, [2017-11-21T13:17:05.403846 #1]  INFO -- Kontena::WebsocketClient: connecting to master at ws://192.168.66.1:9292
I, [2017-11-21T13:17:05.421485 #1]  INFO -- Kontena::WebsocketClient: unsecure connection established without SSL
D, [2017-11-21T13:17:05.429609 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::AgentApi#master_info [{"version"=>"1.4.0.dev"}]
D, [2017-11-21T13:17:05.432411 #1] DEBUG -- Kontena::WebsocketClient: Server closed connection with code 4010: agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
E, [2017-11-21T13:17:05.432640 #1] ERROR -- Kontena::WebsocketClient: master does not accept our version (1.5.0.dev): agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
I, [2017-11-21T13:17:05.433248 #1]  INFO -- Kontena::WebsocketClient: reconnect attempt 1 in 0.61s...
D, [2017-11-21T13:17:05.748214 #1] DEBUG -- Kontena::Workers::LogWorker: waiting 2.5s of 300.0s until: etcd running
```

This continues until the `LogWorker#start` `wait_until` eventually times out and crashes the actor:

```
E, [2017-11-21T13:21:19.560751 #1] ERROR -- Kontena::WebsocketClient: master does not accept our version (1.5.0.dev): agent version 1.5.0.dev is not compatible with server version 1.4.0.dev
I, [2017-11-21T13:21:19.560977 #1]  INFO -- Kontena::WebsocketClient: reconnect attempt 1 in 0.41s...
D, [2017-11-21T13:21:19.840345 #1] DEBUG -- Kontena::Workers::LogWorker: waiting 256.6s of 300.0s until: etcd running
...
W, [2017-11-21T13:22:03.810677 #1]  WARN -- Kontena::Workers::LogWorker: timeout after waiting 300.1s of 300.0s until: etcd running
E, [2017-11-21T13:22:03.811809 #1] ERROR -- : Actor crashed!
Timeout::Error: Timeout after waiting 300.0s until: etcd running
	/app/lib/kontena/helpers/wait_helper.rb:66:in `wait_until!'
	/app/lib/kontena/workers/log_worker.rb:78:in `block in start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/log_worker.rb:77:in `start'
	/app/lib/kontena/workers/log_worker.rb:105:in `on_connect'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

Which allows the `@supervisor.shutdown` to complete:

```
TERMINATE Kontena::Workers::NodeInfoWorker @ /app/lib/celluloid/shutdown_tracer.rb:4:in `terminate'
JOIN #<Celluloid::Proxy::Actor(23a72b2b-b124-490a-8b2a-000000020001) alive>... @ /app/lib/celluloid/shutdown_tracer.rb:24:in `join'
E, [2017-11-21T13:22:08.920108 #1] ERROR -- Kontena::Workers::NodeInfoWorker: publish_node_info: undefined method `request' for nil:NilClass
W, [2017-11-21T13:22:08.941160 #1]  WARN -- Kontena::Observable::Registry: crashing observables owned by actor Kontena::Workers::NodeInfoWorker: Actor terminated
D, [2017-11-21T13:22:08.943099 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: crash: Actor terminated

D, [2017-11-21T13:22:08.943262 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: dead: Kontena::Observer<Kontena::NetworkAdapters::Weave>
D, [2017-11-21T13:22:08.945885 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: dead: Kontena::Observer<Kontena::Workers::NodeStatsWorker>
D, [2017-11-21T13:22:08.946100 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: dead: Kontena::Observer<Kontena::Workers::StatsWorker>
D, [2017-11-21T13:22:08.946192 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: dead: Kontena::Observer<Kontena::Workers::FluentdWorker>
D, [2017-11-21T13:22:08.946270 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: dead: Kontena::Observer<Kontena::Workers::ServicePodManager>
D, [2017-11-21T13:22:08.946343 #1] DEBUG -- Kontena::Observable<Kontena::Workers::NodeInfoWorker>: dead: Kontena::Observer<Kontena::Workers::Volumes::VolumeManager>
I, [2017-11-21T13:22:08.951174 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:08.951297 #1]  INFO -- Kontena::Agent: Shutting down...
I, [2017-11-21T13:22:08.951622 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:08.951690 #1]  INFO -- Kontena::Agent: Shutting down...
I, [2017-11-21T13:22:08.951898 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:08.951961 #1]  INFO -- Kontena::Agent: Shutting down...
I, [2017-11-21T13:22:08.952228 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:08.952301 #1]  INFO -- Kontena::Agent: Shutting down...
I, [2017-11-21T13:22:08.952495 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:08.952554 #1]  INFO -- Kontena::Agent: Shutting down...
....
I, [2017-11-21T13:22:09.112549 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:09.112592 #1]  INFO -- Kontena::Agent: Shutting down...
I, [2017-11-21T13:22:09.112721 #1]  INFO -- Kontena::Agent: Got signal shutdown
I, [2017-11-21T13:22:09.112764 #1]  INFO -- Kontena::Agent: Shutting down...
TERMINATE! Celluloid::Supervision::Service::Root @ /app/lib/celluloid/shutdown_tracer.rb:8:in `terminate!'
```

**Comment by SpComb** [comment]
There's also a minor bug in the agent `WebsocketClient` in that it will still attempt to reconnect if it gets a `close` message and decides to shut down, but I don't think that would actually cause any issues apart from looking silly in the logging.

Normally the `Kontena::Agent.shutdown` would terminate the `WebsocketClient` actor fast enough that it won't have a chance to reconnect, but that's a timing race because the shutdown can stall before the `WebsocketClient` actor gets terminated...

**Comment by SpComb** [comment]
A `SIGINT` will also break the deadlock, because that invokes the `Celluloid.shutdown` handler, which terminates all actors in parallel using `terminate!`, which allows the `LogWorker` actor to also crash because the `Etcd` actor terminates:

```
E, [2017-11-21T13:42:02.471066 #1] ERROR -- : Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor: running?
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:9:in `method_missing'
	/app/lib/kontena/workers/log_worker.rb:78:in `block (2 levels) in start'
	/app/lib/kontena/helpers/wait_helper.rb:33:in `block in wait_until'
	/app/lib/kontena/helpers/wait_helper.rb:32:in `loop'
	/app/lib/kontena/helpers/wait_helper.rb:32:in `wait_until'
	/app/lib/kontena/helpers/wait_helper.rb:63:in `wait_until!'
	/app/lib/kontena/workers/log_worker.rb:78:in `block in start'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:97:in `exclusive'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid.rb:421:in `exclusive'
	/app/lib/kontena/workers/log_worker.rb:77:in `start'
	/app/lib/kontena/workers/log_worker.rb:105:in `on_connect'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

Maybe the `Kontena::Agent.shutdown` should use `Celluloid.shutdown` instead of `@supervisor.shutdown`?
