### ISSUE TITLE
e2e spec: stack validate keywords entrypoint sets stack entrypoint

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3118]
Probably broken by the #2887 fix... the spec was written against the 1.4 api-yaml style output.

Spec should be fixed to use `--format api-json` and pick up the entrypoint from the extended docker-compose file.

```
  20) stack validate keywords entrypoint sets stack entrypoint
      Failure/Error: expect(k.out).to match(/entrypoint.+?foo.+?entrypoint.+?foo2/m)
      
        expected "---\r\n# /kontena/test/spec/fixtures/stack/keywords/entrypoint.yml\r\nstack: test/simple\r\nversion:...docker-compose-entrypoint.yml\r\n      service: redis\r\n    environment: []\r\n    secrets: []\r\n" to match /entrypoint.+?foo.+?entrypoint.+?foo2/m
        Diff:
        @@ -1,2 +1,15 @@
        -/entrypoint.+?foo.+?entrypoint.+?foo2/m
        +---
        +# /kontena/test/spec/fixtures/stack/keywords/entrypoint.yml
        +stack: test/simple
        +version: 0.1.0
        +services:
        +  redis:
        +    image: redis:3-alpine
        +    entrypoint: foo
        +  redis2:
        +    extends:
        +      file: docker-compose-entrypoint.yml
        +      service: redis
        +    environment: []
        +    secrets: []
        
      # ./spec/features/stack/validate_spec.rb:8:in `block (5 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/validate_spec.rb:5:in `block (4 levels) in <top (required)>'
```

**Comment by SpComb** [comment]
Confirm that `kontena stack validate --format api-json` does correctly pick up the `{"entrypoint": "foo2"}` from the extended `docker-compose-entrypoint.yml` file, so this should just be a spec issue, not an actual CLI bug.
