### ISSUE TITLE
Unable to request a certificate

### ISSUE THREAD

**Issue by mlaitinen** [kontena/kontena#3122]
I authorized my domain with 
```
kontena certificate authorize --type tls-sni-01 --linked-service <my load balancer service> <my virtualhost>
``` 
and tried to request a certificate with 
```
kontena certificate request <my virtualhost>
```
but got the following error message:

```
 [fail] Requesting certificate for <my virtualhost>      
 [error] 422 : Unprocessable Entity:
	challenge: Connection refused
```

With the debug flag:
```
DEBUG Kontena CLI 1.4.2 (ruby-2.3.3+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-cloud from /home/miku/.kontena/gems/2.3.3/gems/kontena-plugin-cloud-1.2.0/lib/kontena_cli_plugin.rb
DEBUG Loading plugin kontena-plugin-upcloud from /home/miku/.kontena/gems/2.3.3/gems/kontena-plugin-upcloud-0.3.1/lib/kontena_cli_plugin.rb
DEBUG Running Kontena::MainCommand with ["certificate", "request", "-D", "<my virtualhost>"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::CertificateCommand with ["request", "-D", "<my virtualhost>"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::Certificate::RequestCommand with ["-D", "<my virtualhost>"] -- callback matcher = 'certificate request'
DEBUG Loading configuration from /home/miku/.kontena_client.json
DEBUG Configuration loaded with 2 servers and 2 accounts.
DEBUG Current master: <my master>
DEBUG Current grid: <my grid>
DEBUG Current account: kontena
    *   Requesting certificate for <my virtualhost>  .. \DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>nil, :ssl_verify_peer_host=>nil}
DEBUG [Request]: POST https://xxx.kontena.cloud/v1/grids/<my grid>/certificates (ssl_verify: true)  | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: "{\"domains\":[\"<my virtualhost>\"]}"
    *   Requesting certificate for <my virtualhost>  .. -DEBUG [Error]: Expected([200, 201, 204]) <=> Actual(422 Unprocessable Entity)

DEBUG Request POST /v1/grids/<my grid>/certificates: 422 Unprocessable Entity: {"error":{"challenge":"Connection refused"}}
 [fail] Requesting certificate for <my virtualhost>      
ERROR Unprocessable Entity:
	challenge: Connection refused
 (Kontena::Errors::StandardErrorHash)
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:535:in `handle_error_response'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:343:in `rescue in request'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:284:in `request'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:208:in `post'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/certificate/request_command.rb:15:in `block in execute'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/spinner.rb:138:in `spin'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/common.rb:36:in `spinner'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/certificate/request_command.rb:14:in `execute'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/command.rb:215:in `run'
/var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/command.rb:215:in `run'
/var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/command.rb:215:in `run'
/var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/bin/kontena:19:in `<top (required)>'
/usr/local/bin/kontena:22:in `load'
/usr/local/bin/kontena:22:in `<main>'
DEBUG Execution took 1.249 seconds
DEBUG Kontena::Errors::StandardErrorHash status 422
/var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:535:in `handle_error_response': Unprocessable Entity: (Kontena::Errors::StandardErrorHash)
	challenge: Connection refused
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:343:in `rescue in request'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:284:in `request'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/client.rb:208:in `post'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/certificate/request_command.rb:15:in `block in execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/spinner.rb:138:in `spin'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/common.rb:36:in `spinner'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/cli/certificate/request_command.rb:14:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/command.rb:215:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/command.rb:215:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/lib/kontena/command.rb:215:in `run'
	from /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/2.3.0/gems/kontena-cli-1.4.2/bin/kontena:19:in `<top (required)>'
	from /usr/local/bin/kontena:22:in `load'
	from /usr/local/bin/kontena:22:in `<main>'
```

The domain is configured properly and I'm currently using the application via unsecure http without any issues.

**Comment by piscis** [comment]
Similar thing happed to me. 

What I did that I belief led to the error was that I first registered with letsencript and then created DNS based certificates. Afterwards I tried to switch over to TLS based and ran into timeouts and status 422 errors. Of course a made sure to clean out all of the DNS based certificates first but did not help.

The only way I was able to resolve this for me was to:

1. remove the LE_ENCRYPT_KEY from the vault
2. Clean out all DNS based certificates
3. Remove the acme-text DNS entries (just to be sure)
3. Reregister with a different email address to letsencrypt via kontena CLI
4. Start the TLS based registration again. 

Strange think was that for new domains were I did not use DNS based SSL certificates it worked out of the box and I had no timeouts or 422 errors at all.

Maybe thats an approach you can try.

**Comment by jakolehm** [comment]
> The domain is configured properly and I'm currently using the application via unsecure http without any issues.

@mlaitinen does linked loadbalancer have port `443` open?

**Comment by mlaitinen** [comment]
@jakolehm At first it didn't, but then I opened it. It didn't help.

**Comment by mlaitinen** [comment]
Ok so somehow magically requesting a certificate started working. I didn't do anything special.

**Comment by SpComb** [comment]
The `challenge: Connection refused` error means that the Let's Encrypt servers verifying the challenge are unable to connect to the domain being authorized on port 443.
