### ISSUE TITLE
Container exec with TTY fails with Celluloid::TaskTerminated on tty resize

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3140]
Sometimes a `kontena service/container exec -it` can fail with a `Celluloid::TaskTerminated` error:

```
$ bin/kontena service exec -it redis echo test
 [error] RuntimeError : Celluloid::TaskTerminated: task was terminated
         See /home/kontena/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

This seems to be related to the `Docker::Exec#resize`:

```
D, [2017-12-15T11:49:56.348395 #1] DEBUG -- Kontena::RpcServer: rpc request: Kontena::Rpc::DockerContainerApi#create_exec ["0536a97cfe6a9d5ca5b39b3a2e1eb270c051d2a55df4c68d6af10ae5cb49b64a"]
I, [2017-12-15T11:49:56.457961 #1]  INFO -- Kontena::Actors::ContainerExec: initialized (session b28f5eca-3287-4c8a-bc4c-0016750d67f9)
D, [2017-12-15T11:49:56.553695 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#run_exec ["b28f5eca-3287-4c8a-bc4c-0016750d67f9", ["echo", "test"], true, true]
I, [2017-12-15T11:49:56.554123 #1]  INFO -- Kontena::Actors::ContainerExec: starting command: ["echo", "test"] (tty: true, stdin: true)
D, [2017-12-15T11:49:56.566356 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: exec_create: echo test
D, [2017-12-15T11:49:56.568927 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#tty_resize ["b28f5eca-3287-4c8a-bc4c-0016750d67f9", {"width"=>425, "height"=>126}]
E, [2017-12-15T11:49:56.655822 #1] ERROR -- : Actor crashed!
Docker::Error::ServerError: containerd: process not found for container

	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/connection.rb:50:in `rescue in request'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/connection.rb:38:in `request'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	/usr/lib/ruby/gems/2.4.0/gems/docker-api-1.33.6/lib/docker/exec.rb:93:in `resize'
	/app/lib/kontena/actors/container_exec.rb:43:in `tty_resize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2017-12-15T11:49:56.656010 #1] ERROR -- Kontena::Actors::ContainerExec: task was terminated (Celluloid::TaskTerminated)
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in `handle_crash'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in `run'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
D, [2017-12-15T11:49:56.832929 #1] DEBUG -- Kontena::Workers::ServicePodWorker: container event: exec_start: echo test
D, [2017-12-15T11:49:56.841057 #1] DEBUG -- Kontena::RpcServer: rpc notification: Kontena::Rpc::DockerContainerApi#terminate_exec ["b28f5eca-3287-4c8a-bc4c-0016750d67f9"]
```

**Comment by SpComb** [comment]
This might be a regression case where the error code changed during the Docker 1.12 -> 17.09 upgrade?

The agent contains code to explicitly [handle](https://github.com/kontena/kontena/blob/fea8711fffae58d7d0d27576888335e4df7ec7ff/agent/lib/kontena/actors/container_exec.rb#L47-L59) this kind of `process not found for container` error, because it's a race condition that's very likely to happen between the container exec create/start and the resize. However, that code rescues `Docker::Error::NotFoundError`, and this is raising `Docker::Error::ServerError`...

**Comment by SpComb** [comment]
I seem to be getting a nearly 100% failure rate on container execs with Docker `17.09.0-ce`...?
