### ISSUE TITLE
[1.4.3.rc1] CLI exec fails with ERROR undefined method `raw' for #<IO:<STDIN>> (NoMethodError)

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3160]
Looks like the [`STDIN.raw`](https://github.com/kontena/kontena/blob/v1.4.3.rc1/cli/lib/kontena/cli/helpers/exec_helper.rb#L37) is part of the [`require 'io/console'`](https://ruby-doc.org/stdlib-2.3.0/libdoc/io/console/rdoc/IO.html#method-i-raw) that was removed in #3139

Somehow this only seems to fail for me with the 1.4.3.rc1 gem installed, and when running with `DEBUG=true`. The tty exec does work when running the gem without `DEBUG`, and also when running the development version with `bundle exec`... :neutral_face:

```
$ DEBUG=true kontena service exec -it redis bash
DEBUG Kontena CLI 1.4.3.rc1 (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-cloud from /home/kontena/.kontena/gems/2.3.1/gems/kontena-plugin-cloud-1.2.0/lib/kontena_cli_plugin.rb
DEBUG Loading plugin kontena-plugin-digitalocean from /home/kontena/.kontena/gems/2.3.1/gems/kontena-plugin-digitalocean-0.3.3/lib/kontena_cli_plugin.rb
DEBUG Running Kontena::MainCommand with ["service", "exec", "-it", "redis", "bash"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::ServiceCommand with ["exec", "-it", "redis", "bash"] -- callback matcher = 'nil'
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Configuration loaded with 25 servers and 2 accounts.
DEBUG Current master: terom-test143
DEBUG Current grid: test
DEBUG Current account: kontena
DEBUG Running Kontena::Cli::Services::ExecCommand with ["-it", "redis", "bash"] -- callback matcher = 'services exec'
DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>"/home/kontena/.kontena/certs/188.226.188.22.pem", :ssl_verify_peer_host=>"Test"}
DEBUG [Request]: GET https://188.226.188.22/v1/services/test/null/redis/containers (ssl_verify: true)  | Headers: {Accept: application/json, Authorization: Bearer} 
DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.4.3.rc1}  | Status: 200 | Body: "{\"containers\":[{\"id\":\"test/terom-test143-1/redis-1\",\"name\":\"redis-1\",..."
DEBUG websocket exec connect... wss://188.226.188.22/v1/containers/test/terom-test143-1/redis-1/exec?interactive=true&tty=true
DEBUG websocket exec open
DEBUG websocket exec write: {"cmd"=>["bash"]}
DEBUG websocket exec write: {"tty_size"=>{:width=>212, :height=>63}}
ERROR undefined method `raw' for #<IO:<STDIN>> (NoMethodError)
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/helpers/exec_helper.rb:37:in `read_stdin'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/helpers/exec_helper.rb:115:in `block in websocket_exec_write_thread'
ERROR websocket exec error: stdin read NoMethodError: undefined method `raw' for #<IO:<STDIN>>
DEBUG Execution took 1.221 seconds
DEBUG RuntimeError
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/helpers/exec_helper.rb:177:in `block in websocket_exec': stdin read NoMethodError: undefined method `raw' for #<IO:<STDIN>> (RuntimeError)
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-websocket-client-0.1.1/lib/kontena/websocket/client.rb:64:in `connect'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/helpers/exec_helper.rb:163:in `websocket_exec'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/helpers/exec_helper.rb:204:in `container_exec'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/services/exec_command.rb:88:in `block in execute_container'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/services/exec_command.rb:78:in `maybe_spinner'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/services/exec_command.rb:87:in `execute_container'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/cli/services/exec_command.rb:68:in `execute'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/command.rb:215:in `run'
	from /home/kontena/.gem/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/command.rb:215:in `run'
	from /home/kontena/.gem/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/command.rb:215:in `run'
	from /home/kontena/.gem/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/bin/kontena:19:in `<top (required)>'
	from /home/kontena/.local/bin/kontena:23:in `load'
	from /home/kontena/.local/bin/kontena:23:in `<main>'
```

**Comment by SpComb** [comment]
Tracing with `Module#method_added` shows that it really is dependent on `DEBUG`: the `io/console` is required as a side-effect of the [`Kontena::PluginManager#init`](https://github.com/kontena/kontena/blob/ffc903d2bcb144ac2a278d35590ac8dbb5eb81bb/cli/lib/kontena/plugin_manager.rb#L14) => `Common.use_dummy_ui unless Kontena.debug?`

```
METHOD ADD IO#raw @ /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/lib/ruby/2.3.0/rubygems/user_interaction.rb:9:in `<top (required)>'
        /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/plugin_manager/common.rb:23:in `use_dummy_ui'
        /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/lib/kontena/plugin_manager.rb:14:in `init'
        /home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.4.3.rc1/bin/kontena:18:in `<top (required)>'
        /home/kontena/.local/bin/kontena:29:in `load'
        /home/kontena/.local/bin/kontena:29:in `<main>'
```
