### ISSUE TITLE
CLI omnibus fails sporadically on sourceforce https -> http mirror redirect

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3166]
Apparently still not fixed even with `source url: "http://tukaani.org/xz/xz-#{version}.tar.gz", unsafe: true` :(

See earlier history

* https://github.com/chef/omnibus-software/issues/780
* #2903
* #2907

```
/home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open-uri.rb:225:in `open_loop': redirection forbidden: https://downloads.sourceforge.net/project/lzmautils/xz-5.2.3.tar.gz?r=&ts=1513786876&use_mirror=cfhcable -> http://cfhcable.dl.sourceforge.net/project/lzmautils/xz-5.2.3.tar.gz (RuntimeError)

	from /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open-uri.rb:151:in `open_uri'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'

	from /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open-uri.rb:721:in `open'

	from /home/travis/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/open-uri.rb:35:in `open'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/download_helpers.rb:80:in `download_file!'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/software.rb:897:in `fetch'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/project.rb:1066:in `block (3 levels) in download'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/thread_pool.rb:62:in `loop'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/thread_pool.rb:61:in `catch'

	from /home/travis/.rvm/gems/ruby-2.4.2/gems/omnibus-5.6.1/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```

**Comment by SpComb** [comment]
Also mentioning this here, on the general subject of omnibus build failures due to randomly misbehaving source mirrors:

```
      [Software: libxml2] I | 2018-03-15T06:08:29+00:00 | Resolving manifest entry for libxml2
    [NetFetcher: libxml2] I | 2018-03-15T06:08:29+00:00 | Downloading from `ftp://xmlsoft.org/libxml2/libxml2-2.9.7.tar.gz'
Progress: |/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:470:in `getresp': 425 Security: Bad IP connecting. (Net::FTPTempError)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:497:in `block in sendcmd'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:495:in `sendcmd'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:554:in `transfercmd'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:636:in `block (2 levels) in retrbinary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:310:in `with_binary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:634:in `block in retrbinary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:633:in `retrbinary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:796:in `buffer_open'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:212:in `block in open_loop'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:210:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:210:in `open_loop'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:151:in `open_uri'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:721:in `open'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:35:in `open'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/download_helpers.rb:80:in `download_file!'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/software.rb:897:in `fetch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:62:in `loop'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:61:in `catch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
rake aborted!
```
