### ISSUE TITLE
uncatched error?

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#317]
running 0.10.0.beta, on deploy an app - from docker logs

```
node_1       | Docker::Error::ConflictError: Conflict. The name "kontena-dev-api-1" is already in use by container c39f998d5a6f. You have to remove (or rename) that container to be able to reuse that name.
node_1       | /usr/lib/ruby/gems/2.2.0/gems/docker-api-1.22.0/lib/docker/connection.rb:48:in `rescue in request'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/docker-api-1.22.0/lib/docker/connection.rb:38:in `request'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/docker-api-1.22.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/docker-api-1.22.0/lib/docker/container.rb:228:in `create'
node_1       | /app/lib/kontena/service_pods/creator.rb:97:in `create_container'
node_1       | /app/lib/kontena/service_pods/creator.rb:44:in `perform'
node_1       | /app/lib/kontena/service_pods/creator.rb:60:in `block in perform_async'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `call'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:14:in `block in new'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
node_1       | /usr/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

**Comment by jakolehm** [comment]
I think this is fixed in latest beta. Let's re-open if this error comes back.
