### ISSUE TITLE
e2e plugin related specs break when running with bundle exec

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3173]
Per #3148 (#3052 + #3170) the e2e specs should be run using `bundle exec rspec`. However, this also affects the `Kommando.run('kontena ...')` command environment, and causes the CLI to not load any plugins.

```
Failures:

  1) app subcommand with the app-command plugin app deploy deploys a simple app
     Failure/Error: expect(k.code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/features/plugin/app-command/deploy_spec.rb:10:in `block (5 levels) in <top (required)>'
     # ./spec/support/shell.rb:54:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:53:in `chdir'
     # ./spec/support/shell.rb:53:in `with_fixture_dir'
     # ./spec/features/plugin/app-command/deploy_spec.rb:7:in `block (4 levels) in <top (required)>'

  2) app subcommand with the app-command plugin app ps returns list
     Failure/Error: expect(k.code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/features/plugin/app-command/ps_spec.rb:10:in `block (5 levels) in <top (required)>'
     # ./spec/support/shell.rb:54:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:53:in `chdir'
     # ./spec/support/shell.rb:53:in `with_fixture_dir'
     # ./spec/features/plugin/app-command/ps_spec.rb:7:in `block (4 levels) in <top (required)>'

  3) app subcommand with the app-command plugin app remove removes a deployed app
     Failure/Error: expect(k.code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/features/plugin/app-command/remove_spec.rb:10:in `block (5 levels) in <top (required)>'
     # ./spec/support/shell.rb:54:in `block in with_fixture_dir'
     # ./spec/support/shell.rb:53:in `chdir'
     # ./spec/support/shell.rb:53:in `with_fixture_dir'
     # ./spec/features/plugin/app-command/remove_spec.rb:7:in `block (4 levels) in <top (required)>'

  4) plugin install installs a plugin
     Failure/Error: expect(k.out).to match(/aws/)
     
       expected "\e[1mNAME\e[0m  \e[1mVERSION\e[0m  \e[1mDESCRIPTION\e[0m\r\n" to match /aws/
       Diff:
       @@ -1,2 +1,2 @@
       -/aws/
       +NAME  VERSION  DESCRIPTION
       
     # ./spec/features/plugin/install_spec.rb:12:in `block (2 levels) in <top (required)>'

  5) plugin install attempts to upgrade a plugin
     Failure/Error: expect(k.out).to match(/aws/)
     
       expected "\e[1mNAME\e[0m  \e[1mVERSION\e[0m  \e[1mDESCRIPTION\e[0m\r\n" to match /aws/
       Diff:
       @@ -1,2 +1,2 @@
       -/aws/
       +NAME  VERSION  DESCRIPTION
       
     # ./spec/features/plugin/install_spec.rb:19:in `block (2 levels) in <top (required)>'

  6) plugin uninstall removes installed plugin
     Failure/Error: expect(k.code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./spec/features/plugin/uninstall_spec.rb:10:in `block (2 levels) in <top (required)>'

Failed examples:

rspec ./spec/features/plugin/app-command/deploy_spec.rb:6 # app subcommand with the app-command plugin app deploy deploys a simple app
rspec ./spec/features/plugin/app-command/ps_spec.rb:6 # app subcommand with the app-command plugin app ps returns list
rspec ./spec/features/plugin/app-command/remove_spec.rb:6 # app subcommand with the app-command plugin app remove removes a deployed app
rspec ./spec/features/plugin/install_spec.rb:8 # plugin install installs a plugin
rspec ./spec/features/plugin/install_spec.rb:15 # plugin install attempts to upgrade a plugin
rspec ./spec/features/plugin/uninstall_spec.rb:8 # plugin uninstall removes installed plugin
```

**Comment by SpComb** [comment]
Removing from the 1.5 milestone because the workaround for this is to run the e2e specs using `gem build kontena-cli.gemspec && gem install kontena-cli-*.gem` to get the standard rubygems binwrapper.
