### ISSUE TITLE
Server RPCs stop working if the MongoPubsub actor crashes and restarts

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3206]
If some exception causes the server's `MongoPubsub` actor to crash, the actor will normally get restarted by the Celluloid supervisor. Because it is the only supervised top-level actor, the `@supervisor.actors.first` will point to the new actor, and any future `publish` etc calls will work.

However, the server `WebsocketBackend` middleware class only ever calls `MongoPubsub.subscribe` once, when the worker starts up. If the `MongoPubsub` actor crashes, then the [`WebsocketBackend#subscribe_to_rpc_channel`](https://github.com/kontena/kontena/blob/364629689a5bc00721f4dde0c3b59b8206672292/server/app/middlewares/websocket_backend.rb#L44) subscription will get lost.

This causes all server -> agent RPCs to stop working.

The `/v1/ping` API will still return HTTP 200, because the `MongoPubsub.actor.alive?` is still true - it's just lost the subscriptions.

## Examples

```
D, [2018-01-09T09:38:41.292809 #13] DEBUG -- MongoPubsub: subscribe rpc_client:1159137003
D, [2018-01-09T09:38:41.293663 #13] DEBUG -- MongoPubsub: publish rpc_client
E, [2018-01-09T09:38:41.293788 #13] ERROR -- : Actor crashed!
RuntimeError: test
	/app/app/services/mongo_pubsub.rb:99:in `publish'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
I, [2018-01-09T09:38:41.293877 #13]  INFO -- MongoPubsub: terminated
I, [2018-01-09T09:38:41.294765 #13]  INFO -- MongoPubsub: initialized
I, [2018-01-09T09:38:41.297421 #13]  INFO -- MongoPubsub: starting to tail collection
172.17.0.1 - - [09/Jan/2018:09:38:51 +0000] "GET /v1/nodes/development/core-01/health HTTP/1.1" 422 52 10.1472
```

All RPCs for that server worker will timeout, because while the `RpcClient` -> `MongoPubsub.publish/subscribe` works fine, the `WebsocketBackend` never sees the messages.

**Comment by SpComb** [comment]
Alternatives for fixing this:

* Crash the entire server worker process if the `MongoPubsub` actor crashes
* Make all of the pubsub subscribers also be actors linked to the `MongoPubsub` actor, so that they also crash and re-subscribe if the pubsub actor crashes - this would include refactoring the `WebsocketBackend` to delegate all of the logic from running in the EM thread to running in an actor
* Fix the `MongoPubsub.subscribe` class method implementation to make the subscriptions persistent across actor crashes/restarts
