### ISSUE TITLE
Server MongoPubsub actor crashed: Celluloid::Task::Fibered::StackError: stack level too deep @as_json

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3207]
Unknown what causes this.

```
E, [2018-01-09T08:32:04.934714 #13] ERROR -- : Actor crashed!
Celluloid::Task::Fibered::StackError: stack level too deep @as_json (see https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors)
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:28:in `rescue in deliver'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:26:in `deliver'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:83:in `resume'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:341:in `task'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:72:in `task'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:65:in `invoke'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:34:in `block in initialize'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/handlers.rb:38:in `call'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/handlers.rb:20:in `handle_message'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:283:in `handle_message'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:156:in `block in run'
    /usr/lib/ruby/gems/2.4.0/gems/timers-4.1.2/lib/timers/group.rb:68:in `wait'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
I, [2018-01-09T08:32:04.934954 #13]  INFO -- WebsocketBackend: node XI4K:NPOL:EQJ4:S4V7:EN3B:DHC5:KZJD:F3U2:PCAN:46EV:IO4A:63S5 connection closed with code 1006: 
I, [2018-01-09T08:32:04.942583 #13]  INFO -- Agent::NodeUnplugger: Disconnected node development/core-01 connected at 2018-01-09 08:31:07 UTC
I, [2018-01-09T08:32:04.944737 #13]  INFO -- MongoPubsub: starting to tail collection
```

This somehow also breaks the agent websocket connection:

```
E, [2018-01-09T08:31:06.390374 #1] ERROR -- : Actor crashed!
EOFError: end of buffer reached
    /app/lib/kontena/websocket_client.rb:301:in `unpack'
    /app/lib/kontena/websocket_client.rb:301:in `on_message'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
    /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

And also leads to broken server RPCs even after the agent reconnects: #3206

EDIT: Complete backtrace (after [patching `Celluloid::Task::Fibered#deliver`](https://gist.github.com/SpComb/9925fe83cc16ca7cf5a1b959464014e5#file-celluloid_patch-rb) to not eat the backtrace) shows that it's activesupport's `Object#to_json` recursing: https://gist.github.com/SpComb/9925fe83cc16ca7cf5a1b959464014e5#file-backtrace-log

**Comment by SpComb** [comment]
Repro'd this enough to trace down the celluloid call that leads to this crash. It looks like [`RpcServer#send_message`](https://github.com/kontena/kontena/blob/f90cb36bffd77a65a26f7a9971a579b983217ef0/server/app/services/rpc_server.rb#L127)  gets called with something that contains a reference to the `MongoPubsub#async` celluloid proxy:

```
TRACE ASYNC CALL  -> MongoPubsub#as_json @ /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:140:in `map'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:140:in `as_json'
        /app/app/services/rpc_server.rb:127:in `block in send_message'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
        /app/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

```
TRACE ASYNC CALL  -> MongoPubsub#to_msgpack @ /app/app/services/rpc_server.rb:127:in `dump'
        /app/app/services/rpc_server.rb:127:in `block in send_message'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
        /app/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
```

Guessing this has something to do with the `/containers/health` handler, as it happens immediately after this:

```
TRACE ASYNC CALL RpcServer -> MongoPubsub#publish @ /app/app/services/mongo_pubsub.rb:122:in `publish_async'
        /app/app/models/event_stream.rb:43:in `publish_async'
        /app/app/models/container.rb:192:in `publish_update_event'
        /app/app/models/container.rb:125:in `set_health_status'
        /app/app/services/rpc/container_handler.rb:84:in `health'
        /app/app/services/rpc_server.rb:71:in `handle_request'
        /app/app/services/rpc_server.rb:55:in `process!'
```

**Comment by SpComb** [comment]
The agent [ContainerHealthCheckWorker calls `rpc_client.async.request('/containers/health', [msg])`](https://github.com/kontena/kontena/blob/f90cb36bffd77a65a26f7a9971a579b983217ef0/agent/lib/kontena/workers/container_health_check_worker.rb#L47), so the result of the the server [`Rpc::ContainerHandler#health`](https://github.com/kontena/kontena/blob/f90cb36bffd77a65a26f7a9971a579b983217ef0/server/app/services/rpc/container_handler.rb#L84) ends up getting serialized as a response by the server...

Looks like that return value ends up being the celluloid async proxy for `MongoPubsub` if [`Container#set_health_status`](https://github.com/kontena/kontena/blob/f90cb36bffd77a65a26f7a9971a579b983217ef0/server/app/services/rpc/container_handler.rb#L84) hits the [`publish_update_event if health_status_changed`](https://github.com/kontena/kontena/blob/f90cb36bffd77a65a26f7a9971a579b983217ef0/server/app/models/container.rb#L125) condition, which calls `publish_async` -> [`MongoPubsub.publish_async(CHANNEL, event)`](https://github.com/kontena/kontena/blob/f90cb36bffd77a65a26f7a9971a579b983217ef0/server/app/models/event_stream.rb#L43).

**Comment by SpComb** [comment]
Confirmed, the `Rpc::ContainerHandler#health` is returning a `Celluloid::Proxy::Async<MongoPubsub>` which ends up getting serialized from within the `EM.next_tick { ... }` handler... it's not crashing EM, but it it sending async calls to the pubsub actor, which ends up crashing in some `Object#as_json` recursion.

```
D, [2018-01-15T10:08:54.660157 #9] DEBUG -- RpcServer: /containers/health => #<Celluloid::Proxy::Async:0x0000557a13c55e80>
TRACE ASYNC CALL  -> MongoPubsub#as_json @ /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:140:in `map'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:140:in `as_json'
        /app/app/services/rpc_server.rb:129:in `block in send_message'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
        /app/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
TRACE ASYNC CALL  -> MongoPubsub#to_msgpack @ /app/app/services/rpc_server.rb:129:in `dump'
        /app/app/services/rpc_server.rb:129:in `block in send_message'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `times'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
        /usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
        /app/app/initializers/eventmachine.rb:10:in `block in <top (required)>'
Celluloid::Task::Fibered::StackError: stack level too deep @as_json @ /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/instance_variables.rb:13:in `map'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/instance_variables.rb:13:in `instance_values'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:50:in `as_json'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:159:in `each'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:159:in `map'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:159:in `as_json'
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:50:in `as_json'
...
        /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:50:in `as_json'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
        /app/lib/celluloid_patch.rb:6:in `rescue in deliver'
        /app/lib/celluloid_patch.rb:3:in `deliver'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:83:in `resume'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:341:in `task'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:72:in `task'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:65:in `invoke'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:34:in `block in initialize'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/handlers.rb:38:in `call'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/handlers.rb:20:in `handle_message'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:283:in `handle_message'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:156:in `block in run'
        /usr/lib/ruby/gems/2.4.0/gems/timers-4.1.2/lib/timers/group.rb:68:in `wait'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
        /usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
```

I'm guessing the websocket disconnect happens because the `MessagePack.dump(Celluloid::Proxy::Async<MongoPubsub>)` results in something very weird... not entirely sure what, the `#to_msgpack` is going to return `self`, but with the `.bytes` in between I have no idea what actually ends up getting passed to `ws.send`, and how EM deals with that.

**Comment by SpComb** [comment]
Looks like this is a regression in 1.5.0.dev from #3202: https://github.com/kontena/kontena/commit/3ab5a0de50af611eb2f6e9531a806d86e1ffeea3#diff-51967a5b5276e866374473d45e180bd5

The same code path used to return from [`MongoPubsub.publish(...)`](https://github.com/kontena/kontena/blob/v1.4.3/server/app/services/rpc/container_handler.rb#L86), at least `if container.grid_service`. That probably ends up returning some mongoid document from `self.collection.insert_one(...)`... which is probably still unintentional, but it didn't get noticed because it doesn't explode.
