### ISSUE TITLE
MongoPubsub::Subscription: undefined method `users' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ptsurbeleu** [kontena/kontena#3213]
Just have caught the following stack trace in my Kontena Master's logs (v1.4.3).
```
<IP REDACTED> - - [12/Jan/2018:05:30:10 +0000] "DELETE /v1/grids/test HTTP/1.1" 200 2 0.3053
E, [2018-01-12T05:30:10.616183 #7] ERROR -- MongoPubsub::Subscription: undefined method `users' for nil:NilClass (NoMethodError)
/app/app/services/cloud/websocket_client.rb:295:in `resolve_users'
/app/app/services/cloud/websocket_client.rb:275:in `send_notification_message'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
(celluloid):0:in `remote procedure call'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
/app/app/services/cloud/websocket_client.rb:313:in `block in subscribe_events'
/app/app/services/mongo_pubsub.rb:46:in `send_message'
/app/app/services/mongo_pubsub.rb:37:in `process'
/app/app/services/mongo_pubsub.rb:65:in `block in process_subscription'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
I, [2018-01-12T05:30:10.622216 #7]  INFO -- CloudWebsocketClientManager: Client exited: undefined method `users' for nil:NilClass
E, [2018-01-12T05:30:10.612687 #7] ERROR -- : Actor crashed!
NoMethodError: undefined method `users' for nil:NilClass
	/app/app/services/cloud/websocket_client.rb:295:in `resolve_users'
	/app/app/services/cloud/websocket_client.rb:275:in `send_notification_message'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by jnummelin** [comment]
From the logs it appears that you were trying to delete a grid on this happened?

**Comment by nevalla** [comment]
yes I can see possible bug here:
https://github.com/kontena/kontena/blob/master/server/app/services/cloud/websocket_client.rb#L291-L300

We should add check that grid still exist when requesting users.

**Comment by ptsurbeleu** [comment]
Thanks a ton folks for the prompt turnaround!
