### ISSUE TITLE
CLI plugin uninstall: NoMethodError : undefined method `name' for "aws":String

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3228]
```
$ DEBUG=true kontena plugin uninstall aws
DEBUG Kontena CLI 1.5.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-app-command from /home/terom/.kontena/gems/2.3.1/gems/kontena-plugin-app-command-0.1.0/lib/kontena_cli_plugin.rb
DEBUG Loading plugin kontena-plugin-aws from /home/terom/.kontena/gems/2.3.1/gems/kontena-plugin-aws-0.3.1/lib/kontena_cli_plugin.rb
DEBUG Loading plugin kontena-plugin-digitalocean from /home/terom/.kontena/gems/2.3.1/gems/kontena-plugin-digitalocean-0.3.3/lib/kontena_cli_plugin.rb
DEBUG Running Kontena::MainCommand with ["plugin", "uninstall", "aws"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::PluginCommand with ["uninstall", "aws"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::Plugins::UninstallCommand with ["aws"] -- callback matcher = 'plugins uninstall'
DEBUG Execution took 0.113 seconds
DEBUG NoMethodError
/home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/plugin_manager/common.rb:38:in `block in installed': undefined method `name' for "aws":String (NoMethodError)
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/plugin_manager/common.rb:38:in `each'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/plugin_manager/common.rb:38:in `find'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/plugin_manager/common.rb:38:in `installed'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/plugin_manager/common.rb:43:in `installed?'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/cli/plugins/uninstall_command.rb:13:in `block in execute'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/cli/plugins/uninstall_command.rb:12:in `each'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/cli/plugins/uninstall_command.rb:12:in `execute'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/command.rb:215:in `run'
	from /home/terom/.gem/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/command.rb:215:in `run'
	from /home/terom/.gem/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/lib/kontena/command.rb:215:in `run'
	from /home/terom/.gem/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /home/terom/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0.dev/bin/kontena:19:in `<top (required)>'
	from /home/terom/.local/bin/kontena:23:in `load'
	from /home/terom/.local/bin/kontena:23:in `<main>'
```

**Comment by SpComb** [comment]
Looks like the [`parameter ..., attribute_name: :plugins`](https://github.com/kontena/kontena/pull/3193/files#diff-64f7de171543c9d544989fc54bb2dc7cR9) added in #3193 breaks the included `Kontena::PluginManager::Common` mixin, because it overrides the `def plugins`.

Too many `include`s is bad for you 🙈
