### ISSUE TITLE
service exec fails with Error during WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3231]
This seems to happen sporadically in the e2e specs, but it's also reproducible via the CLI. It seems like once the server goes into a state where the service exec fails, then the service exec will keep failing.

This now shows up in the server logs as an `RpcClient::Error (Container not found)` from the agent, which means that the server `@container.container_id` is wrong.

Indeed, this can be confirmed:

```
$ kontena service create test-1 redis:3.0
 [done] Creating test-1 service      
$ kontena service deploy test-1
 [done] Deploying service test-1      
⊛ Deployed instance e2e/null/test-1-1 to node terom-e2e-dev
$ kontena service exec test-1 hostname -s
 [error] Error during WebSocket handshake: Unexpected response code: 500
$ kontena container list
 [done] Retrieving container list     
CONTAINER_ID                        IMAGE                       COMMAND                         CREATED          STATUS
terom-e2e-dev/test-1-1              redis:3.0                   "docker-entrypoint.sh redi.."   20 seconds ago   running
...
$ kontena container inspect terom-e2e-dev/test-1-1
 [error] 404 : Not Found (/v1/containers/e2e/terom-e2e-dev/test-1-1/inspect)
```

The container ID sent by the server in the RPC does not match up with the actual container ID:

```
$ docker ps -f name=test-1-1
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
db39fdc56b53        redis:3.0           "/w/w docker-entry..."   2 minutes ago       Up 2 minutes        6379/tcp            test-1-1
$ docker logs kontena-agent | grep 'rpc request'
...
D, [2018-02-01T12:40:07.961066 #1] DEBUG -- Kontena::RpcServer: rpc request: Kontena::Rpc::DockerContainerApi#create_exec ["ab1f2b232eadb90b1e10fb977a5be5d2d6242f26acaa7546bbefbf4c9523e8c4"]
D, [2018-02-01T12:40:24.554622 #1] DEBUG -- Kontena::RpcServer: rpc request: Kontena::Rpc::DockerContainerApi#inspect ["ab1f2b232eadb90b1e10fb977a5be5d2d6242f26acaa7546bbefbf4c9523e8c4"]
$ docker inspect -f '{{.ID}}' test-1-1
db39fdc56b5326fb20558977b500c92449bcbed7308644da54ef6b25cfae6525
```

The server is sending the RPCs with `@container.container_id` being `ab1f2b232eadb90b1e10fb977a5be5d2d6242f26acaa7546bbefbf4c9523e8c4`, whereas the actual container ID is `db39fdc56b5326fb20558977b500c92449bcbed7308644da54ef6b25cfae6525`

```
api_1      | 172.18.0.1 - - [01/Feb/2018:12:34:33 +0000] "GET /v1/services/e2e/null/test-1/containers HTTP/1.1" 200 1701 0.0916
api_1      | 
api_1      | RpcClient::Error (Container not found):
api_1      |   agent:/app/lib/kontena/rpc/docker_container_api.rb:125:in `rescue in create_exec'
api_1      |   agent:/app/lib/kontena/rpc/docker_container_api.rb:118:in `create_exec'
api_1      |   agent:/app/lib/kontena/rpc_server.rb:45:in `handle_request'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
api_1      |   agent:/usr/lib/ruby/gems/2.4.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
api_1      |   <RPC>
api_1      |   /app/app/services/rpc_client.rb:60:in `request'
api_1      |   /app/app/services/docker/streaming_executor.rb:68:in `exec_create'
api_1      |   /app/app/services/docker/streaming_executor.rb:62:in `setup'
api_1      |   /app/app/routes/v1/containers_api.rb:66:in `block (4 levels) in <class:ContainersApi>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
api_1      |   /app/app/routes/v1/containers_api.rb:57:in `block (3 levels) in <class:ContainersApi>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:767:in `always'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:758:in `_verb'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:388:in `get'
api_1      |   /app/app/routes/v1/containers_api.rb:35:in `block (2 levels) in <class:ContainersApi>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
api_1      |   /app/app/routes/v1/containers_api.rb:31:in `block in <class:ContainersApi>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda/plugins/error_handler.rb:66:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
api_1      |   /app/app/routes/v1_api.rb:16:in `block (2 levels) in <class:Api>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:857:in `match'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `block in match_all'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `each'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `all?'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:870:in `match_all'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:831:in `if_match'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
api_1      |   /app/app/routes/v1_api.rb:16:in `block in <class:Api>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:117:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:660:in `run'
api_1      |   /app/server.rb:54:in `block (2 levels) in <class:Server>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:832:in `if_match'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:506:in `on'
api_1      |   /app/server.rb:53:in `block in <class:Server>'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `instance_exec'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:261:in `block in call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `catch'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:259:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/roda-2.26.0/lib/roda.rb:228:in `block in build_rack_app'
api_1      |   /app/app/middlewares/version_injector.rb:12:in `call'
api_1      |   /app/app/middlewares/token_authentication.rb:70:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
api_1      |   /app/app/middlewares/websocket_backend.rb:75:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
api_1      |   /usr/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
api_1      | 
api_1      | 172.18.0.1 - - [01/Feb/2018:12:34:33 +0000] "GET /v1/containers/e2e/terom-e2e-dev/test-1-1/exec HTTP/1.1" 500 5480 0.1036
```

**Comment by SpComb** [comment]
Remembering to run `kontena container list -a` reveals this to be a case of #2978 Duplicate/ghost containers... there are two `terom-e2e-dev/test-1-1` containers on the server, and the server is using the wrong/older one that is `dead`, instead of the `running` container with the correct ID. This also explains the persistence of this issue:

```
irb(main):007:0> Container.where(name: 'test-1-1').each do |c| puts "#{c.name} #{c.container_id} #{c.status}" end
test-1-1 ab1f2b232eadb90b1e10fb977a5be5d2d6242f26acaa7546bbefbf4c9523e8c4 dead
test-1-1 db39fdc56b5326fb20558977b500c92449bcbed7308644da54ef6b25cfae6525 running
```
