### ISSUE TITLE
[1.5-dev] CLI raises JSON::ParseError for DELETE requests with empty response body

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3251]
Regression from #3240 because the server returns an empty response body with `Content-Type: application/json`: #3250

```
$ DEBUG=api bundle exec bin/kontena master token remove 5a5e0dd3f77ecf000edb4c4f
DEBUG Kontena CLI 1.5.0.dev (ruby-2.3.1+x86_64-linux-gnu)
DEBUG Loading plugin kontena-plugin-hello from /home/kontena/kontena/kontena/cli/examples/kontena-plugin-hello/lib/kontena_cli_plugin.rb
DEBUG Running Kontena::MainCommand with ["master", "token", "remove", "5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::MasterCommand with ["token", "remove", "5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'nil'
DEBUG Running Kontena::Cli::Master::TokenCommand with ["remove", "5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'nil'
DEBUG Loading configuration from /home/kontena/.kontena_client.json
DEBUG Configuration loaded with 25 servers and 2 accounts.
DEBUG Current master: development
DEBUG Current grid: development
DEBUG Current account: kontena
DEBUG Running Kontena::Cli::Master::Token::RemoveCommand with ["5a5e0dd3f77ecf000edb4c4f"] -- callback matcher = 'token remove'
> Destructive command. You can skip this prompt by running this command with --force option. Are you sure? Yes
DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock, Excon::Middleware::Decompress], :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>nil, :ssl_verify_peer_host=>nil}
DEBUG [Request]: DELETE http://localhost:9292/oauth2/tokens/5a5e0dd3f77ecf000edb4c4f | Headers: {Accept: application/json, Accept-Encoding: gzip, Authorization: Bearer} 
DEBUG [Response]: Headers: {Content-Type: application/json, X-Kontena-Version: 1.5.0.dev}  | Status: 201
bundler: failed to load command: bin/kontena (bin/kontena)
Kontena::Errors::StandardError: Invalid response JSON from server for /oauth2/tokens/5a5e0dd3f77ecf000edb4c4f: JSON::ParserError: 743: unexpected token at ''
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:519:in `rescue in parse_json'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:517:in `parse_json'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:490:in `parse_response'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:330:in `request'
  /home/kontena/kontena/kontena/cli/lib/kontena/client.rb:244:in `delete'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/master/token/remove_command.rb:15:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:215:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:20:in `<top (required)>'
DEBUG Execution took 1.871 seconds
DEBUG SystemExit status 1
```

**Comment by kke** [comment]
I suppose any empty response with `Content-Type: application/json` will trigger this?
