### ISSUE TITLE
CLI stacks client NoMethodError : undefined method `+' for nil:NilClass on HTTP 403 response

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3315]
```
$ kontena stack registry push test/whoami.yaml 
 [fail] Pushing test/whoami.yaml to stack registry as terom/whoami:1.0.0     
 [error] NoMethodError : undefined method `+' for nil:NilClass
         See /home/kontena/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

```
    *   Pushing test/whoami.yaml to stack registry as terom/whoami:1.0.0 .. \DEBUG Excon opts: {:omit_default_port=>true, :connect_timeout=>10, :read_timeout=>30, :write_timeout=>10, :ssl_verify_peer=>true, :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock, Excon::Middleware::Decompress], :instrumentor=>Kontena::DebugInstrumentor, :ssl_ca_file=>nil, :ssl_verify_peer_host=>nil}
DEBUG [Request]: POST https://stacks.kontena.io/v2/stack-files (ssl_verify: true)  | Headers: {Accept: application/json, Accept-Encoding: gzip, Content-Type: application/vnd.api+json, Authorization: Bearer}  | Body: "{\"data\":{\"type\":\"stack-files\",\"attributes\":{\"content\":\"stack: terom/..."
    *   Pushing test/whoami.yaml to stack registry as terom/whoami:1.0.0 .. -DEBUG [Error]: Expected([200, 201, 204]) <=> Actual(403 Forbidden)

DEBUG Request POST /v2/stack-files: 403 Forbidden: {"errors":[{"status":403,"source":{"parameter":"user"},"detail":"User not in organization"}]}
 [fail] Pushing test/whoami.yaml to stack registry as terom/whoami:1.0.0     
ERROR undefined method `+' for nil:NilClass (NoMethodError)
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/client.rb:554:in `handle_error_response'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/client.rb:350:in `rescue in request'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/client.rb:287:in `request'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/client.rb:211:in `post'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/stacks_client.rb:39:in `push'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/cli/stacks/registry/push_command.rb:32:in `block in execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/cli/spinner.rb:138:in `spin'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/cli/common.rb:36:in `spinner'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/cli/stacks/registry/push_command.rb:30:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/command.rb:216:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/command.rb:216:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/command.rb:216:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/command.rb:216:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/bin/kontena:22:in `<top (required)>'
/home/kontena/.local/bin/kontena:23:in `load'
/home/kontena/.local/bin/kontena:23:in `<main>'
```

Not sure how, because the response is like `{"errors": ...}`, and the code is for `elsif data.is_a?(Hash) && data.has_key?('error')`?

**Comment by SpComb** [comment]
This happens for all errors, including 422 validation errors:

```
DEBUG Request POST /v2/stack-files: 422 Unprocessable Entity: {"errors":[{"status":422,"source":{"parameter":"server"},"detail":"key not found: \"description\""}]}
 [fail] Pushing test/whoami.yaml to stack registry as terom/whoami:1.0.0     
ERROR undefined method `+' for nil:NilClass (NoMethodError)
/home/kontena/.gem/ruby/2.3.0/gems/kontena-cli-1.5.0/lib/kontena/client.rb:554:in `handle_error_response'
```

**Comment by kke** [comment]
This may be different if you have the cloud plugin installed, it monkeypatches the error handler.

**Comment by SpComb** [comment]
> This may be different if you have the cloud plugin installed, it monkeypatches the error handler.

This happens with `bundle exec`, so without plugins.

**Comment by SpComb** [comment]
> This may be different if you have the cloud plugin installed, it monkeypatches the error handler.

Right... with `bundle exec` on git master, it actually works:

```
$ bundle exec bin/kontena stack registry push test/whoami.yaml 
 [fail] Pushing test/whoami.yaml to stack registry as terom/whoami:1.0.0     
 [error] 422 : Unprocessable Entity:
	errors:
	- status: 422
	  source:
	    parameter: stack_version
	  detail: Version not unique
```

**Comment by SpComb** [comment]
Yes, looks like `kontena-plugin-cloud` is monkeypatching `parse_response` to mangle `{"errors": [{"title": ...}]}` => `{"error": ...}`, and the stack registry `errors` response doesn't have the `title`.
