### ISSUE TITLE
CLI omnibus release builds on travis failing with ftp://xmlsoft.org

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3327]
Assuming the error is related to the libxml download:

```
Progress: |      [Software: libxml2] I | 2018-03-13T07:57:06+00:00 | Resolving manifest entry for libxml2
    [NetFetcher: libxml2] I | 2018-03-13T07:57:06+00:00 | Downloading from `ftp://xmlsoft.org/libxml2/libxml2-2.9.7.tar.gz'
Progress: |/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:470:in `getresp': 425 Security: Bad IP connecting. (Net::FTPTempError)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:497:in `block in sendcmd'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:495:in `sendcmd'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:554:in `transfercmd'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:636:in `block (2 levels) in retrbinary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:310:in `with_binary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:634:in `block in retrbinary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/ftp.rb:633:in `retrbinary'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:796:in `buffer_open'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:212:in `block in open_loop'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:210:in `catch'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:210:in `open_loop'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:151:in `open_uri'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:721:in `open'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:35:in `open'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/download_helpers.rb:80:in `download_file!'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/fetchers/net_fetcher.rb:173:in `download'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/software.rb:897:in `fetch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:62:in `loop'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:61:in `catch'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/omnibus-5.6.8/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
```

This seems to be related to some FTP PASV mode behavior?

**Comment by SpComb** [comment]
The `425 Security: Bad IP connecting` seems to mean that the FTP server is seeing a different source address for the PASV mode data connection, where it is expecting the same source address as the control connection.

Initial guess would be that travis has started doing some NAT pooling for worker jobs where different outgoing connections end up using different source addresses?

**Comment by SpComb** [comment]
Looks like the release tarballs are also available via HTTP with matching checksums: http://xmlsoft.org/sources/
