### ISSUE TITLE
cant create master after update cli: 0.15.0

### ISSUE THREAD

**Issue by 1s22s22p6** [kontena/kontena#919]
kontena master digitalocean create
  
`ERROR: No such sub-command 'digitalocean'`

kontena digitalocean master create

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- kontena/machine/digital_ocean (LoadError)
       	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
       	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
       	from /Library/Ruby/Gems/2.0.0/gems/kontena-plugin-digitalocean-0.1.0/lib/kontena/plugin/digital_ocean/master/create_command.rb:20:in `execute'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
       	from /Library/Ruby/Gems/2.0.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
       	from /Library/Ruby/Gems/2.0.0/gems/kontena-cli-0.15.0/bin/kontena:16:in `<top (required)>'
       	from /usr/local/bin/kontena:23:in `load'
       	from /usr/local/bin/kontena:23:in `<main>'
```

**Comment by nevalla** [comment]
Have you installed digitalocean plugin (`kontena plugin install digitalocean`)?

Just noticed that you have to execute the command with `sudo` if using Ruby version shipped with Mac OS.

**Comment by 1s22s22p6** [comment]
thank you
